# Translations template for nova.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the nova project.
#
# Translators:
# Adriana Chisco Landazábal <achisco94@gmail.com>, 2015
# David Martinez Morata, 2014
# Ed Gonzalez <proplw@gmail.com>, 2015
# Pablo Sanchez <furybeat@gmail.com>, 2015
# Rafael Rivero <rafael@cloudscaling.com>, 2014
# Sergio Cuellar Valdes <scuellarv@kionetworks.com>, 2015
# Andreas Jaeger <jaegerandi@gmail.com>, 2016. #zanata
msgid ""
msgstr ""
"Project-Id-Version: nova 14.0.0.0b3.dev750\n"
"Report-Msgid-Bugs-To: https://bugs.launchpad.net/openstack-i18n/\n"
"POT-Creation-Date: 2016-08-25 06:15+0000\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"PO-Revision-Date: 2016-01-20 01:51+0000\n"
"Last-Translator: Andreas Jaeger <jaegerandi@gmail.com>\n"
"Language: es\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"Generated-By: Babel 2.0\n"
"X-Generator: Zanata 3.7.3\n"
"Language-Team: Spanish\n"

msgid "\"Look for the VDIs failed"
msgstr "\"Ha fallado la búsqueda de las VDIs"

#, python-format
msgid ""
"%(base)s virtual size %(base_size)s larger than flavor root disk size "
"%(size)s"
msgstr ""
"El tamaño virtual %(base_size)s de %(base)s es más grande que el tamaño del "
"disco raíz del sabor %(size)s"

#, python-format
msgid ""
"%(scheme)s is registered as a module twice. %(module_name)s is not being "
"used."
msgstr ""
"%(scheme)s se está registrado como módulo dos veces. %(module_name)s no se "
"encuentra en uso."

#, python-format
msgid ""
"Aggregate %(aggregate_id)s: unrecoverable state during operation on %(host)s"
msgstr ""
"Agregado %(aggregate_id)s: estado irrecuperable durante la operación en "
"%(host)s"

msgid "An error occurred while refreshing the network cache."
msgstr "Ha ocurrido un error al actualizar el cache de red."

#, python-format
msgid "Attaching PCI devices %(dev)s to %(dom)s failed."
msgstr "La asociación de dispositivos PCI %(dev)s a %(dom)s ha fallado."

msgid "Cannot cleanup migration files"
msgstr "No se pueden limpiar los archivos de migración"

#, python-format
msgid "Cannot reboot instance: %s"
msgstr "No se puede reiniciar instancia: %s"

#, python-format
msgid "Caught error: %s"
msgstr "Capturado error: %s"

msgid "Compute driver option required, but not specified"
msgstr ""
"La opción de controlador de cálculo es necesaria, pero no se ha especificado"

#, python-format
msgid "Connection to libvirt failed: %s"
msgstr "Ha fallado la conexión a libvirt: %s"

#, python-format
msgid "Could not bind to %(host)s:%(port)s"
msgstr "No se puede asociar al %(host)s:%(port)s"

msgid "Could not decode scheduler options"
msgstr "No se ha podido decodificar las opciones del programador"

#, python-format
msgid "Could not remove tmpdir: %s"
msgstr "No se ha podido remover directorio temporal: %s"

#, python-format
msgid "Could not start encryption for disk %(device)s: %(exception)s"
msgstr ""
"No pudo comenzar la encriptación para el disco %(device)s: %(exception)s"

#, python-format
msgid "Could not stat scheduler options file %(filename)s"
msgstr ""
"No se ha podido crear estadísticas de archivo de opciones de planificador "
"%(filename)s"

msgid "Couldn't communicate with any cells"
msgstr "No se puede establecer comunicación con alguna celda"

#, python-format
msgid "Couldn't communicate with cell '%s'"
msgstr "No se puede comunicar con la celda '%s'"

#, python-format
msgid "Couldn't lookup app: %s"
msgstr "No se pudo hallar aplicación: %s"

#, python-format
msgid "Couldn't unmount the GlusterFS share %s"
msgstr "No se puede desmontar el recurso compartido GlusterFS %s"

#, python-format
msgid "Couldn't unmount the NFS share %s"
msgstr "No se puede desmontar el recurso compartido NFS %s"

#, python-format
msgid "Couldn't unmount the Quobyte Volume at %s"
msgstr "No se ha podido desmontar el Volumen Quobyte en %s"

#, python-format
msgid "Couldn't unmount the share %s"
msgstr "No se pudo desmontar el compartido %s"

#, python-format
msgid "Creating config drive failed with error: %s"
msgstr "La creación de unidad de configuración ha fallado con el error: %s"

msgid "DB error"
msgstr "Error de BD"

msgid "Destroy VM failed"
msgstr "Ha fallado la destrucción de VM"

msgid "Destroy instance failed"
msgstr "Fallo en la destrucción de la instancia"

#, python-format
msgid "Detaching network adapter failed. Exception: %s"
msgstr "Fallo al desconectar el adaptador de red. Excepción: %s"

#, python-format
msgid ""
"Download handler '%(handler)s' raised an exception, falling back to default "
"handler '%(default_handler)s'"
msgstr ""
"La descarga del manejador '%(handler)s' ha arrojado una excepción, "
"restaurando hacia el manejador predeterminado '%(default_handler)s"

msgid "Download image error"
msgstr "Error en la descarga de la imagen"

#, python-format
msgid "Driver failed to attach volume %(volume_id)s at %(mountpoint)s"
msgstr ""
"El controlador ha fallado al asignar el volumen %(volume_id)s en "
"%(mountpoint)s"

msgid "Environment variable 'NETWORK_ID' must be set."
msgstr "La variable de entorno 'NETWORK_ID' debe ser establecida."

#, python-format
msgid "Error defining a domain with XML: %s"
msgstr "Error definiendo el dominio con XML: %s"

#, python-format
msgid "Error defining a secret with XML: %s"
msgstr "Error al definir un secreto con XML: %s"

#, python-format
msgid "Error deleting conntrack entries for %s"
msgstr "Error al eliminar las entradas conntrack para %s"

#, python-format
msgid "Error deploying instance %(instance)s on baremetal node %(node)s."
msgstr ""
"Error al desplegar la instancia %(instance)s en nodo de máquina vacía "
"%(node)s."

#, python-format
msgid "Error enabling hairpin mode with XML: %s"
msgstr "Error al habilitar modo horquilla con XML: %s"

#, python-format
msgid "Error from last host: %(last_host)s (node %(last_node)s): %(exc)s"
msgstr "Error del último host: %(last_host)s (nodo %(last_node)s): %(exc)s"

#, python-format
msgid "Error from libvirt during destroy. Code=%(errcode)s Error=%(e)s"
msgstr "Error de libvirt durante destrucción. Código=%(errcode)s Error=%(e)s"

#, python-format
msgid "Error from libvirt during undefine. Code=%(errcode)s Error=%(e)s"
msgstr ""
"Error de libvirt durante borrado de definición. Código=%(errcode)s Error="
"%(e)s"

#, python-format
msgid "Error from libvirt during unfilter. Code=%(errcode)s Error=%(e)s"
msgstr ""
"Error de libvirt durante eliminación de filtro. Código=%(errcode)s Error="
"%(e)s"

#, python-format
msgid "Error injecting data into image %(img_id)s (%(e)s)"
msgstr "Error al inyectar datos en imagen %(img_id)s (%(e)s)"

#, python-format
msgid "Error instantiating %(provider)s: %(exception)s"
msgstr "Error al instanciar %(provider)s: %(exception)s"

#, python-format
msgid "Error launching a defined domain with XML: %s"
msgstr "Error al lanzar el dominio definido con XML: %s"

msgid "Error locating next hop for message"
msgstr "Error al localizar el siguiente salto para el mensaje"

msgid "Error locating next hops for message"
msgstr "Error al localizar el siguiente salto para el mensaje"

msgid ""
"Error occurred during volume_snapshot_create, sending error status to Cinder."
msgstr ""
"Error ocurrido durante volume_snapshot_create, enviando estado de error a "
"Cinder."

msgid ""
"Error occurred during volume_snapshot_delete, sending error status to Cinder."
msgstr ""
"Ha ocurrido un error durante volume_snapshot_delete, envinado estado de "
"error a Cinder."

#, python-format
msgid "Error on '%(path)s' while checking direct I/O: '%(ex)s'"
msgstr "Error en '%(path)s' al comprobar E/S directa: '%(ex)s'"

#, python-format
msgid ""
"Error preparing deploy for instance %(instance)s on baremetal node %(node)s."
msgstr ""
"Error al preparar la implementacion para instancia %(instance)s en nodo "
"nativo %(node)s."

msgid "Error processing message locally"
msgstr "Error al procesar el mensaje localmente"

#, python-format
msgid "Error releasing DHCP for IP %(address)s with MAC %(mac_address)s"
msgstr "Error al liberar DHCP para la IP %(address)s con MAC %(mac_address)s"

#, python-format
msgid "Error scheduling instances %(instance_uuids)s"
msgstr "Error al planificar instancias %(instance_uuids)s"

msgid "Error sending message to next hops."
msgstr "Error al enviar el mensaje a los siguientes saltos"

#, python-format
msgid "Error starting xvp: %s"
msgstr "Error al iniciar xvp: %s "

msgid "Error trying to Rescue Instance"
msgstr "Error al intentar Rescatar Instancia"

msgid "Error trying to reschedule"
msgstr "Error al intentar volver a programar "

msgid "Error waiting for responses from neighbor cells"
msgstr "Error al esperar respuestas de celdas vecinas"

#, python-format
msgid "Error while trying to clean up image %s"
msgstr "Error al intentar limpiar imagen %s"

#, python-format
msgid "Error writing to %(path)s: %(exception)s"
msgstr "Error escribiendo en %(path)s: %(exception)s"

#, python-format
msgid "Error: %s"
msgstr "Error: %s"

#, python-format
msgid "Exception dispatching event %(event)s: %(ex)s"
msgstr "Excepción al asignar el suceso %(event)s: %(ex)s"

#, python-format
msgid "Exception handling resource: %s"
msgstr "Excepción manejando recurso: %s"

msgid "Exception in string format operation"
msgstr "Excepción en operación de formateo de cadena"

msgid "Exception loading extension"
msgstr "Excepción cargando extensión"

#, python-format
msgid "Exception running %(name)s %(type)s-hook: %(obj)s"
msgstr "Excepción ejecutando %(name)s %(type)s-enlace: %(obj)s"

msgid "Exception while creating table."
msgstr "Excepción al crear la tabla."

#, python-format
msgid "Exception while waiting completion of volume snapshots: %s"
msgstr "Excepción al esperar finalización de instantáneas de volumen: %s"

#, python-format
msgid "Extending virtual disk failed with error: %s"
msgstr "La extensión del disco virtual ha fallado con el error: %s"

#, python-format
msgid "Failed removing bridge device: '%s'"
msgstr "Error al eliminar dispositivo de puente: '%s'"

#, python-format
msgid "Failed removing net device: '%s'"
msgstr "Fallo al remover dispositivo de red: '%s'"

msgid "Failed storing info cache"
msgstr "Ha fallado el almacenamiento de memoria caché de información"

msgid ""
"Failed to allocate PCI devices for instance. Unassigning devices back to "
"pools. This should not happen, since the scheduler should have accurate "
"information, and allocation during claims is controlled via a hold on the "
"compute node semaphore"
msgstr ""
"Error al asignar dispositivos PCI para instancia. Desasignando dispositivos "
"de nuevo a pools. Esto no debe suceder, mientras el planificador tenga "
"información acertada y se controle la asignación durante reclamos mediante "
"la detención del semáforo de nodo de computación"

msgid "Failed to allocate network(s)"
msgstr "Fallo al asociar red(es)"

#, python-format
msgid "Failed to attach %(volume_id)s at %(mountpoint)s"
msgstr "Fallo al asociar %(volume_id)s en %(mountpoint)s"

#, python-format
msgid "Failed to attach volume at mountpoint: %s"
msgstr "Error al adjuntar volumen a punto de montaje: %s"

#, python-format
msgid "Failed to change vm state of %(instance_name)s to %(req_state)s"
msgstr "Error al cambiar el estado de vm de %(instance_name)s a %(req_state)s"

msgid "Failed to check if instance shared"
msgstr "Fallo al verificar si la instancia se encuentra compartida"

#, python-format
msgid "Failed to cleanup directory %(target)s: %(e)s"
msgstr "No se ha podido limpiar el directorio %(target)s: %(e)s"

msgid "Failed to cleanup snapshot."
msgstr "Fallo al limpiar instantánea."

#, python-format
msgid "Failed to commit reservations %s"
msgstr "Falla al asegurar grabado de reservaciones %s"

msgid "Failed to complete a deletion"
msgstr "Fallo durante la compleción una remoción"

#, python-format
msgid "Failed to connect to volume %(volume_id)s with volume at %(mountpoint)s"
msgstr ""
"Fallo al conectar hacia al volúmen %(volume_id)s con el volumen en "
"%(mountpoint)s"

#, python-format
msgid ""
"Failed to copy cached image %(source)s to %(dest)s for resize: %(error)s"
msgstr ""
"Error al copiar la imagen en memoria cahé %(source)s a %(dest)s para "
"redimensionamiento: %(error)s"

msgid "Failed to deallocate networks"
msgstr "Fallo al desasociar redes"

#, python-format
msgid "Failed to decrypt %(image_location)s to %(image_path)s"
msgstr "No se ha podido descifrar %(image_location)s en %(image_path)s"

#, python-format
msgid "Failed to destroy instance: %s"
msgstr "No se ha podido destruir instancia: %s"

#, python-format
msgid "Failed to detach %(device_name)s. Exception: %(exc)s"
msgstr "Error al separar %(device_name)s. Excepción: %(exc)s"

#, python-format
msgid "Failed to detach volume %(volume_id)s from %(mp)s"
msgstr "No se ha podido desconectar el volumen %(volume_id)s de %(mp)s"

#, python-format
msgid "Failed to download %(image_location)s to %(image_path)s"
msgstr "No se ha podido descargar %(image_location)s en %(image_path)s"

msgid "Failed to fetch glance image"
msgstr "No se ha podido captar la imagen glance"

#, python-format
msgid "Failed to find an SR for volume %s"
msgstr "Error al encontrar SR para volumen %s"

#, python-format
msgid "Failed to forget the SR for volume %s"
msgstr "Error al olvidad el SR para volumen %s"

#, python-format
msgid "Failed to generate usage audit for instance on host %s"
msgstr ""
"No se ha podido generar auditoría de uso para la instancia en el host %s "

#, python-format
msgid "Failed to get compute_info for %s"
msgstr "Fallo al obtener compute_info para %s"

msgid "Failed to get default networks"
msgstr "Fallo al obtener las redes predeterminadas"

#, python-format
msgid "Failed to get metadata for instance id: %s"
msgstr "Falla al obtener metadatos para la instancia id: %s"

msgid "Failed to get nw_info"
msgstr "Falla al obtener nw_info"

#, python-format
msgid "Failed to instantiate the download handler for %(scheme)s"
msgstr "Fallo al instanciar el manejador de descargas para %(scheme)s"

#, python-format
msgid "Failed to load %(cfgfile)s: %(ex)s"
msgstr "Falla cargando %(cfgfile)s: %(ex)s"

#, python-format
msgid "Failed to load %s"
msgstr "Ha fallado la carga de %s"

#, python-format
msgid "Failed to load %s-api"
msgstr "Error al cargar %s-api"

#, python-format
msgid ""
"Failed to mount container filesystem '%(image)s' on '%(target)s': %(errors)s"
msgstr ""
"Se ha encontrado un error en el montaje del sistema de archivos de "
"contenedor '%(image)s' en '%(target)s': : %(errors)s"

msgid "Failed to notify cells of BDM destroy."
msgstr "Fallo al notiifcar las celdas de destrucción de BDM"

msgid "Failed to notify cells of BDM update/create."
msgstr "Fallo al notificar las celdas de actualización/creación de BDM."

msgid "Failed to notify cells of bw_usage update"
msgstr "No se ha podido notificar a las celdas la actualización de bw_usage"

msgid "Failed to notify cells of instance fault"
msgstr "No se ha podido notificar a las celdas el error de instancia"

msgid "Failed to notify cells of instance info cache update"
msgstr ""
"No se ha podido notificar a las celdas la actualización de memoria caché de "
"información de instancia"

#, python-format
msgid "Failed to remove %(base_file)s, error was %(error)s"
msgstr "No se ha podido eliminar %(base_file)s, el error era %(error)s"

#, python-format
msgid "Failed to request Ironic to provision instance %(inst)s: %(reason)s"
msgstr ""
"Error al solicitar Ironic para aprovisionar instancia %(inst)s: %(reason)s"

#, python-format
msgid ""
"Failed to retrieve encryption metadata for volume %(volume_id)s: "
"%(exception)s"
msgstr ""
"Fallo al recuperar los metadatos de encripción para el volumen "
"%(volume_id)s: %(exception)s"

msgid "Failed to retrieve ephemeral encryption key"
msgstr "Error al recuperar clave de cifrado efímera"

msgid "Failed to revert crashed migration"
msgstr "Se ha encontrado un error en al revertir la migración colgada"

#, python-format
msgid "Failed to roll back reservations %s"
msgstr "Falla al revertir las reservaciones %s"

msgid "Failed to rollback quota for failed finish_resize"
msgstr "Error al restaurar capacidad para finish_resize fallido"

#, python-format
msgid "Failed to send message to cell: %(next_hop)s"
msgstr "Error al enviar mensaje a celda: %(next_hop)s"

msgid "Failed to send state update notification"
msgstr "Falla enviando notificación de actualización de estado"

msgid "Failed to send updated snapshot status to volume service."
msgstr ""
"Fallo al enviar estado de instantánea actualizada al servicio de volumen."

msgid "Failed to set instance name using multi_instance_display_name_template."
msgstr ""
"Se ha encontrado un error en la definición del nombre de instancia mediante "
"multi_instance_display_name_template."

#, python-format
msgid "Failed to start %(name)s on %(host)s:%(port)s with SSL support"
msgstr "Falla al iniciar %(name)s en %(host)s:%(port)s con soporte SSL"

msgid "Failed to start instance"
msgstr "Fallo al iniciar instancia"

msgid "Failed to stop instance"
msgstr "Fallo al detener instancia"

#, python-format
msgid "Failed to swap volume %(old_volume_id)s for %(new_volume_id)s"
msgstr ""
"Fallo para intercambiar volúmen %(old_volume_id)s por %(new_volume_id)s"

msgid "Failed to teardown container filesystem"
msgstr "Error al desarmar el sistema de archivo de contenedor "

msgid "Failed to umount container filesystem"
msgstr "Error al desmontar el sistema de archivos de contenedor"

msgid "Failed to unpause instance"
msgstr "Fallo al reanudar la instancia"

#, python-format
msgid "Failed to untar %(image_location)s to %(image_path)s"
msgstr "No se ha podido ejecutar untar %(image_location)s en %(image_path)s"

msgid "Failed to update usages bulk deallocating floating IP"
msgstr "Fallo al actualizar uso de desasignación masiva de IP fotante"

msgid "Failed to update usages deallocating fixed IP"
msgstr ""
"Se ha encontrado un error en la actualización de los usos desasignando IP "
"flotante"

msgid "Failed to update usages deallocating floating IP"
msgstr "No se han podido actualizar los usos desasignando IP flotante "

msgid "Failed to update usages deallocating network."
msgstr "No se han podido actualizar los usos desasignando la red."

msgid "Failed to update usages deallocating security group"
msgstr ""
"No se han podido actualizar los usos desasignando el grupo de seguridad "

msgid "Failed to update usages deallocating server group"
msgstr "Error al actualizar los usos desasignando el grupo de servidor"

#, python-format
msgid "Failed to upload %(image_location)s to %(image_path)s"
msgstr "No se ha podido subir %(image_location)s a %(image_path)s "

msgid "Failed to write configuration file"
msgstr "No se ha podido grabar archivo de configuración"

msgid "Failed to write inbound.csr"
msgstr "Falla al grabar inbound.csr"

msgid "Failed while plugging vif"
msgstr "Fallo al conectar vif"

msgid "Failed while unplugging vif"
msgstr "No se ha podido desconectar vif"

msgid "Failure prepping block device"
msgstr "Fallo al preparar el dispositivo de bloques"

msgid "Failure while cleaning up attached VDIs"
msgstr "Error al limpiar VDI conectados "

#, python-format
msgid "Fatal Exception running %(name)s %(type)s-hook: %(obj)s"
msgstr "Excepción fatal ejecutando %(name)s %(type)s-enlace: %(obj)s"

msgid "Guest does not have a console available"
msgstr "El invitado no tiene una consola disponible"

msgid "Host is member of a pool, but DB says otherwise"
msgstr ""
"El host es miembro de una agrupación, pero la base de datos indica lo "
"contrario"

#, python-format
msgid ""
"Hostname has changed from %(old)s to %(new)s. A restart is required to take "
"effect."
msgstr ""
"El nombre del anfitrión ha cambiado de %(old)s a %(new)s. Se requiere un "
"reinicio para hacer efecto."

#, python-format
msgid "Image size %(size)d exceeded flavor allowed size %(allowed_size)d"
msgstr ""
"El tamaño de la imagen %(size)d excede el tamaño permitido por el sabor "
"%(allowed_size)d"

#, python-format
msgid ""
"Instance compute service state on %s expected to be down, but it was up."
msgstr ""
"El estado de la instancia del servicio de cómputo en %s debería ser "
"inactivo, pero se encontraba activo."

msgid "Instance failed block device setup"
msgstr "Ha fallado la configuración de dispositivo de bloque en la instancia"

#, python-format
msgid "Instance failed network setup after %(attempts)d attempt(s)"
msgstr ""
"La configuración de red de la instancia falló después de %(attempts)d "
"intento(s)"

msgid "Instance failed to spawn"
msgstr "La instancia no se ha podido generar"

#, python-format
msgid "Interface %s not found"
msgstr "Interfaz %s no encontrada"

#, python-format
msgid "Invalid server_string: %s"
msgstr "Serie del servidor no válido: %s"

#, python-format
msgid "Live Migration failure: %s"
msgstr "Fallo en migración en vivo: %s"

msgid "Live migration failed."
msgstr "Falló la migración en vivo."

msgid "Migrate Receive failed"
msgstr "Ha fallado la recepción de migración"

msgid "Migrate Send failed"
msgstr "Ha fallado el envío de migración"

#, python-format
msgid "Migration %s is not found during confirmation"
msgstr "La migración %s no ha sido encontrada durante la confirmación"

#, python-format
msgid ""
"Migration of instance %(instance_id)s to host %(dest)s unexpectedly failed."
msgstr ""
"La migración de la instancia %(instance_id)s al anfitrión %(dest)s ha "
"fallado inesperadamente."

msgid "Migration operation has aborted"
msgstr "La operación de migración ha sido abortada"

#, python-format
msgid "NBD error - previous umount did not cleanup /var/lock/qemu-nbd-%s."
msgstr "Error NBD - desmontaje previo no ha limpiado /var/qemu-nbd-%s."

#, python-format
msgid ""
"NOT IMPLEMENTED: The call to %(method)s is not supported by the agent. args="
"%(args)r"
msgstr ""
"SIN IMPLEMENTAR: el agente no soporta la llamada a %(method)s. args=%(args)r"

msgid "Network driver option required, but not specified"
msgstr ""
"La opción de controlador de red es necesaria, pero no se ha especificado"

#, python-format
msgid "Neutron Error adding rules to security group %s"
msgstr "Error de Neutron al agregar reglas al grupo de seguridad %s"

#, python-format
msgid "Neutron Error creating security group %s"
msgstr "Error de Neutron al crear el grupo de seguridad %s"

#, python-format
msgid "Neutron Error getting security group %s"
msgstr "Error de Neutron al obtener los grupos de seguridad %s"

msgid "Neutron Error getting security groups"
msgstr "Error de Neutron al obtener los grupos de seguridad"

#, python-format
msgid "Neutron Error unable to delete %s"
msgstr "Error de Neutron incapaz de eliminar %s"

#, python-format
msgid "Neutron Error updating security group %s"
msgstr "Error de Neutron al actualizar el grupo de seguridad %s"

msgid "Neutron Error:"
msgstr "Error de Neutron:"

#, python-format
msgid "Neutron Error: %s"
msgstr "Error de Neutron: %s"

#, python-format
msgid "Neutron Reported failure on event %(event)s for instance %(uuid)s"
msgstr ""
"Neutron ha reportado una falla en el evento %(event)s para la instancia "
"%(uuid)s"

#, python-format
msgid "Neutron error creating port on network %s"
msgstr "Error de Neutron al crear puerto en la red: %s"

#, python-format
msgid "No compute node record for host %s"
msgstr "No hay registro de nodo de cómputo para host %s"

#, python-format
msgid "No save handler for %s"
msgstr "No hay manejador de guardado para %s"

msgid "Not all properties needed are implemented in the compute driver"
msgstr ""
"No todas las propiedades necesarias están implementadas en el controlador de "
"cómputo"

msgid ""
"Periodic sync_power_state task had an error while processing an instance."
msgstr ""
"La tarea periódica sync_power_state ha tenido un error al procesar una "
"instancia."

msgid "Periodic task failed to offload instance."
msgstr "Tarea periódica falló al descargar instancia."

msgid "Plugin config_file get_val failed"
msgstr "Ha fallado desconexión config_file get_val "

#, python-format
msgid "Pool-Join failed: %s"
msgstr "Fallo en la integración al conjunto: %s"

#, python-format
msgid "Pool-eject failed: %s"
msgstr "Expulsión de conjunto fallida: %s"

#, python-format
msgid "Pool-set_name_label failed: %s"
msgstr "Fallo al establecer set_name_label en conjunto: %s"

#, python-format
msgid "Pre live migration failed at %s"
msgstr "Previo a migración en vivo falló en %s"

msgid "Read/Write data failed"
msgstr "Fallo en la Lectura/Escritura de datos"

#, python-format
msgid "Requested VM Generation %s, but provided VHD instead of VHDX."
msgstr ""
"Generación de VM  solicitada %s, pero se ha proporcionado VHD en lugar de "
"VHDX."

#, python-format
msgid "Returning exception %s to caller"
msgstr "Devolviendo excepción %s al interlocutor"

msgid "Service error occurred during cleanup_host"
msgstr "Error del servicio durante cleanup_host"

msgid "Setting instance vm_state to ERROR"
msgstr "Estableciendo el vm_state de la instancia a ERROR"

msgid "Shutting down VM (cleanly) failed."
msgstr "Ha fallado el cierre de VM (de forma limpia)."

msgid "Shutting down VM (hard) failed"
msgstr "Ha fallado el cierre de VM (de forma permanente)"

msgid ""
"Something wrong happened when trying to delete snapshot from shelved "
"instance."
msgstr ""
"Algo malo ha pasado al intentar eliminar la instantánea de la imagen "
"almacenada."

#, python-format
msgid "TIMEOUT: The call to %(method)s timed out. args=%(args)r"
msgstr ""
"TIEMPO DE ESPERA EXCEDIDO: La llamada a %(method)s ha excedido el tiempo de "
"espera. args=%(args)r"

#, python-format
msgid "Temporary directory is invalid: %s"
msgstr "El directorio temporal no es válido: %s"

#, python-format
msgid "The Quobyte volume at %s is still in use."
msgstr "El volumen Quobyte en %s todavía esta en uso."

#, python-format
msgid ""
"The agent call to %(method)s returned an invalid response: %(ret)r. args="
"%(args)r"
msgstr ""
"La llamada del agente para %(method)s ha arrojado una respuesta inválida: "
"%(ret)r. args=%(args)r"

#, python-format
msgid "The call to %(method)s returned an error: %(e)s."
msgstr "La llamada a %(method)s ha devuelto un error: %(e)s."

#, python-format
msgid "The call to %(method)s returned an error: %(e)s. args=%(args)r"
msgstr "La llamada a %(method)s ha devuelto un error: %(e)s. args=%(args)r"

msgid "Transfer data failed"
msgstr "Ha fallado la transferencia de datos"

#, python-format
msgid "Unable to access floating IP %s"
msgstr "Incapaz de acceder a la Ip flotante %s"

msgid "Unable to access the rescue disk"
msgstr "No es posible acceder al disco de recuperación"

#, python-format
msgid "Unable to attach volume to instance %s"
msgstr "Imposible adjuntar volumen a la instancia %s"

#, python-format
msgid "Unable to clear device ID for port '%s'"
msgstr "No es posible limpiar el ID del dispositivo para puerto '%s'"

msgid "Unable to create VM snapshot, failing volume_snapshot operation."
msgstr ""
"Incapaz de crear instantánea de VM, operación de volume_snapshot fallida."

msgid ""
"Unable to create quiesced VM snapshot, attempting again with quiescing "
"disabled."
msgstr ""
"Incapaz de crear instantánea de VM inmovilizada, intentando nuevamente con "
"la inmovilidad deshabilitada"

msgid "Unable to destroy VBD"
msgstr "No ha sido posible destruir VBD"

#, python-format
msgid "Unable to execute %(cmd)s. Exception: %(exception)s"
msgstr "No se puede ejecutar %(cmd)s. Excepción: %(exception)s"

msgid "Unable to find SR from VBD"
msgstr "No es posible encontrar SR a partir de VBD"

msgid "Unable to find SR from VDI"
msgstr "No es posible encontrar SR a partir de VDI"

msgid "Unable to get record of VDI"
msgstr "No es posible obtener registro de VDI"

msgid "Unable to get updated status"
msgstr "No se puede obtener el estado actualizado"

msgid "Unable to introduce VDI for SR"
msgstr "Inposible insertar VDI para SR"

msgid "Unable to introduce VDI on SR"
msgstr "No es posible insertar VDI o SR"

msgid "Unable to load the virtualization driver"
msgstr "Incapaz de cargar el controlador de virtualización"

#, python-format
msgid "Unable to migrate VM %(vm_ref)s from %(host)s"
msgstr "Incapaz de migrar VM %(vm_ref)s desde %(host)s"

#, python-format
msgid ""
"Unable to obtain RRD XML for VM %(vm_uuid)s with server details: %(server)s."
msgstr ""
"No se ha podido obtener XML RRD para la máquina virtual %(vm_uuid)s con los "
"detalles de servidor: %(server)s."

#, python-format
msgid "Unable to parse rrd of %s"
msgstr "Incapaz de analizar rrd de %s"

#, python-format
msgid "Unable to retrieve storage policy with name %s"
msgstr ""
"No ha sido posible recuperar la política de almacenamiento de nombre %s"

#, python-format
msgid "Unable to set up pool: %s."
msgstr "Incapaz de establecer conjunto: %s"

msgid "Unable to unplug VBD"
msgstr "No ha sido posible desconectar VBD"

#, python-format
msgid "Unable to update instance VNIC index for port %s."
msgstr "No pudo actualizar el índice VNIC de la instancia para el puerto %s."

msgid "Unexpected build failure, not rescheduling build."
msgstr "Fallo de compilación inesperado, no se reprogramará la compilación."

#, python-format
msgid "Unexpected error while checking process %(pid)s."
msgstr "Un error inesperado al revisar el proceso %(pid)s."

msgid "Unexpected exception in API method"
msgstr "Excepción inesperada en método API."

#, python-format
msgid "Unknown cell '%(cell_name)s' when trying to update capabilities"
msgstr "Celda '%(cell_name)s' desconocida al intentar actualizar prestaciones"

#, python-format
msgid "Unknown cell '%(cell_name)s' when trying to update capacities"
msgstr "Celda '%(cell_name)s' desconocida al intentar actualizar capacidades"

#, python-format
msgid "Unknown content in connection_info/access_mode: %s"
msgstr "Contenido desconocido en connection_info/access_mode: %s"

msgid "Unshelve attempted but an error has occurred"
msgstr "Se ha intentado la extracción pero ha ocurrido un error"

msgid "Unshelve attempted but vm_state not SHELVED or SHELVED_OFFLOADED"
msgstr ""
"Se ha intentado desarchivar pero vm_state no se encuentra como SHELVED o "
"SHELVED_OFFLOADED"

msgid "Vifs plug failed"
msgstr "Error de conexión Vifs"

#, python-format
msgid "Volume %s is associated with the instance but no SR was found for it"
msgstr ""
"El volumen %s está asociado con la instancia pero no se ha encontrado SR "
"alguna para éste"

#, python-format
msgid "Volume is not writable. Please broaden the file permissions. Mount: %s"
msgstr ""
"No se puede escribir el volumen. Por favor amplíe los permisos del fichero. "
"Montaje: %s"

#, python-format
msgid ""
"When loading the module %(module_str)s the following error occurred: %(ex)s"
msgstr ""
"Al cargar el módulo %(module_str)s se ha presentado el siguiente error: "
"%(ex)s"

msgid ""
"XenAPI is unable to find a Storage Repository to install guest instances on. "
"Please check your configuration (e.g. set a default SR for the pool) and/or "
"configure the flag 'sr_matching_filter'."
msgstr ""
"XenAPI es incapaz de encontrar un Storage Repository en dónde instalar las "
"instancias invitadas. Por favor verifica tu configuración (p.ej. establece "
"un SR predeterminado en el conjunto) y/o ocnfigura el identificador "
"'sr_matching_filter'."

msgid "_migrate_disk_resizing_down failed. Restoring orig vm"
msgstr "Falló _migrate_disk_resizing_down. Restaurando vm original"

#, python-format
msgid "_migrate_disk_resizing_up failed. Restoring orig vm due_to: %s."
msgstr "_migrate_disk_resizing_up fallido. Restaurando vm original due_to: %s."

#, python-format
msgid "allocate_port_for_instance returned %(ports)s ports"
msgstr "allocate_port_for_instance ha regresado %(ports)s puertos"

msgid "attaching network adapter failed."
msgstr "se ha encontrado un error en la conexión del adaptador de red."

msgid "detaching network adapter failed."
msgstr "se ha encontrado un error en la desconexión del adaptador de red."

msgid "error during stop() in sync_power_state."
msgstr "error durante stop() en sync_power_state."

#, python-format
msgid "error opening rbd image %s"
msgstr "Error al abrir imagen rbd %s"

#, python-format
msgid "kill -HUP dnsmasq threw %s"
msgstr "kill -HUP dnsmasq lanzó %s"

#, python-format
msgid "killing radvd threw %s"
msgstr "Matando radvd lanzado %s"

msgid "nbd module not loaded"
msgstr "El módulo nbd no se ha cargado"

msgid "set_admin_password failed"
msgstr "Error de set_admin_password"

#, python-format
msgid ""
"status is UNKNOWN from vm_state=%(vm_state)s task_state=%(task_state)s. Bad "
"upgrade or db corrupted?"
msgstr ""
"Estado  DESCONOCIDO de vm_state=%(vm_state)s task_state=%(task_state)s. "
"¿Actualización errónea o base de datos dañada?"
