# Translations template for nova.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the nova project.
#
# Translators:
# Andreas Jaeger <jaegerandi@gmail.com>, 2016. #zanata
msgid ""
msgstr ""
"Project-Id-Version: nova 14.0.0.0b3.dev750\n"
"Report-Msgid-Bugs-To: https://bugs.launchpad.net/openstack-i18n/\n"
"POT-Creation-Date: 2016-08-25 06:15+0000\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"PO-Revision-Date: 2016-03-19 08:31+0000\n"
"Last-Translator: Carlos Marques <marquesc@br.ibm.com>\n"
"Language: pt-BR\n"
"Plural-Forms: nplurals=2; plural=(n > 1);\n"
"Generated-By: Babel 2.0\n"
"X-Generator: Zanata 3.7.3\n"
"Language-Team: Portuguese (Brazil)\n"

msgid "\"Look for the VDIs failed"
msgstr "Procure pelos VDIs com falha"

#, python-format
msgid ""
"%(base)s virtual size %(base_size)s larger than flavor root disk size "
"%(size)s"
msgstr ""
"O tamanho virtual %(base_size)s  do %(base)s é maior que o tamanho do disco "
"raiz de tipo %(size)s"

#, python-format
msgid ""
"%(scheme)s is registered as a module twice. %(module_name)s is not being "
"used."
msgstr ""
"O %(scheme)s está registrado como um módulo duas vezes. O %(module_name)s "
"não está sendo utilizado."

#, python-format
msgid ""
"Aggregate %(aggregate_id)s: unrecoverable state during operation on %(host)s"
msgstr ""
"Agregado %(aggregate_id)s: estado irrecuperável durante a operação em "
"%(host)s"

msgid "An error occurred while deallocating network."
msgstr "Ocorreu um erro ao desalocar a rede."

msgid "An error occurred while refreshing the network cache."
msgstr "Ocorreu um erro ao atualizar o cache de rede."

#, python-format
msgid "Attach volume failed to %(instance_name)s: %(exn)s"
msgstr "Falha ao anexar volume ao %(instance_name)s: %(exn)s"

#, python-format
msgid "Attaching PCI devices %(dev)s to %(dom)s failed."
msgstr "Falha ao anexar dispositivos PCI %(dev)s no %(dom)s."

#, python-format
msgid "Attaching network adapter failed. Exception: %s"
msgstr "A anexação do adaptador de rede falhou. Exceção: %s"

msgid "Cannot cleanup migration files"
msgstr "Não é possível limpar arquivos de migração"

#, python-format
msgid ""
"Cannot log in target %(target_iqn)s. Unsupported iSCSI authentication "
"method: %(auth_method)s."
msgstr ""
"Não é possível efetuar login no destino %(target_iqn)s. Método de "
"autenticação iSCSI não suportado: %(auth_method)s."

#, python-format
msgid "Cannot reboot instance: %s"
msgstr "Não é possível reinicializar a instância: %s"

#, python-format
msgid "Caught error: %s"
msgstr "Capturado o erro: %s"

msgid "Compute driver option required, but not specified"
msgstr "Opção de driver de cálculo necessária, mas não especificada"

#, python-format
msgid ""
"Connection between volume %(vol)s and host %(host)s might have succeeded, "
"but attempt to terminate connection has failed. Validate the connection and "
"determine if manual cleanup is needed. Error: %(msg)s Code: %(code)s."
msgstr ""
"A conexão entre o  volume %(vol)s e o host %(host)s pode ter sido bem-"
"sucedida, mas uma tentativa de finalizar a conexão falhou. Valide a conexão "
"e determine se uma limpeza manual é necessária. Erro: %(msg)s, Código: "
"%(code)s."

#, python-format
msgid "Connection to libvirt failed: %s"
msgstr "Falha na conexão a libvirt: %s"

#, python-format
msgid "Could not bind to %(host)s:%(port)s"
msgstr "Não foi possível localizar %(host)s:%(port)s"

msgid "Could not decode scheduler options"
msgstr "Não foi possível decodificar opções do planejador"

#, python-format
msgid ""
"Could not disconnect encrypted volume %(volume)s. If dm-crypt device is "
"still active it will have to be destroyed manually for cleanup to succeed."
msgstr ""
"Não foi possível desconectar o volume criptografado %(volume)s. Se o "
"dispositivo dm-crypt ainda estiver ativo, ele deverá ser destruído "
"manualmente para que a limpeza seja bem-sucedida. "

#, python-format
msgid "Could not remove tmpdir: %s"
msgstr "Não foi possível remover tmpdir: %s"

#, python-format
msgid "Could not start encryption for disk %(device)s: %(exception)s"
msgstr ""
"Não foi possível iniciar a criptografia para o disco %(device)s: "
"%(exception)s"

#, python-format
msgid "Could not stat scheduler options file %(filename)s"
msgstr ""
"Não foi possível iniciar o arquivo de opções do planejador %(filename)s"

msgid "Couldn't communicate with any cells"
msgstr "Não é possível comunicar-se com nenhuma célula"

#, python-format
msgid "Couldn't communicate with cell '%s'"
msgstr "Não é possível comunicar-se com a célula '%s'."

#, python-format
msgid "Couldn't lookup app: %s"
msgstr "Não é possível consultar o aplicativo:  %s"

#, python-format
msgid "Couldn't unmount the GlusterFS share %s"
msgstr "Não foi possível desmontar o compartilhamento GlusterFS %s"

#, python-format
msgid "Couldn't unmount the NFS share %s"
msgstr "Não foi possível desmontar o compartilhamento NFS %s"

#, python-format
msgid "Couldn't unmount the Quobyte Volume at %s"
msgstr "Não foi possível desmontar o Volume Quobyte no %s"

#, python-format
msgid "Couldn't unmount the share %s"
msgstr "Não foi possível desmontar o compartilhamento %s"

#, python-format
msgid "Creating config drive failed with error: %s"
msgstr "Criando unidade de configuração com falha com erro: %s"

msgid "DB error"
msgstr "Erro de DB"

msgid ""
"Data migrations for PciDevice are not safe, likely because not all services "
"that access the DB directly are updated to the latest version"
msgstr ""
"As migrações de dados para PciDevice não são seguras, provavelmente porque "
"nem todos os serviços que acessam o BD diretamente estão atualizados para a "
"versão mais recente"

msgid "Destroy VM failed"
msgstr "A destruição de MV falhou"

msgid "Destroy instance failed"
msgstr "A destruição da instância falhou"

#, python-format
msgid "Detaching network adapter failed. Exception: %s"
msgstr "A separação do adaptador de rede falhou. Exceção: %s"

#, python-format
msgid ""
"Download handler '%(handler)s' raised an exception, falling back to default "
"handler '%(default_handler)s'"
msgstr ""
"O manipulador de download '%(handler)s' emitiu uma exceção, executando "
"failback para o manipulador padrão '%(default_handler)s'"

msgid "Download image error"
msgstr "Erro de download de imagem"

#, python-format
msgid "Driver failed to attach volume %(volume_id)s at %(mountpoint)s"
msgstr "O driver falhou ao conectar o volume %(volume_id)s no %(mountpoint)s"

msgid "Environment variable 'NETWORK_ID' must be set."
msgstr "A variável de ambiente 'NETWORK_ID' deve ser definida."

#, python-format
msgid ""
"Error contacting glance server '%(server)s' for '%(method)s', %(extra)s."
msgstr ""
"Erro ao entrar em contato com o servidor glance  '%(server)s' para "
"'%(method)s', %(extra)s."

#, python-format
msgid "Error defining a domain with XML: %s"
msgstr "Erro ao definir um domínio com XML: %s"

#, python-format
msgid "Error defining a secret with XML: %s"
msgstr "Erro ao definir um segredo com XML: %s"

#, python-format
msgid "Error deleting conntrack entries for %s"
msgstr "Erro ao excluir entradas conntrack para %s"

#, python-format
msgid "Error deploying instance %(instance)s on baremetal node %(node)s."
msgstr "Erro ao implementar a instância %(instance)s no nó básico %(node)s."

#, python-format
msgid "Error enabling hairpin mode with XML: %s"
msgstr "Erro ao ativar o modo hairpin com XML: %s"

#, python-format
msgid "Error from last host: %(last_host)s (node %(last_node)s): %(exc)s"
msgstr "Erro do último host: %(last_host)s (nó %(last_node)s): %(exc)s"

#, python-format
msgid "Error from libvirt during destroy. Code=%(errcode)s Error=%(e)s"
msgstr "Erro de libvirt durante destruição. Código=%(errcode)s Erro=%(e)s"

#, python-format
msgid "Error from libvirt during undefine. Code=%(errcode)s Error=%(e)s"
msgstr "Erro de libvirt durante indefinição. Código=%(errcode)s Erro=%(e)s"

#, python-format
msgid "Error from libvirt during unfilter. Code=%(errcode)s Error=%(e)s"
msgstr ""
"Erro de libvirt durante cancelamento de filtro. Código=%(errcode)s Erro=%(e)s"

#, python-format
msgid ""
"Error from libvirt while injecting an NMI to %(instance_uuid)s: [Error Code "
"%(error_code)s] %(ex)s"
msgstr ""
"Erro de ibvirt ao injetar um NMI para %(instance_uuid)s: [Error Code "
"%(error_code)s] %(ex)s"

#, python-format
msgid "Error injecting data into image %(img_id)s (%(e)s)"
msgstr "Erro ao injetar dados na imagem %(img_id)s (%(e)s)"

#, python-format
msgid "Error instantiating %(provider)s: %(exception)s"
msgstr "Erro ao instanciar %(provider)s: %(exception)s"

#, python-format
msgid "Error launching a defined domain with XML: %s"
msgstr "Erro ao ativar um domínio definido com XML: %s"

msgid "Error locating next hop for message"
msgstr "Erro ao localizar próximo hop para mensagem"

msgid "Error locating next hops for message"
msgstr "Erro ao localizar próximos hops para mensagem"

msgid ""
"Error occurred during volume_snapshot_create, sending error status to Cinder."
msgstr ""
"Ocorreu um erro durante volume_snapshot_create, enviando status de erro para "
"o  Cinder."

msgid ""
"Error occurred during volume_snapshot_delete, sending error status to Cinder."
msgstr ""
"Ocorreu um erro durante volume_snapshot_delete, enviando status de erro para "
"o  Cinder."

#, python-format
msgid "Error on '%(path)s' while checking direct I/O: '%(ex)s'"
msgstr "Erro em '%(path)s' ao verificar E/S direta: '%(ex)s'"

#, python-format
msgid ""
"Error preparing deploy for instance %(instance)s on baremetal node %(node)s."
msgstr ""
"Erro ao preparar implementação para a instância %(instance)s no nó básico "
"%(node)s."

msgid "Error processing message locally"
msgstr "Erro ao processar a mensagem localmente"

#, python-format
msgid "Error releasing DHCP for IP %(address)s with MAC %(mac_address)s"
msgstr "Erro ao liberar DHCP para o IP %(address)s com MAC %(mac_address)s"

#, python-format
msgid "Error scheduling instances %(instance_uuids)s"
msgstr "Erro ao planejar instâncias %(instance_uuids)s"

msgid "Error sending message to next hops."
msgstr "Erro ao enviar mensagem para os próximos hops."

#, python-format
msgid "Error starting xvp: %s"
msgstr "Erro ao iniciar xvp: %s"

msgid "Error trying to Rescue Instance"
msgstr "Erro ao tentar Resgatar Instância"

msgid "Error trying to reschedule"
msgstr "Erro ao tentar reagendar"

#, python-format
msgid "Error updating resources for node %(node)s."
msgstr "Erro ao atualizar recursos para o nó  %(node)s."

msgid "Error waiting for responses from neighbor cells"
msgstr "Erro ao gravar respostas para células vizinhas"

#, python-format
msgid "Error while trying to clean up image %s"
msgstr "Erro ao tentar limpar a imagem %s"

#, python-format
msgid "Error writing to %(path)s: %(exception)s"
msgstr "Erro ao gravar em %(path)s: %(exception)s"

#, python-format
msgid "Error: %s"
msgstr "Erro: %s"

#, python-format
msgid "Exception dispatching event %(event)s: %(ex)s"
msgstr "Exceção ao despachar o evento %(event)s: %(ex)s"

#, python-format
msgid "Exception handling resource: %s"
msgstr "Exceção ao manipular recurso: %s"

msgid "Exception in string format operation"
msgstr "Exceção na operação de formato de sequência"

msgid "Exception loading extension"
msgstr "Exceção ao carregar a extensão"

#, python-format
msgid "Exception running %(name)s %(type)s-hook: %(obj)s"
msgstr "Exceção ao executar %(name)s %(type)s-hook: %(obj)s"

msgid "Exception while creating table."
msgstr "Exceção ao criar tabela."

#, python-format
msgid "Exception while waiting completion of volume snapshots: %s"
msgstr "Exceção ao aguardar a conclusão de capturas instantâneas do volume: %s"

#, python-format
msgid "Extending virtual disk failed with error: %s"
msgstr "A extensão do disco virtual falhou com o erro: %s"

#, python-format
msgid "Failed removing bridge device: '%s'"
msgstr "Falha ao remover o dispositivo de ponte: '%s'"

#, python-format
msgid "Failed removing net device: '%s'"
msgstr "Falha ao remover o dispositivo de rede: '%s'"

msgid "Failed storing info cache"
msgstr "Falha ao armazenar no cache de informações"

msgid ""
"Failed to allocate PCI devices for instance. Unassigning devices back to "
"pools. This should not happen, since the scheduler should have accurate "
"information, and allocation during claims is controlled via a hold on the "
"compute node semaphore"
msgstr ""
"Falha ao alocar dispositivos PCI para a instância. Removendo designação de "
"dispositivos de volta para conjuntos. Isso não deve ocorrer, já que o "
"planejador deve possuir informações precisas, e a alocação durante as "
"solicitações é controlada por meio de uma suspensão no semáforo de nó de "
"cálculo."

msgid "Failed to allocate network(s)"
msgstr "Falha ao alocar rede(s)"

#, python-format
msgid "Failed to attach %(volume_id)s at %(mountpoint)s"
msgstr "Falha ao anexar %(volume_id)s em %(mountpoint)s"

#, python-format
msgid "Failed to attach volume at mountpoint: %s"
msgstr "Falha ao anexar volume no ponto de montagem: %s"

#, python-format
msgid "Failed to build configdrive: %s"
msgstr "Falha ao construir configdrive: %s"

#, python-format
msgid "Failed to cancel migration %s"
msgstr "Falha ao cancelar a migração %s"

#, python-format
msgid "Failed to change vm state of %(instance_name)s to %(req_state)s"
msgstr ""
"Falha ao alterar o estado da MV de %(instance_name)s para %(req_state)s"

msgid "Failed to check if instance shared"
msgstr "Falha ao verificar se a instância está compartilhada"

#, python-format
msgid "Failed to cleanup directory %(target)s: %(e)s"
msgstr "Falha ao limpar diretório %(target)s: %(e)s"

msgid "Failed to cleanup snapshot."
msgstr "Falha ao limpar uma captura instantânea."

#, python-format
msgid "Failed to commit reservations %s"
msgstr "Falha ao fazer commit das reservas %s"

msgid "Failed to complete a deletion"
msgstr "Falha ao concluir uma exclusão"

#, python-format
msgid "Failed to connect to volume %(volume_id)s with volume at %(mountpoint)s"
msgstr ""
"Falha ao conectar-se com o volume %(volume_id)s com o volume em "
"%(mountpoint)s"

#, python-format
msgid ""
"Failed to copy cached image %(source)s to %(dest)s for resize: %(error)s"
msgstr ""
"Falha ao copiar a imagem em cache %(source)s para %(dest)s para o "
"redimensionamento: %(error)s"

msgid "Failed to deallocate networks"
msgstr "Falha ao desalocar redes"

#, python-format
msgid "Failed to decrypt %(image_location)s to %(image_path)s"
msgstr "Falha ao decriptografar %(image_location)s para %(image_path)s"

#, python-format
msgid "Failed to destroy instance: %s"
msgstr "Falha ao destruir instância: %s"

#, python-format
msgid "Failed to detach %(device_name)s. Exception: %(exc)s"
msgstr "Falha ao separar %(device_name)s. Exceção: %(exc)s"

#, python-format
msgid "Failed to detach volume %(volume_id)s from %(mp)s"
msgstr "Falha ao remover volume %(volume_id)s de %(mp)s"

#, python-format
msgid "Failed to download %(image_location)s to %(image_path)s"
msgstr "Falha ao fazer o download de %(image_location)s para %(image_path)s"

#, python-format
msgid ""
"Failed to extract compute RPC version from service history because I am too "
"old (minimum version is now %(version)i)"
msgstr ""
"Falha ao extrair a versão do RPC de cálculo a partir do histórico de serviço "
"porque ela é muito antiga (a versão mínima agora é %(version)i)"

#, python-format
msgid ""
"Failed to extract compute RPC version from service history for version "
"%(version)i"
msgstr ""
"Falha ao extrair a versão do RPC de cálculo a partir do histórico de serviço "
"para a versão %(version)i"

msgid "Failed to fetch glance image"
msgstr "Falha ao buscar imagem de visão rápida"

#, python-format
msgid "Failed to find an SR for volume %s"
msgstr "Falha ao localizar um SR para o volume %s"

#, python-format
msgid "Failed to forget the SR for volume %s"
msgstr "Falha ao esquecer o SR para o volume %s"

#, python-format
msgid "Failed to generate usage audit for instance on host %s"
msgstr "Falha ao gerar auditoria de uso para a instância no host %s"

#, python-format
msgid "Failed to get compute_info for %s"
msgstr "Falha ao obter compute_info para %s"

msgid "Failed to get default networks"
msgstr "Falha ao obter redes padrão"

#, python-format
msgid ""
"Failed to get instance id for metadata request, provider %(provider)s "
"networks %(networks)s requester %(requester)s. Error: %(error)s"
msgstr ""
"Falha ao obter o ID da instância para a solicitação de metadados, provedor "
"%(provider)s, redes %(networks)s, solicitador %(requester)s. Erro: %(error)s"

#, python-format
msgid "Failed to get metadata for instance id: %s"
msgstr "Falha ao obter metadados para o ID da instância: %s"

msgid "Failed to get nw_info"
msgstr "Falha ao obter nw_info"

#, python-format
msgid "Failed to instantiate the download handler for %(scheme)s"
msgstr "Falha ao instanciar o manipulador de download para %(scheme)s"

#, python-format
msgid ""
"Failed to kill process %(pid)s due to %(reason)s, while deleting the "
"instance."
msgstr ""
"Falha ao encerrar o processo %(pid)s devido a %(reason)s, ao excluir a "
"instância."

#, python-format
msgid "Failed to load %(cfgfile)s: %(ex)s"
msgstr "Falha ao carregar %(cfgfile)s: %(ex)s"

#, python-format
msgid "Failed to load %s"
msgstr "Falha ao carregar %s"

#, python-format
msgid "Failed to load %s-api"
msgstr "Falha ao carregar a API %s"

#, python-format
msgid ""
"Failed to mount container filesystem '%(image)s' on '%(target)s': %(errors)s"
msgstr ""
"Falha ao montar o sistema de arquivos do contêiner '%(image)s' em "
"'%(target)s': %(errors)s"

msgid "Failed to notify cells of BDM destroy."
msgstr "Falha ao notificar células de destruição de BDM"

msgid "Failed to notify cells of BDM update/create."
msgstr "Falha ao notificar células de atualização/criação de BDM."

msgid "Failed to notify cells of bw_usage update"
msgstr "Falha ao notificar células de atualização de bw_usage"

msgid "Failed to notify cells of instance fault"
msgstr "Falha ao notificar células de falha da instância"

msgid "Failed to notify cells of instance info cache update"
msgstr ""
"Falha ao notificar células de atualização do cache de informações da "
"instância"

#, python-format
msgid "Failed to remove %(base_file)s, error was %(error)s"
msgstr "Falha ao remover %(base_file)s; o erro foi %(error)s"

#, python-format
msgid "Failed to remove snapshot for VM %s"
msgstr "Falha ao remover captura instantânea para a MV %s"

#, python-format
msgid "Failed to request Ironic to provision instance %(inst)s: %(reason)s"
msgstr ""
"Falha ao solicitar provisão da instância pelo Ironic %(inst)s: %(reason)s"

#, python-format
msgid ""
"Failed to retrieve encryption metadata for volume %(volume_id)s: "
"%(exception)s"
msgstr ""
"Falha ao recuperar metadados de criptografia para o volume %(volume_id)s: "
"%(exception)s"

msgid "Failed to retrieve ephemeral encryption key"
msgstr "Falha ao recuperar chave de criptografia efêmera"

msgid "Failed to revert crashed migration"
msgstr "Falha ao reverter a migração travada"

#, python-format
msgid "Failed to roll back reservations %s"
msgstr "Falha ao voltar atrás das reservas %s"

msgid "Failed to rollback quota for failed finish_resize"
msgstr "Falha ao recuperar cota para finish_resize"

#, python-format
msgid "Failed to send message to cell: %(next_hop)s"
msgstr "Falha ao enviar mensagem para a célula: %(next_hop)s"

msgid "Failed to send state update notification"
msgstr "Falha ao enviar notificação de atualização de estado"

msgid "Failed to send updated snapshot status to volume service."
msgstr ""
"Falha ao enviar status atualizado da captura instantânea para o serviço de "
"volume."

msgid "Failed to set instance name using multi_instance_display_name_template."
msgstr ""
"Falha ao configurar o nome da instância usando "
"multi_instance_display_name_template."

msgid "Failed to snapshot image"
msgstr "Falha ao obter captura instantânea da imagem"

#, python-format
msgid "Failed to start %(name)s on %(host)s:%(port)s with SSL support"
msgstr "Falha ao iniciar %(name)s no %(host)s:%(port)s com suporte SSL"

msgid "Failed to start instance"
msgstr "Falha ao iniciar a instância"

msgid "Failed to stop instance"
msgstr "Falha ao parar a instância"

#, python-format
msgid "Failed to swap volume %(old_volume_id)s for %(new_volume_id)s"
msgstr "Falha ao trocar volume %(old_volume_id)s para %(new_volume_id)s"

msgid "Failed to teardown container filesystem"
msgstr "Falha ao desativar o sistema de arquivos do contêiner"

msgid "Failed to umount container filesystem"
msgstr "Falha ao desmontar o sistema de arquivos do contêiner"

msgid "Failed to unpause instance"
msgstr "Falha ao despausar a instância"

#, python-format
msgid "Failed to untar %(image_location)s to %(image_path)s"
msgstr ""
"Falha ao descompactar arquivo tar %(image_location)s para %(image_path)s"

msgid "Failed to update usages bulk deallocating floating IP"
msgstr "Falha ao atualizar usos de desalocação de IP flutuante em massa"

msgid "Failed to update usages deallocating fixed IP"
msgstr "Falha ao atualizar usos de desalocação de IP fixo"

msgid "Failed to update usages deallocating floating IP"
msgstr "Falha ao atualizar usos de desalocação de IP flutuante"

msgid "Failed to update usages deallocating network."
msgstr "Falha ao atualizar usos de desalocação da rede."

msgid "Failed to update usages deallocating security group"
msgstr "Falha ao atualizar usos de desalocação de grupo de segurança"

msgid "Failed to update usages deallocating server group"
msgstr "Falha ao atualizar usos de desalocação de grupo de servidores"

#, python-format
msgid "Failed to upload %(image_location)s to %(image_path)s"
msgstr "Falha ao fazer upload de %(image_location)s para %(image_path)s"

msgid "Failed to write configuration file"
msgstr "Falha ao gravar arquivo de configuração"

msgid "Failed to write inbound.csr"
msgstr "Falha ao gravar inbound.csr"

msgid "Failed while plugging ib hostdev vif"
msgstr "Falha ao conectar ib hostdev vif"

msgid "Failed while plugging vif"
msgstr "Falha ao conectar vif"

msgid "Failed while unplugging ib hostdev vif"
msgstr "Falha ao desconectar ib hostdev vif"

msgid "Failed while unplugging vif"
msgstr "Falha ao desconectar vif"

msgid "Failure prepping block device"
msgstr "Falha na preparação do dispositivo de bloco"

msgid "Failure while cleaning up attached VDIs"
msgstr "Falha ao limpar VDIs conectados"

#, python-format
msgid "Fatal Exception running %(name)s %(type)s-hook: %(obj)s"
msgstr "Exceção Fatal ao executar %(name)s %(type)s-hook: %(obj)s"

msgid "Guest does not have a console available"
msgstr "O convidado não possui um console disponível"

msgid "Host is member of a pool, but DB says otherwise"
msgstr "O host é membro de um conjunto, mas o BD diz o contrário"

#, python-format
msgid ""
"Host mismatch detected in stashed volume connector. Will use local volume "
"connector. Instance host is %(ihost)s. Local volume connector host is "
"%(chost)s. Stashed volume connector host is %(schost)s."
msgstr ""
"Incompatibilidade de host detectada no conector de volume stash. Utilizando "
"conector de volume local. O host da instância é %(ihost)s. O host do "
"conector de volume local é %(chost)s. O host do conector de volume stash é "
"%(schost)s."

#, python-format
msgid ""
"Hostname has changed from %(old)s to %(new)s. A restart is required to take "
"effect."
msgstr ""
"O nome do host alterou de %(old)s para %(new)s. Um reinício é necessário "
"para entrar em vigor."

#, python-format
msgid "Image signature verification failed for image: %s"
msgstr "A verificação de assinatura da imagem falhou para a imagem: %s"

#, python-format
msgid "Image size %(size)d exceeded flavor allowed size %(allowed_size)d"
msgstr ""
"O tamanho da imagem %(size)d excedeu o tamanho de tipo permitido "
"%(allowed_size)d"

#, python-format
msgid "Improper or unknown HTTP status code used: %d"
msgstr "Código de status HTTP impróprio ou desconhecido usado: %d"

#, python-format
msgid ""
"Initialize connection failed for volume %(vol)s on host %(host)s. Error: "
"%(msg)s Code: %(code)s. Attempting to terminate connection."
msgstr ""
"Falha ao inicializar conexão para o volume %(vol)s no host %(host)s. Erro: "
"%(msg)s Código: %(code)s. Tentando finalizar a conexão."

#, python-format
msgid ""
"Instance compute service state on %s expected to be down, but it was up."
msgstr ""
"O estado de serviço de cálculo da instância em %s deveria ser inativo, mas "
"estava ativo. "

msgid "Instance failed block device setup"
msgstr "Falha da instância na configuração do dispositivo de bloco"

#, python-format
msgid "Instance failed network setup after %(attempts)d attempt(s)"
msgstr ""
"Falha da instância na configuração de rede após %(attempts)d attempt(s)"

msgid "Instance failed to spawn"
msgstr "Falha da instância ao usar spawn"

#, python-format
msgid "Interface %s not found"
msgstr "Interface %s não localizada"

#, python-format
msgid "Invalid server_string: %s"
msgstr "server_string inválido: %s"

#, python-format
msgid "Live Migration failure: %s"
msgstr "Falha na Migração em Tempo Real: %s"

msgid "Live migration failed."
msgstr "A migração em tempo real falhou."

msgid "Migrate Receive failed"
msgstr "Falha em Migrar Recebimento"

msgid "Migrate Send failed"
msgstr "Falha em Migrar Envio"

#, python-format
msgid "Migration %s is not found during confirmation"
msgstr "Migração %s não localizada durante a confirmação"

#, python-format
msgid "Migration for instance %(uuid)s refers to another host's instance!"
msgstr "A migração da instância %(uuid)s refere-se à outra instância do host!"

#, python-format
msgid ""
"Migration of instance %(instance_id)s to host %(dest)s unexpectedly failed."
msgstr ""
"A migração da instância %(instance_id)s para o host %(dest)s falhou "
"inesperadamente. "

msgid "Migration operation has aborted"
msgstr "A operação de migração foi interrompida"

#, python-format
msgid "NBD error - previous umount did not cleanup /var/lock/qemu-nbd-%s."
msgstr "Erro de NBD - a desmontagem anterior não limpou /var/lock/qemu-nbd-%s."

#, python-format
msgid ""
"NOT IMPLEMENTED: The call to %(method)s is not supported by the agent. args="
"%(args)r"
msgstr ""
"NÃO IMPLEMENTADO: A chamada para %(method)s não é suportada pelo agente. "
"args=%(args)r"

msgid "Network driver option required, but not specified"
msgstr "Opção de driver de rede necessária, mas não especificada"

#, python-format
msgid "Neutron Error adding rules to security group %s"
msgstr "Erro de Neutron ao incluir regras no grupo de segurança %s"

#, python-format
msgid "Neutron Error creating security group %s"
msgstr "Erro de Neutron ao criar o grupo de segurança %s"

#, python-format
msgid "Neutron Error getting security group %s"
msgstr "Erro de Neutron ao obter o grupo de segurança %s"

msgid "Neutron Error getting security groups"
msgstr "Erro de Neutron ao obter grupos de segurança"

#, python-format
msgid "Neutron Error unable to delete %s"
msgstr "Erro de Neutron: não é possível excluir %s"

#, python-format
msgid "Neutron Error updating security group %s"
msgstr "Erro de Neutron ao atualizar o grupo de segurança %s"

msgid "Neutron Error:"
msgstr "Erro de Neutron:"

#, python-format
msgid "Neutron Error: %s"
msgstr "Erro de Neutron: %s"

#, python-format
msgid "Neutron Reported failure on event %(event)s for instance %(uuid)s"
msgstr "O Neutron relatou falha no evento %(event)s para a instância %(uuid)s"

#, python-format
msgid "Neutron error creating port on network %s"
msgstr "Erro de Neutron ao criar porta na rede %s"

#, python-format
msgid "No compute node record for host %s"
msgstr "Nenhum registro de nó de cálculo para o host %s"

#, python-format
msgid "No load handler for %s"
msgstr "Nenhum manipulador de carga para %s"

#, python-format
msgid "No save handler for %s"
msgstr "Nenhum manipulador de salvamento para %s"

msgid "Not all properties needed are implemented in the compute driver"
msgstr ""
"Nem todas as propriedades necessárias estão implementadas no driver de "
"cálculo"

msgid ""
"Periodic sync_power_state task had an error while processing an instance."
msgstr ""
"Ocorreu um erro na tarefa periódica sync_power_state ao processar uma "
"instância."

msgid "Periodic task failed to offload instance."
msgstr "A tarefa periódica falhou ao transferir a instância."

msgid "Plugin config_file get_val failed"
msgstr "O plugin config_file get_val falhou"

#, python-format
msgid "Pool-Join failed: %s"
msgstr "A Junção de Conjunto falhou: %s"

#, python-format
msgid "Pool-eject failed: %s"
msgstr "A Ejeção de Conjunto falhou: %s"

#, python-format
msgid "Pool-set_name_label failed: %s"
msgstr "Pool-set_name_label falhou: %s"

#, python-format
msgid "Pre live migration failed at %s"
msgstr "A pré-migração em tempo real falhou em %s"

msgid "Read/Write data failed"
msgstr "A Leitura/Gravação de dados falhou"

#, python-format
msgid "Requested VM Generation %s is not supported on this OS."
msgstr "O VM Generation solicitado %s não é suportado neste S.O."

#, python-format
msgid "Requested VM Generation %s, but provided VHD instead of VHDX."
msgstr "O VM Generation solicitou %s, mas forneceu VHD em vez de VHDX."

#, python-format
msgid "Returning exception %s to caller"
msgstr "Retornando exceção %s ao método de origem"

msgid "Service error occurred during cleanup_host"
msgstr "Ocorreu um erro de serviço durante cleanup_host"

msgid "Setting instance vm_state to ERROR"
msgstr "Configurando a instância vm_state para ERROR"

msgid "Shutting down VM (cleanly) failed."
msgstr "O encerramento de MV (no modo normal) falhou"

msgid "Shutting down VM (hard) failed"
msgstr "O encerramento de MV (no modo forçado) falhou"

msgid ""
"Something wrong happened when trying to delete snapshot from shelved "
"instance."
msgstr ""
"Algo de errado ocorreu ao tentar excluir captura instantânea de uma "
"instância arquivada. "

#, python-format
msgid "TIMEOUT: The call to %(method)s timed out. args=%(args)r"
msgstr ""
"TIMEOUT: A chamada para %(method)s atingiu o tempo limite. args=%(args)r"

#, python-format
msgid "Temporary directory is invalid: %s"
msgstr "O diretório temporário é inválido: %s"

#, python-format
msgid "The Quobyte volume at %s is still in use."
msgstr "O volume Quobyte no %s ainda está em uso."

#, python-format
msgid "The agent call to %(method)s returned an error: %(ret)r. args=%(args)r"
msgstr ""
"A chamada do agente de %(method)s retornou um erro: %(ret)r. args=%(args)r"

#, python-format
msgid ""
"The agent call to %(method)s returned an invalid response: %(ret)r. args="
"%(args)r"
msgstr ""
"A chamada do agente de %(method)s retornou uma resposta inválida: %(ret)r. "
"args=%(args)r"

#, python-format
msgid "The call to %(method)s returned an error: %(e)s."
msgstr "A chamada para %(method)s retornou um erro: %(e)s."

#, python-format
msgid "The call to %(method)s returned an error: %(e)s. args=%(args)r"
msgstr "A chamada para %(method)s retornou um erro: %(e)s. args=%(args)r"

msgid "Transfer data failed"
msgstr "A transferência de dados falhou"

#, python-format
msgid "Unable to access floating IP %s"
msgstr "Não é possível acessar o IP flutuante %s"

#, python-format
msgid "Unable to access floating IP for %s"
msgstr "Não é possível acessar o IP flutuante para %s"

msgid "Unable to access the rescue disk"
msgstr "Não é possível acessar o disco de resgate"

#, python-format
msgid "Unable to attach volume to instance %s"
msgstr "Não é possível anexar o volume na instância %s"

#, python-format
msgid "Unable to clear device ID for port '%s'"
msgstr "Não é possível limpar o ID de dispositivo para a porta '%s'"

msgid "Unable to create VM snapshot, failing volume_snapshot operation."
msgstr ""
"Não é possível criar uma captura instantânea de MV, falha da operação "
"volume_snapshot. "

msgid ""
"Unable to create quiesced VM snapshot, attempting again with quiescing "
"disabled."
msgstr ""
"Não é possível criar uma captura instantânea de MV em quiesce, tentando "
"novamente com quiesce desativado. "

msgid "Unable to destroy VBD"
msgstr "Não é possível destruir o VBD"

#, python-format
msgid "Unable to execute %(cmd)s. Exception: %(exception)s"
msgstr "Não foi possível executar %(cmd)s. Exceção: %(exception)s"

msgid "Unable to find SR from VBD"
msgstr "Não é possível localizar SR a partir do VBD "

msgid "Unable to find SR from VDI"
msgstr "Não é possível localizar SR a partir do VDI"

msgid "Unable to get record of VDI"
msgstr "Não é possível obter registro do VDI"

msgid "Unable to get updated status"
msgstr "Não foi possível obter o status atualizado"

msgid "Unable to introduce VDI for SR"
msgstr "Não é possível introduzir VDI para SR "

msgid "Unable to introduce VDI on SR"
msgstr "Não é possível introduzir VDI no SR "

msgid "Unable to load the virtualization driver"
msgstr "Não é possível carregar o driver de virtualização"

#, python-format
msgid "Unable to migrate VM %(vm_ref)s from %(host)s"
msgstr "Não é possível migrar a MV %(vm_ref)s a partir do %(host)s"

#, python-format
msgid ""
"Unable to obtain RRD XML for VM %(vm_uuid)s with server details: %(server)s."
msgstr ""
"Não é possível obter o RRD XML para a VM %(vm_uuid)s com detalhes do "
"servidor: %(server)s."

#, python-format
msgid "Unable to parse rrd of %s"
msgstr "Não é possível analisar rrd de %s"

#, python-format
msgid "Unable to retrieve certificate with ID %(id)s: %(e)s"
msgstr "Não é possível recuperar o certificado com ID: %(id)s: %(e)s"

#, python-format
msgid "Unable to retrieve storage policy with name %s"
msgstr "Não é possível recuperar a política de armazenamento com o nome %s"

#, python-format
msgid "Unable to set up pool: %s."
msgstr "Não é possível configurar o conjunto: %s"

msgid "Unable to unplug VBD"
msgstr "Não é possível desconectar o VBD"

#, python-format
msgid "Unable to update instance VNIC index for port %s."
msgstr "Não é possível atualizar o índice VNIC da instância para a porta %s."

msgid "Unexpected build failure, not rescheduling build."
msgstr "Falha de construção inesperada, não replanejando a construção."

msgid "Unexpected error during post live migration at destination host."
msgstr "Erro inesperado durante pós-migração em tempo real no host de destino."

#, python-format
msgid "Unexpected error while checking process %(pid)s."
msgstr "Erro inesperado ao verificar o processo %(pid)s."

msgid "Unexpected error while reporting service status"
msgstr "Erro inesperado ao relatar o status de serviço"

msgid "Unexpected exception in API method"
msgstr "Exceção inesperada no método da API"

#, python-format
msgid "Unknown cell '%(cell_name)s' when trying to update capabilities"
msgstr "Célula desconhecida '%(cell_name)s' ao tentar atualizar recursos"

#, python-format
msgid "Unknown cell '%(cell_name)s' when trying to update capacities"
msgstr "Célula desconhecida '%(cell_name)s' ao tentar atualizar recursos"

#, python-format
msgid "Unknown content in connection_info/access_mode: %s"
msgstr "Conteúdo incerto em connection_info/access_mode: %s"

msgid "Unshelve attempted but an error has occurred"
msgstr "Houve uma tentativa de desarquivar, mas ocoreu um erro"

msgid "Unshelve attempted but vm_state not SHELVED or SHELVED_OFFLOADED"
msgstr ""
"Houve uma tentativa de desarquivar, mas vm_state não era SHELVED ou "
"SHELVED_OFFLOADED"

msgid "Vifs plug failed"
msgstr "O plug Vifs falhou"

#, python-format
msgid "Volume %s is associated with the instance but no SR was found for it"
msgstr ""
"O volume %s está associado à instância, mas nenhum SR foi localizado para "
"ele."

#, python-format
msgid "Volume is not writable. Please broaden the file permissions. Mount: %s"
msgstr ""
"O volume não é gravável. Aumente as permissões do arquivo. Montagem:  %s"

#, python-format
msgid ""
"When loading the module %(module_str)s the following error occurred: %(ex)s"
msgstr "Ao carregar o módulo %(module_str)s, o erro a seguir ocorreu: %(ex)s"

msgid ""
"XenAPI is unable to find a Storage Repository to install guest instances on. "
"Please check your configuration (e.g. set a default SR for the pool) and/or "
"configure the flag 'sr_matching_filter'."
msgstr ""
"O XenAPI não pode localizar um Repositório de Armazenamento no qual instalar "
"instâncias convidadas. Verifique sua configuração (por exemplo, configure um "
"SR padrão para o conjunto) e/ou configure o sinalizador 'sr_matching_filter'."

msgid ""
"You are running nova-compute on an unsupported version of Windows (older "
"than Windows / Hyper-V Server 2012). The support for this version of Windows "
"has been removed in Mitaka."
msgstr ""
"Você está executando nova-compute em uma versão não suportada do  Windows "
"(mais antiga que Windows / Hyper-V Server 2012). O suporte para essa versão "
"do  Windows foi removido do Mitaka."

msgid "_migrate_disk_resizing_down failed. Restoring orig vm"
msgstr "O _migrate_disk_resizing_down falhou. Restaurando MV de origem"

#, python-format
msgid "_migrate_disk_resizing_up failed. Restoring orig vm due_to: %s."
msgstr ""
"O _migrate_disk_resizing_up falhou. Restaurando MV de origem due_to: %s."

#, python-format
msgid "allocate_port_for_instance returned %(ports)s ports"
msgstr "allocate_port_for_instance retornou %(ports)s portas"

msgid "attaching network adapter failed."
msgstr "a anexação do adaptador de rede falhou."

msgid "detaching network adapter failed."
msgstr "a remoção do adaptador de rede falhou."

msgid "error during stop() in sync_power_state."
msgstr "erro durante stop() em sync_power_state."

#, python-format
msgid "error opening rbd image %s"
msgstr "Erro ao abrir a imagem rbd %s"

#, python-format
msgid "image %(volume)s in pool %(pool)s has snapshots, failed to remove"
msgstr ""
"A imagem %(volume)s no conjunto %(pool)s possui capturas instantâneas, e "
"falhou ao ser removida"

#, python-format
msgid "kill -HUP dnsmasq threw %s"
msgstr "kill -HUP dnsmasq threw %s"

#, python-format
msgid "killing radvd threw %s"
msgstr "eliminando radvd lançando %s"

msgid "nbd module not loaded"
msgstr "Módulo nbd não carregado"

msgid "set_admin_password failed"
msgstr "set_admin_password falhou"

#, python-format
msgid ""
"status is UNKNOWN from vm_state=%(vm_state)s task_state=%(task_state)s. Bad "
"upgrade or db corrupted?"
msgstr ""
"O status é UNKNOWN de vm_state=%(vm_state)s task_state=%(task_state)s. "
"Upgrade inválido ou db corrompido?"
