# Translations template for nova.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the nova project.
#
# Translators:
# FIRST AUTHOR <EMAIL@ADDRESS>, 2011
# Sasuke(Kyohei MORIYAMA) <>, 2015
# *pokotan-in-the-sky*  <>, 2012
# Tom Fifield <tom@openstack.org>, 2013
# Tomoyuki KATO <tomo@dream.daynight.jp>, 2013
# Andreas Jaeger <jaegerandi@gmail.com>, 2016. #zanata
msgid ""
msgstr ""
"Project-Id-Version: nova 14.0.0.0b3.dev750\n"
"Report-Msgid-Bugs-To: https://bugs.launchpad.net/openstack-i18n/\n"
"POT-Creation-Date: 2016-08-25 06:14+0000\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"PO-Revision-Date: 2016-04-04 06:25+0000\n"
"Last-Translator: Tsutomu Kimura <ebb0de2@jp.ibm.com>\n"
"Language: ja\n"
"Plural-Forms: nplurals=1; plural=0;\n"
"Generated-By: Babel 2.0\n"
"X-Generator: Zanata 3.7.3\n"
"Language-Team: Japanese\n"

#, python-format
msgid "%(address)s is not a valid IP address."
msgstr "%(address)s は有効な IP アドレスではありません。"

#, python-format
msgid "%(address)s is not a valid IP v4/6 address."
msgstr "%(address)s が有効な IP v4/6 アドレスではありません。"

#, python-format
msgid "%(address)s is not within %(cidr)s."
msgstr "%(address)s は %(cidr)s 内にありません。"

#, python-format
msgid ""
"%(binary)s attempted direct database access which is not allowed by policy"
msgstr ""
"%(binary)s が直接データベースへアクセスしようとしましたが、これはポリシーで許"
"可されていません"

#, python-format
msgid "%(cidr)s is not a valid IP network."
msgstr "%(cidr)s や有効な IP ネットワークではありません。"

#, python-format
msgid ""
"%(desc)r\n"
"command: %(cmd)r\n"
"exit code: %(code)r\n"
"stdout: %(stdout)r\n"
"stderr: %(stderr)r"
msgstr ""
"%(desc)r\n"
"コマンド: %(cmd)r\n"
"終了コード: %(code)r\n"
"stdout: %(stdout)r\n"
"stderr: %(stderr)r"

#, python-format
msgid "%(err)s"
msgstr "%(err)s"

#, python-format
msgid ""
"%(event_type)s is not a versioned notification and not whitelisted. See ./"
"doc/source/notification.rst"
msgstr ""
"%(event_type)s はバージョンが設定された通知でもなければ、ホワイトリストの対象"
"にもなっていません。./doc/source/notification.rst を参照してください。"

#, python-format
msgid "%(field)s should not be part of the updates."
msgstr "%(field)s を更新に含めることはできません。"

#, python-format
msgid "%(fieldname)s missing field type"
msgstr "%(fieldname)s のフィールドタイプがありません"

#, python-format
msgid "%(host)s:%(port)s: Target closed"
msgstr "%(host)s:%(port)s: ターゲットがクローズされました"

#, python-format
msgid "%(key)s is not a valid quota key. Valid options are: %(options)s."
msgstr ""
"%(key)s は有効なクォータキーではありません。有効なオプションは %(options)s で"
"す。"

#, python-format
msgid "%(key)s must be an integer."
msgstr "%(key)s は整数でなければなりません。"

#, python-format
msgid "%(memsize)d MB of memory assigned, but expected %(memtotal)d MB"
msgstr ""
"%(memsize)d MB のメモリーが割り当てられていますが、%(memtotal)d MB が期待され"
"ていました"

#, python-format
msgid "%(name)s has a minimum character requirement of %(min_length)s."
msgstr "%(name)s の最小文字数は %(min_length)s という要件があります。"

#, python-format
msgid "%(name)s has more than %(max_length)s characters."
msgstr "%(name)s が %(max_length)s 文字を超えています。"

#, python-format
msgid "%(path)s is not on local storage: %(reason)s"
msgstr "%(path)s はローカルストレージ上にありません: %(reason)s"

#, python-format
msgid "%(path)s is not on shared storage: %(reason)s"
msgstr "%(path)s は共有ストレージ上にありません: %(reason)s"

#, python-format
msgid "%(req)s is required to create a network."
msgstr "ネットワークを作成するには %(req)s が必要です。"

#, python-format
msgid "%(total)i rows matched query %(meth)s, %(done)i migrated"
msgstr "%(total)i 行がクエリー %(meth)s に合致し、%(done)i が移行しました"

#, python-format
msgid "%(type)s hypervisor does not support PCI devices"
msgstr "%(type)s ハイパーバイザーは PCI デバイスをサポートしていません"

#, python-format
msgid "%(typename)s in %(fieldname)s is not an instance of Enum"
msgstr "%(fieldname)s 内の %(typename)s は Enum のインスタンスです"

#, python-format
msgid "%(value_name)s must be <= %(max_value)d"
msgstr "%(value_name)s は <= %(max_value)d 以下でなければなりません"

#, python-format
msgid "%(value_name)s must be >= %(min_value)d"
msgstr "%(value_name)s は %(min_value)d 以上でなければなりません"

#, python-format
msgid "%(value_name)s must be an integer"
msgstr "%(value_name)s は整数でなければなりません"

#, python-format
msgid "%(worker_name)s value of %(workers)s is invalid, must be greater than 0"
msgstr ""
"%(workers)s の %(worker_name)s 値が無効です。0 より大きい値にしなければなりま"
"せん"

#, python-format
msgid "%r failed. Not Retrying."
msgstr "%r が失敗しました。再試行しません。"

#, python-format
msgid "%r failed. Retrying."
msgstr "%r が失敗しました。再試行しています。"

#, python-format
msgid "%s does not support disk hotplug."
msgstr "%s ではディスクのホットプラグはサポートされていません。"

#, python-format
msgid "%s format is not supported"
msgstr "%s 形式はサポートされていません"

#, python-format
msgid "%s is not a string or unicode"
msgstr "%s が文字列でも Unicode でもありません"

#, python-format
msgid "%s is not a valid node managed by this compute host."
msgstr "%s は、このコンピュートホストが管理する有効なノードではありません。"

#, python-format
msgid "%s is not supported."
msgstr "%s はサポートされていません。"

#, python-format
msgid "%s must be either 'MANUAL' or 'AUTO'."
msgstr "%s は 'MANUAL' または 'AUTO' のいずれかでなければいけません。"

#, python-format
msgid "'%(other)s' should be an instance of '%(cls)s'"
msgstr "'%(other)s' は'%(cls)s' のインスタンスである必要があります"

msgid "'qemu-img info' parsing failed."
msgstr "'qemu-img info' の解析に失敗しました。"

#, python-format
msgid "'rxtx_factor' argument must be a float between 0 and %g"
msgstr ""
"'rxtx_factor' 引数は 0 から %g の範囲内の浮動小数点数でなければなりません"

#, python-format
msgid "/%s should be specified as single address(es) not in cidr format"
msgstr ""
"/%s は CIDR 形式で指定せずに、単一のアドレスとして指定する必要があります。"

msgid "A CPU model name should not be set when a host CPU model is requested"
msgstr "ホスト CPU モデルの要求時に CPU モデル名は設定できません"

#, python-format
msgid "A NetworkModel is required in field %s"
msgstr "フィールド %s に NetworkModel が必要です"

#, python-format
msgid ""
"API Version String %(version)s is of invalid format. Must be of format "
"MajorNum.MinorNum."
msgstr ""
"API バージョン文字列 %(version)s の形式が無効です。形式は MajorNum.MinorNum "
"でなければなりません。"

#, python-format
msgid "API version %(version)s is not supported on this method."
msgstr "API バージョン %(version)s はこのメソッドではサポートされていません。"

msgid "Access list not available for public flavors."
msgstr "パブリックフレーバーではアクセスリストを使用できません。"

#, python-format
msgid "Action %s not found"
msgstr "アクション %s が見つかりません"

#, python-format
msgid ""
"Action for request_id %(request_id)s on instance %(instance_uuid)s not found"
msgstr ""
"インスタンス %(instance_uuid)s に対する request_id %(request_id)s のアクショ"
"ンが見つかりません"

#, python-format
msgid "Action: '%(action)s', calling method: %(meth)s, body: %(body)s"
msgstr "アクション: '%(action)s'、呼び出しメソッド: %(meth)s、本文: %(body)s"

#, python-format
msgid "Add metadata failed for aggregate %(id)s after %(retries)s retries"
msgstr ""
"アグリゲート %(id)s にメタデータを追加しようと %(retries)s 回再試行しました"
"が、追加できませんでした"

msgid "Address could not be converted."
msgstr "アドレスを変換できませんでした。"

msgid "Affinity instance group policy was violated."
msgstr "Affinity インスタンスグループポリシーに違反しました"

#, python-format
msgid "Agent does not support the call: %(method)s"
msgstr "エージェントは、呼び出し %(method)s をサポートしていません"

#, python-format
msgid ""
"Agent-build with hypervisor %(hypervisor)s os %(os)s architecture "
"%(architecture)s exists."
msgstr ""
"ハイパーバイザー %(hypervisor)s の OS %(os)s アーキテクチャー "
"%(architecture)s のエージェントビルドが存在します。"

#, python-format
msgid "Aggregate %(aggregate_id)s already has host %(host)s."
msgstr "アグリゲート %(aggregate_id)s には既にホスト %(host)s があります。"

#, python-format
msgid "Aggregate %(aggregate_id)s could not be found."
msgstr "アグリゲート %(aggregate_id)s が見つかりませんでした。"

#, python-format
msgid "Aggregate %(aggregate_id)s has no host %(host)s."
msgstr "アグリゲート %(aggregate_id)s にはホスト %(host)s がありません。"

#, python-format
msgid "Aggregate %(aggregate_id)s has no metadata with key %(metadata_key)s."
msgstr ""
"アグリゲート %(aggregate_id)s にはキー %(metadata_key)s を持つメタデータはあ"
"りません。"

#, python-format
msgid ""
"Aggregate %(aggregate_id)s: action '%(action)s' caused an error: %(reason)s."
msgstr ""
"アグリゲート %(aggregate_id)s: アクション '%(action)s' でエラーが発生しまし"
"た: %(reason)s。"

#, python-format
msgid "Aggregate %(aggregate_name)s already exists."
msgstr "アグリゲート %(aggregate_name)s は既に存在します。"

#, python-format
msgid "Aggregate %s does not support empty named availability zone"
msgstr "アグリゲート %s は空の名前のアベイラビリティーゾーンをサポートしません"

#, fuzzy, python-format
msgid "Aggregate for host %(host)s count not be found."
msgstr "ホスト %(host)s カウントの総計が見つかりません。"

msgid "All hosts are already mapped to cell(s), exiting."
msgstr "すべてのホストが既にセルにマッピングされています。処理を終了します。"

#, python-format
msgid "An invalid 'name' value was provided. The name must be: %(reason)s"
msgstr ""
"無効な 'name' の値が提供されました。名前は以下である必要があります: "
"%(reason)s"

msgid "An unknown error has occurred. Please try your request again."
msgstr "未知のエラーが発生しました。再度リクエストを実行してください。"

msgid "An unknown exception occurred."
msgstr "不明な例外が発生しました。"

msgid "Anti-affinity instance group policy was violated."
msgstr "anti-affinity インスタンスグループポリシーに違反しました。"

#, python-format
msgid "Architecture name '%(arch)s' is not recognised"
msgstr "アーキテクチャー名 '%(arch)s' は認識できません"

#, python-format
msgid "Architecture name '%s' is not valid"
msgstr "アーキテクチャー名 '%s' が有効ではありません"

msgid ""
"Asymmetric NUMA topologies require explicit assignment of CPUs and memory to "
"nodes in image or flavor"
msgstr ""
"非対称 NUMA トポロジーでは、CPU とメモリーのノードへの割り当てを、イメージか"
"フレーバーで明示的に指定する必要があります"

#, python-format
msgid ""
"Attempt to consume PCI device %(compute_node_id)s:%(address)s from empty pool"
msgstr ""
"空のプールから PCI デバイス %(compute_node_id)s:%(address)s を取り込んでみて"
"ください"

msgid "Attempted overwrite of an existing value."
msgstr "既存の値を上書きしようとしました。"

#, python-format
msgid "Attribute not supported: %(attr)s"
msgstr "この属性はサポートされていません: %(attr)s"

#, python-format
msgid "Bad mac for to_global_ipv6: %s"
msgstr "to_global_ipv6 の MAC が正しくありません: %s"

#, python-format
msgid "Bad network format: missing %s"
msgstr "ネットワークの形式が正しくありません。%s がありません"

msgid "Bad networks format"
msgstr "ネットワークの形式が正しくありません"

#, python-format
msgid "Bad networks format: network uuid is not in proper format (%s)"
msgstr ""
"ネットワークの形式が正しくありません。ネットワーク UUID が適切な形式になって"
"いません (%s)"

#, python-format
msgid "Bad prefix for network in cidr %s"
msgstr "CIDR %s 内のネットワークでは無効なプレフィックス"

#, python-format
msgid "Bad prefix for to_global_ipv6: %s"
msgstr "to_global_ipv6 のプレフィックスが正しくありません: %s"

#, python-format
msgid ""
"Binding failed for port %(port_id)s, please check neutron logs for more "
"information."
msgstr ""
"ポート %(port_id)s でバインドが失敗しました。詳細情報については neutron のロ"
"グを確認してください。"

msgid "Blank components"
msgstr "空白コンポーネント"

msgid ""
"Blank volumes (source: 'blank', dest: 'volume') need to have non-zero size"
msgstr ""
"ブランクのボリューム (ソース: 'blank'、宛先: 'volume') にはゼロでないサイズを"
"設定する必要があります"

#, python-format
msgid "Block Device %(id)s is not bootable."
msgstr "ブロックデバイス %(id)s がブート可能ではありません。"

#, python-format
msgid ""
"Block Device Mapping %(volume_id)s is a multi-attach volume and is not valid "
"for this operation."
msgstr ""
"ブロックデバイスマッピング %(volume_id)s は複数の接続を持つボリュームであり、"
"この処理には有効ではありません。"

msgid "Block Device Mapping cannot be converted to legacy format. "
msgstr "ブロックデバイスマッピングを以前の形式に変換することはできません。"

msgid "Block Device Mapping is Invalid."
msgstr "ブロックデバイスマッピングが無効です。"

#, python-format
msgid "Block Device Mapping is Invalid: %(auth_method)s is unsupported."
msgstr ""
"ブロックデバイスマッピングが無効です。%(auth_method)s はサポートされません。"

#, python-format
msgid "Block Device Mapping is Invalid: %(details)s"
msgstr "ブロックデバイスマッピングが無効です: %(details)s"

msgid ""
"Block Device Mapping is Invalid: Boot sequence for the instance and image/"
"block device mapping combination is not valid."
msgstr ""
"ブロックデバイスマッピングが無効です。指定されたインスタンスとイメージ/ブロッ"
"クデバイスマッピングの組み合わせでのブートシーケンスは無効です。"

msgid ""
"Block Device Mapping is Invalid: You specified more local devices than the "
"limit allows"
msgstr ""
"ブロックデバイスマッピングが無効です。制限で許可されているよりも多くのローカ"
"ルデバイスが指定されました。"

#, python-format
msgid "Block Device Mapping is Invalid: failed to get image %(id)s."
msgstr ""
"ブロックデバイスマッピングが無効です。イメージ %(id)s の取得に失敗しました。"

#, python-format
msgid "Block Device Mapping is Invalid: failed to get snapshot %(id)s."
msgstr ""
"ブロックデバイスマッピングが無効です。スナップショット %(id)s の取得に失敗し"
"ました。"

#, python-format
msgid "Block Device Mapping is Invalid: failed to get volume %(id)s."
msgstr ""
"ブロックデバイスマッピングが無効です。ボリューム %(id)s の取得に失敗しまし"
"た。"

msgid "Block migration can not be used with shared storage."
msgstr ""
"ブロックマイグレーションを使用するときに、共有ストレージを使用することはでき"
"ません。"

msgid "Boot index is invalid."
msgstr "boot インデックスが無効です。"

#, python-format
msgid "Build of instance %(instance_uuid)s aborted: %(reason)s"
msgstr "インスタンス %(instance_uuid)s の作成は打ち切られました: %(reason)s"

#, python-format
msgid "Build of instance %(instance_uuid)s was re-scheduled: %(reason)s"
msgstr ""
"インスタンス %(instance_uuid)s の作成は再スケジュールされました: %(reason)s"

#, python-format
msgid "BuildRequest not found for instance %(uuid)s"
msgstr "インスタンス %(uuid)s に関する BuildRequest が見つかりません"

msgid "CPU and memory allocation must be provided for all NUMA nodes"
msgstr ""
"CPU とメモリーの割り当ては、すべての NUMA ノードに指定しなければなりません"

#, python-format
msgid ""
"CPU doesn't have compatibility.\n"
"\n"
"%(ret)s\n"
"\n"
"Refer to %(u)s"
msgstr ""
"CPU に互換性がありません。\n"
"\n"
"%(ret)s\n"
"\n"
"%(u)s を参照"

#, python-format
msgid "CPU number %(cpunum)d is assigned to two nodes"
msgstr "CPU 番号 %(cpunum)d は 2 つのノードに割り当てられています"

#, python-format
msgid "CPU number %(cpunum)d is larger than max %(cpumax)d"
msgstr "CPU 番号 %(cpunum)d は最大値 %(cpumax)d を超えています"

#, python-format
msgid "CPU number %(cpuset)s is not assigned to any node"
msgstr "CPU 番号 %(cpuset)s はノードに割り当てられていません"

#, python-format
msgid "CPU pinning is not supported by the host: %(reason)s"
msgstr "ホストは CPU の固定を行うことができません: %(reason)s"

msgid "Can not add access to a public flavor."
msgstr "パブリックフレーバーにアクセスを追加できません"

msgid "Can not find requested image"
msgstr "要求されたイメージが見つかりません"

#, python-format
msgid "Can not handle authentication request for %d credentials"
msgstr "%d 認証情報に関する認証要求を処理できません"

#, python-format
msgid "Can only run %s more instances of this type."
msgstr "このタイプのインスタンスは、あと %s 個に限り実行できます。"

msgid "Can't detach root device volume"
msgstr "ルートデバイスボリュームは切断することはできません"

msgid "Can't resize a disk to 0 GB."
msgstr "ディスクのサイズを 0 GB に変更することはできません。"

msgid "Can't resize down ephemeral disks."
msgstr "一時ディスクのサイズを減らすことはできません。"

msgid "Can't retrieve root device path from instance libvirt configuration"
msgstr "インスタンスの libvirt 設定からルートデバイスのパスを取得できません"

#, python-format
msgid ""
"Cannot '%(action)s' instance %(server_id)s while it is in %(attr)s %(state)s"
msgstr ""
"インスタンス %(server_id)s が %(attr)s %(state)s にある間は '%(action)s' を行"
"うことはできません"

#, python-format
msgid ""
"Cannot access \"%(instances_path)s\", make sure the path exists and that you "
"have the proper permissions. In particular Nova-Compute must not be executed "
"with the builtin SYSTEM account or other accounts unable to authenticate on "
"a remote host."
msgstr ""
"\"%(instances_path)s\" にアクセスできません。パスが存在し、適切な許可を持って"
"いることを確認してください。特に、Nova-Compute は、リモートホスト上で認証でき"
"ない組み込みのシステムアカウント等のアカウントで実行してはなりません。"

#, python-format
msgid "Cannot access 'scality_sofs_config': %s"
msgstr "'scality_sofs_config' にアクセスできません: %s"

#, python-format
msgid "Cannot add host to aggregate %(aggregate_id)s. Reason: %(reason)s."
msgstr ""
"ホストをアグリゲート %(aggregate_id)s に追加できません。理由: %(reason)s。"

msgid "Cannot attach one or more volumes to multiple instances"
msgstr "1 つのボリュームを複数のインスタンスに接続できません"

#, python-format
msgid ""
"Cannot block migrate instance %(uuid)s with mapped volumes. Selective block "
"device migration feature requires libvirt version %(libvirt_ver)s"
msgstr ""
"マッピングされたボリュームを使用してインスタンス %(uuid)s のブロックをマイグ"
"レーションすることはできません。特定のブロックデバイスをマイグレーションする"
"には、libvirt のバージョン %(libvirt_ver)s が必要です。"

#, python-format
msgid "Cannot call %(method)s on orphaned %(objtype)s object"
msgstr ""
"親のない %(objtype)s オブジェクトで %(method)s を呼び出すことはできません"

msgid ""
"Cannot create default bittorrent URL without xenserver.torrent_base_url "
"configuration option set."
msgstr ""
"xenserver.torrent_base_url の設定オプションを設定しないかぎり、デフォルトの "
"bittorrent URL を作成できません。"

#, python-format
msgid ""
"Cannot determine the parent storage pool for %s; cannot determine where to "
"store images"
msgstr ""
"%s の親のストレージプールを検出できません。イメージを保存する場所を決定できま"
"せん。"

msgid "Cannot disassociate auto assigned floating IP"
msgstr ""
"自動的に割り当てられたFloating IP の割り当て解除を行うことができません。"

msgid "Cannot execute /sbin/mount.sofs"
msgstr "/sbin/mount.sofs を実行できません"

msgid "Cannot find SR of content-type ISO"
msgstr "コンテンツタイプが ISO の SR が見つかりません"

msgid "Cannot find SR to read/write VDI."
msgstr "VDI の読み取り/書き込み用の SR が見つかりません。"

msgid "Cannot find image for rebuild"
msgstr "再作成用のイメージが見つかりません"

#, python-format
msgid "Cannot load scheduler driver from configuration %(conf)s."
msgstr "設定 %(conf)s からスケジューラードライバーをロードできません。"

msgid "Cannot mount Scality SOFS, check syslog for errors"
msgstr "Scality SOFS をマウントできません。syslog でエラーを確認してください"

#, python-format
msgid "Cannot remove host %(host)s in aggregate %(id)s"
msgstr "ホスト %(host)s をアグリゲート %(id)s から削除できません"

#, python-format
msgid "Cannot remove host from aggregate %(aggregate_id)s. Reason: %(reason)s."
msgstr ""
"ホストをアグリゲート %(aggregate_id)s から削除できません。理由: %(reason)s。"

msgid "Cannot rescue a volume-backed instance"
msgstr "ボリュームを使ったインスタンスはレスキューできません"

#, python-format
msgid ""
"Cannot resize the root disk to a smaller size. Current size: "
"%(curr_root_gb)s GB. Requested size: %(new_root_gb)s GB."
msgstr ""
"ルートディスクのサイズを小さくすることはできません。現在のサイズ: "
"%(curr_root_gb)s GB。要求されたサイズ: %(new_root_gb)s GB。"

msgid "Cannot run any more instances of this type."
msgstr "このタイプのインスタンスをこれ以上実行することはできません。"

msgid ""
"Cannot set cpu thread pinning policy in a non dedicated cpu pinning policy"
msgstr ""
"専用でない CPU の固定ポリシーではCPU スレッドの固定ポリシーを設定できません"

msgid "Cannot set realtime policy in a non dedicated cpu pinning policy"
msgstr ""
"専用でない CPU の固定ポリシーではリアルタイムのポリシーを設定できません"

#, python-format
msgid "Cannot update aggregate %(aggregate_id)s. Reason: %(reason)s."
msgstr "アグリゲート %(aggregate_id)s を更新できません。理由: %(reason)s。"

msgid "Cannot update cells configuration file."
msgstr "セルの設定ファイルを更新できません。"

#, python-format
msgid ""
"Cannot update metadata of aggregate %(aggregate_id)s. Reason: %(reason)s."
msgstr ""
"アグリゲート %(aggregate_id)s のメタデータを更新できません。理由: "
"%(reason)s。"

#, python-format
msgid "Cell %(cell_name)s doesn't exist."
msgstr "セル %(cell_name)s は存在しません。"

#, python-format
msgid "Cell %(uuid)s has no mapping."
msgstr "セル %(uuid)s にはマッピングがありません。"

#, python-format
msgid "Cell %s doesn't exist."
msgstr "セル %s は存在しません。"

#, python-format
msgid "Cell is not known for instance %(instance_uuid)s"
msgstr "セルはインスタンス %(instance_uuid)s で認識されていません"

#, python-format
msgid "Cell message has reached maximum hop count: %(hop_count)s"
msgstr "セルメッセージが最大ホップ数 %(hop_count)s に達しました"

#, python-format
msgid "Cell with name %(name)s already exists."
msgstr "名前が %(name)s のセルは既に存在します。"

#, python-format
msgid "Certificate is not valid after: %s UTC"
msgstr "証明書は以下の時間以降には無効です: %s UTC"

#, python-format
msgid "Certificate is not valid before: %s UTC"
msgstr "証明書は以下の時間以前には無効です: %s UTC"

#, python-format
msgid ""
"Change would make usage less than 0 for the following resources: %(unders)s"
msgstr "変更によって、リソース %(unders)s の使用量が 0 未満になります"

msgid "Claim pci failed."
msgstr "PCI デバイスの要求に失敗しました。"

#, python-format
msgid "Class %(class_name)s could not be found: %(exception)s"
msgstr "クラス %(class_name)s が見つかりませんでした: %(exception)s"

#, python-format
msgid ""
"Command Not supported. Please use Ironic command %(cmd)s to perform this "
"action."
msgstr ""
"コマンドはサポートされていません。このアクションを実行するには、Ironic コマン"
"ド %(cmd)s を使用してください。"

#, python-format
msgid "Compute host %(host)s could not be found."
msgstr "コンピュートホスト %(host)s が見つかりませんでした。"

#, python-format
msgid "Compute host %(name)s needs to be created first before updating."
msgstr ""
"更新する前に、まずコンピュートホスト %(name)s を作成する必要があります。"

#, python-format
msgid "Compute host %s not found."
msgstr "コンピュートホスト %s が見つかりません。"

#, python-format
msgid "Compute service of %(host)s is still in use."
msgstr "%(host)s のコンピュートサービスが依然として使用されています。"

#, python-format
msgid "Compute service of %(host)s is unavailable at this time."
msgstr "この時点では %(host)s のコンピュートサービスを使用できません。"

#, python-format
msgid "Config drive format '%(format)s' is not supported."
msgstr "コンフィグドライブ形式 %(format)s がサポートされません。"

msgid "Config requested a custom CPU model, but no model name was provided"
msgstr ""
"設定でカスタム CPU モデルが要求されましたが、モデル名が指定されませんでした"

#, python-format
msgid ""
"Config requested an explicit CPU model, but the current libvirt hypervisor "
"'%s' does not support selecting CPU models"
msgstr ""
"設定で、明示的な CPU モデルが要求されましたが、現在の libvirt ハイパーバイ"
"ザー '%s' は CPU モデルの選択をサポートしていません"

#, python-format
msgid ""
"Conflict updating instance %(instance_uuid)s, but we were unable to "
"determine the cause"
msgstr ""
"インスタンス %(instance_uuid)s の更新で競合が発生したものの、原因を特定できま"
"せんでした。"

#, python-format
msgid ""
"Conflict updating instance %(instance_uuid)s. Expected: %(expected)s. "
"Actual: %(actual)s"
msgstr ""
"インスタンス %(instance_uuid)s の更新で競合が発生しました。%(expected)s を期"
"待したものの、実際には %(actual)s が得られました"

#, python-format
msgid "Connection to cinder host failed: %(reason)s"
msgstr "cinder ホストへの接続に失敗しました: %(reason)s"

#, python-format
msgid "Connection to glance host %(server)s failed: %(reason)s"
msgstr "glance ホスト %(server)s への接続に失敗しました: %(reason)s"

#, python-format
msgid "Connection to libvirt lost: %s"
msgstr "libvirt との接続が失われました: %s"

#, python-format
msgid "Connection to the hypervisor is broken on host: %(host)s"
msgstr "ホスト %(host)s でハイパーバイザーへの接続がおかしくなっています"

#, python-format
msgid "Console %(console_id)s could not be found."
msgstr "コンソール %(console_id)s が見つかりませんでした。"

#, python-format
msgid "Console for instance %(instance_uuid)s could not be found."
msgstr "インスタンス %(instance_uuid)s 用のコンソールが見つかりませんでした。"

#, python-format
msgid ""
"Console for instance %(instance_uuid)s in pool %(pool_id)s could not be "
"found."
msgstr ""
"プール %(pool_id)s 内のインスタンス %(instance_uuid)s 用のコンソールが見つか"
"りませんでした。"

#, python-format
msgid ""
"Console log output could not be retrieved for instance %(instance_id)s. "
"Reason: %(reason)s"
msgstr ""
"インスタンス %(instance_id)s についてコンソールログの出力を取得できませんでし"
"た。理由: %(reason)s"

#, python-format
msgid "Console pool %(pool_id)s could not be found."
msgstr "コンソールプール %(pool_id)s が見つかりませんでした。"

#, python-format
msgid ""
"Console pool of type %(console_type)s for compute host %(compute_host)s on "
"proxy host %(host)s not found."
msgstr ""
"プロキシーホスト %(host)s 上でコンピュートホスト %(compute_host)s 用の、タイ"
"プが %(console_type)s のコンソールプールが見つかりません。"

#, python-format
msgid ""
"Console pool with host %(host)s, console_type %(console_type)s and "
"compute_host %(compute_host)s already exists."
msgstr ""
"ホスト %(host)s、コンソールタイプ %(console_type)s、コンピュートホスト "
"%(compute_host)s のコンソールプールは既に存在します。"

msgid "Constraint not met."
msgstr "制約が満たされていません。"

#, python-format
msgid "Converted to raw, but format is now %s"
msgstr "raw 形式に変換されましたが、現在の形式は %s です"

#, python-format
msgid "Core API extensions are missing: %(missing_apis)s"
msgstr "コア API 拡張がありません: %(missing_apis)s"

#, fuzzy, python-format
msgid "Could not attach image to loopback: %s"
msgstr "イメージをループバック %s にアタッチできません。"

#, python-format
msgid "Could not fetch image %(image_id)s"
msgstr "イメージ %(image_id)s を取り出すことができませんでした"

#, python-format
msgid "Could not find a handler for %(driver_type)s volume."
msgstr "%(driver_type)s ボリュームのハンドラーが見つかりませんでした。"

#, fuzzy
msgid "Could not find another compute"
msgstr "別のコンピュートが見つかりませんでした"

#, python-format
msgid "Could not find binary %(binary)s on host %(host)s."
msgstr "ホスト %(host)s 上でバイナリー %(binary)s が見つかりませんでした。"

#, python-format
msgid "Could not find config at %(path)s"
msgstr "%(path)s に config が見つかりませんでした"

msgid "Could not find the datastore reference(s) which the VM uses."
msgstr "VM が使用するデータストア参照が見つかりませんでした。"

#, python-format
msgid "Could not load line %(line)s, got error %(error)s"
msgstr ""
"行 %(line)s をロードできませんでした。エラー %(error)s を受け取りました"

#, python-format
msgid "Could not load paste app '%(name)s' from %(path)s"
msgstr ""
"paste アプリケーション '%(name)s' を %(path)s からロードできませんでした"

#, python-format
msgid ""
"Could not mount vfat config drive. %(operation)s failed. Error: %(error)s"
msgstr ""
"vfat コンフィグドライブをマウントできません。%(operation)s が失敗しました。エ"
"ラー: %(error)s"

#, python-format
msgid "Could not read %s. Re-running with sudo"
msgstr "%s を読み取ることができませんでした。sudo で再実行します"

#, python-format
msgid "Could not upload image %(image_id)s"
msgstr "イメージ %(image_id)s をアップロードできませんでした"

#, python-format
msgid "Couldn't get Link Local IP of %(interface)s :%(ex)s"
msgstr "%(interface)s のローカル IP アドレスのリンクが取得できません:%(ex)s"

msgid "Create networks failed"
msgstr "ネットワークの作成に失敗しました"

msgid "Creation of virtual interface with unique mac address failed"
msgstr "一意な MAC アドレスを持つ仮想インターフェースを作成できませんでした"

msgid "DNS entries not found."
msgstr "DNS エントリーが見つかりません。"

msgid "DNS1"
msgstr "DNS1"

msgid "DNS2"
msgstr "DNS2"

#, python-format
msgid "Datastore regex %s did not match any datastores"
msgstr "データストア regex %s がどのデータストアとも一致しませんでした"

msgid "Datetime is in invalid format"
msgstr "日時が無効な形式です"

msgid "Default PBM policy is required if PBM is enabled."
msgstr "PBM が有効になっている場合、デフォルト PBM ポリシーは必須です。"

#, python-format
msgid "Deleted %(records)d records from table '%(table_name)s'."
msgstr "レコード %(records)d がテーブル '%(table_name)s' から削除されました。"

msgid "Deleting by fixed_range is not supported with the NeutronManager"
msgstr "fixed_range による削除は、NeutronManager ではサポートされていません"

#, python-format
msgid "Destination host:%s must be in the same aggregate as the source server"
msgstr ""
"宛先ホスト:%s は移動元サーバーと同じアグリゲート内に存在しなければなりません"

#, python-format
msgid "Detected existing vlan with id %(vlan)d"
msgstr "ID %(vlan)d を持つ既存の VLAN が検出されました"

#, python-format
msgid "Device '%(device)s' not found."
msgstr "デバイス '%(device)s' が見つかりません。"

#, python-format
msgid ""
"Device id %(id)s specified is not supported by hypervisor version %(version)s"
msgstr ""
"指定されたデバイス id %(id)s はハイパーバイザーバージョン %(version)s ではサ"
"ポートされていません"

msgid "Device name contains spaces."
msgstr "デバイス名に空白が含まれています。"

msgid "Device name empty or too long."
msgstr "デバイス名が空か、長すぎます。"

#, python-format
msgid "Device type mismatch for alias '%s'"
msgstr "別名 '%s' のデバイスタイプが一致しません"

#, python-format
msgid ""
"Different types in %(table)s.%(column)s and shadow table: %(c_type)s "
"%(shadow_c_type)s"
msgstr ""
"%(table)s.%(column)s とシャドーテーブル内のタイプが異なります: %(c_type)s "
"%(shadow_c_type)s"

#, python-format
msgid "Disk contains a filesystem we are unable to resize: %s"
msgstr "ディスクにサイズ変更できないファイルシステムが含まれています: %s"

#, python-format
msgid "Disk format %(disk_format)s is not acceptable"
msgstr "ディスク形式 %(disk_format)s は受け付けられません"

#, python-format
msgid "Disk info file is invalid: %(reason)s"
msgstr "ディスク情報ファイルが無効です: %(reason)s"

msgid "Disk must have only one partition."
msgstr "ディスクのパーティションは 1 つのみでなければなりません。"

#, python-format
msgid "Disk with id: %s not found attached to instance."
msgstr "ID が %s のインスタンスに接続されたディスクが見つかりません。"

#, python-format
msgid "Driver Error: %s"
msgstr "ドライバーエラー: %s"

#, python-format
msgid "Duplicate networks (%s) are not allowed"
msgstr "ネットワークの重複 (%s) は許可されません"

msgid ""
"ERROR: Network commands are not supported when using the Neutron API.  Use "
"python-neutronclient instead."
msgstr ""
"エラー: Neutron API を使用する場合、ネットワークコマンドはサポートされませ"
"ん。代わりに python-neutronclient を使用してください。"

msgid ""
"ESX SOAP server returned an empty port group for the host system in its "
"response"
msgstr ""
"ESX SOAP サーバーが返した応答で、そのホストシステムのポートグループが空でした"

#, python-format
msgid "Ec2 id %(ec2_id)s is unacceptable."
msgstr "EC2 ID %(ec2_id)s は受け付けられません。"

#, python-format
msgid ""
"Either network uuid %(network_uuid)s is not present or is not assigned to "
"the project %(project_id)s."
msgstr ""
"ネットワーク UUID %(network_uuid)s が存在しないか、またはプロジェクト "
"%(project_id)s に割り当てられていません。"

#, python-format
msgid "Error attempting to run %(method)s"
msgstr "%(method)s を実行しようとしてエラーが発生しました"

#, python-format
msgid ""
"Error destroying the instance on node %(node)s. Provision state still "
"'%(state)s'."
msgstr ""
"インスタンスをノード %(node)s で破棄しているときにエラーが発生しました。プロ"
"ビジョニング状態は '%(state)s' です。"

#, python-format
msgid "Error during following call to agent: %(method)s"
msgstr "エージェントに対する %(method)s の呼び出し中に、エラーが発生しました"

#, python-format
msgid "Error during unshelve instance %(instance_id)s: %(reason)s"
msgstr "インスタンス %(instance_id)s の復元中のエラー: %(reason)s"

#, python-format
msgid ""
"Error from libvirt while getting domain info for %(instance_name)s: [Error "
"Code %(error_code)s] %(ex)s"
msgstr ""
"%(instance_name)s のドメイン情報を取得している際に、libvirt でエラーが発生し"
"ました: [エラーコード %(error_code)s] %(ex)s"

#, python-format
msgid ""
"Error from libvirt while looking up %(instance_id)s: [Error Code "
"%(error_code)s] %(ex)s"
msgstr ""
"%(instance_id)s の検索中に libvirt でエラーが発生しました: [エラーコード "
"%(error_code)s] %(ex)s"

#, python-format
msgid ""
"Error from libvirt while looking up %(instance_name)s: [Error Code "
"%(error_code)s] %(ex)s"
msgstr ""
"%(instance_name)s の検索中に libvirt でエラーが発生しました: [エラーコード "
"%(error_code)s] %(ex)s"

#, python-format
msgid ""
"Error from libvirt while quiescing %(instance_name)s: [Error Code "
"%(error_code)s] %(ex)s"
msgstr ""
"%(instance_name)s の正常終了中に libvirt でエラーが発生しました: [エラーコー"
"ド %(error_code)s] %(ex)s"

#, python-format
msgid ""
"Error from libvirt while set password for username \"%(user)s\": [Error Code "
"%(error_code)s] %(ex)s"
msgstr ""
"ユーザー名 \"%(user)s\" のパスワードの設定中に libvirt でエラーが発生しまし"
"た: [エラーコード %(error_code)s] %(ex)s"

#, python-format
msgid ""
"Error mounting %(device)s to %(dir)s in image %(image)s with libguestfs "
"(%(e)s)"
msgstr ""
"libguestfs (%(e)s) を使用してイメージ %(image)s の %(dir)s に %(device)s をマ"
"ウントする際にエラーが発生しました"

#, python-format
msgid "Error mounting %(image)s with libguestfs (%(e)s)"
msgstr ""
"libguestfs (%(e)s) を使用してイメージ %(image)s をマウントする際にエラーが発"
"生しました"

msgid "Error occurred while creating the verifier"
msgstr "ベリファイヤーの作成中にエラーが発生しました"

#, python-format
msgid "Error when creating resource monitor: %(monitor)s"
msgstr "リソースモニター %(monitor)s を作成するときにエラーが発生しました"

msgid "Error: Agent is disabled"
msgstr "エラー: エージェントは無効になっています"

#, python-format
msgid "Event %(event)s not found for action id %(action_id)s"
msgstr ""
"アクション ID %(action_id)s に対応するイベント %(event)s が見つかりません"

msgid "Event must be an instance of nova.virt.event.Event"
msgstr "イベントは nova.virt.event.Event のインスタンスでなければなりません"

#, python-format
msgid ""
"Exceeded max scheduling attempts %(max_attempts)d for instance "
"%(instance_uuid)s. Last exception: %(exc_reason)s"
msgstr ""
"インスタンス %(instance_uuid)s に関してスケジューリング可能な最大試行回数 "
"%(max_attempts)d を超えました。直近の例外: %(exc_reason)s"

#, python-format
msgid ""
"Exceeded max scheduling retries %(max_retries)d for instance "
"%(instance_uuid)s during live migration"
msgstr ""
"ライブマイグレーション時にインスタンス %(instance_uuid)s の最大スケジューリン"
"グ再試行回数 %(max_retries)d を超えました"

#, python-format
msgid "Exceeded maximum number of retries. %(reason)s"
msgstr "再試行の最大回数を超えました。%(reason)s"

#, python-format
msgid "Expected a uuid but received %(uuid)s."
msgstr "UUID が必要ですが、%(uuid)s を受け取りました。"

#, python-format
msgid "Expected object of type: %s"
msgstr "想定されるオブジェクトタイプ: %s"

#, python-format
msgid "Extra column %(table)s.%(column)s in shadow table"
msgstr "シャドーテーブルに余分なカラム %(table)s.%(column)s があります"

msgid "Extracting vmdk from OVA failed."
msgstr "OVA からの vmdk の取得に失敗しました。"

#, python-format
msgid "Failed to access port %(port_id)s: %(reason)s"
msgstr "ポート %(port_id)s へのアクセスに失敗しました: %(reason)s"

#, python-format
msgid "Failed to add bridge: %s"
msgstr "ブリッジ %s の追加に失敗しました"

#, python-format
msgid ""
"Failed to add deploy parameters on node %(node)s when provisioning the "
"instance %(instance)s"
msgstr ""
"インスタンス %(instance)s のプロビジョニング中に、ノード %(node)s でデプロイ"
"パラメーターを追加できませんでした。"

#, python-format
msgid "Failed to add interface: %s"
msgstr "インターフェースの追加に失敗しました: %s"

#, python-format
msgid "Failed to allocate the network(s) with error %s, not rescheduling."
msgstr ""
"エラー %s が発生したため、ネットワークを割り当てることができませんでした。再"
"スケジュールは行われません。"

msgid "Failed to allocate the network(s), not rescheduling."
msgstr ""
"ネットワークを割り当てることができませんでした。再スケジュールは行われませ"
"ん。"

#, python-format
msgid "Failed to attach network adapter device to %(instance_uuid)s"
msgstr ""
"ネットワークアダプターデバイスを %(instance_uuid)s に接続できませんでした"

#, python-format
msgid "Failed to create vif %s"
msgstr "vif %s の作成に失敗しました"

#, python-format
msgid "Failed to decrypt image file %(image_file)s: %(err)s"
msgstr "イメージファイル %(image_file)s の復号化に失敗しました: %(err)s"

#, python-format
msgid "Failed to decrypt initialization vector: %s"
msgstr "初期化ベクターの復号化に失敗しました: %s"

#, python-format
msgid "Failed to decrypt private key: %s"
msgstr "秘密鍵の復号化に失敗しました: %s"

#, python-format
msgid "Failed to decrypt text: %(reason)s"
msgstr "テキストの復号化に失敗しました: %(reason)s"

#, python-format
msgid "Failed to deploy instance: %(reason)s"
msgstr "インスタンスをデプロイできませんでした: %(reason)s"

#, python-format
msgid "Failed to detach PCI device %(dev)s: %(reason)s"
msgstr "PCI デバイス %(dev)s を切り離すことができませんでした: %(reason)s"

#, python-format
msgid "Failed to detach network adapter device from %(instance_uuid)s"
msgstr ""
"ネットワークアダプターデバイスを %(instance_uuid)s から切り離すことができませ"
"んでした"

#, python-format
msgid "Failed to encrypt text: %(reason)s"
msgstr "テキストの暗号化に失敗しました: %(reason)s"

#, python-format
msgid "Failed to launch instances: %(reason)s"
msgstr "インスタンスを起動できませんでした: %(reason)s"

#, python-format
msgid "Failed to map partitions: %s"
msgstr "パーティションのマッピングに失敗しました: %s"

#, python-format
msgid "Failed to mount filesystem: %s"
msgstr "ファイルシステム %s のマウントに失敗しました。"

msgid "Failed to parse information about a pci device for passthrough"
msgstr "パススルー用の PCI デバイスに関する情報の解析に失敗しました"

#, python-format
msgid "Failed to power off instance: %(reason)s"
msgstr "インスタンスの電源オフに失敗しました: %(reason)s"

#, python-format
msgid "Failed to power on instance: %(reason)s"
msgstr "インスタンスの電源オンに失敗しました: %(reason)s"

#, python-format
msgid ""
"Failed to prepare PCI device %(id)s for instance %(instance_uuid)s: "
"%(reason)s"
msgstr ""
"インスタンス %(instance_uuid)s 用に PCI デバイス %(id)s を準備できませんでし"
"た: %(reason)s"

#, python-format
msgid "Failed to provision instance %(inst)s: %(reason)s"
msgstr "インスタンス %(inst)s をプロビジョニングできませんでした: %(reason)s"

#, python-format
msgid "Failed to read or write disk info file: %(reason)s"
msgstr "ディスク情報ファイルの読み取りまたは書き込みに失敗しました: %(reason)s"

#, python-format
msgid "Failed to reboot instance: %(reason)s"
msgstr "インスタンスをリブートできませんでした: %(reason)s"

#, python-format
msgid "Failed to release IP %(address)s with MAC %(mac_address)s"
msgstr ""
"MAC アドレス %(mac_address)s) から IP アドレス %(address)s を解放できませんで"
"した"

#, python-format
msgid "Failed to remove volume(s): (%(reason)s)"
msgstr "ボリュームの削除に失敗しました: (%(reason)s)"

#, python-format
msgid "Failed to request Ironic to rebuild instance %(inst)s: %(reason)s"
msgstr ""
"インスタンス %(inst)s の再構築を Ironic に要求できませんでした: %(reason)s"

#, python-format
msgid "Failed to resume instance: %(reason)s"
msgstr "インスタンスの再開に失敗しました: %(reason)s"

#, python-format
msgid "Failed to revoke certificate for %(project_id)s"
msgstr "%(project_id)s の証明書の取り消しに失敗しました"

#, python-format
msgid "Failed to run qemu-img info on %(path)s : %(error)s"
msgstr "qemu-img info を %(path)s に対して実行できませんでした: %(error)s"

msgid "Failed to run xvp."
msgstr "xvp の実行に失敗しました。"

#, python-format
msgid "Failed to set admin password on %(instance)s because %(reason)s"
msgstr "%(instance)s で管理者パスワードの設定に失敗しました。理由: %(reason)s"

msgid "Failed to spawn, rolling back"
msgstr "起動に失敗しました。ロールバックしています"

#, python-format
msgid "Failed to suspend instance: %(reason)s"
msgstr "インスタンスを休止できませんでした: %(reason)s"

#, python-format
msgid "Failed to terminate instance: %(reason)s"
msgstr "インスタンスを削除できませんでした: %(reason)s"

#, python-format
msgid "Failed to unplug vif %s"
msgstr "vif %s の取り外しに失敗しました"

msgid "Failure prepping block device."
msgstr "ブロックデバイスを準備できませんでした"

#, python-format
msgid "File %(file_path)s could not be found."
msgstr "ファイル %(file_path)s が見つかりませんでした。"

#, python-format
msgid "File path %s not valid"
msgstr "ファイルパス %s は無効です"

#, python-format
msgid "Fixed IP %(address)s already exists."
msgstr "Fixed IP %(address)s が既に存在しています。"

#, python-format
msgid "Fixed IP %(ip)s is not a valid ip address for network %(network_id)s."
msgstr ""
"Fixed IP %(ip)s はネットワーク %(network_id)s の有効な IP アドレスではありま"
"せん。"

#, python-format
msgid "Fixed IP %s has been deleted"
msgstr "Fixed IP %s が削除されました"

#, python-format
msgid "Fixed IP %s is already in use."
msgstr "Fixed IP %s は既に使用中です。"

#, python-format
msgid "Fixed IP %s not found"
msgstr "Fixed IP %s が見つかりません"

#, python-format
msgid "Fixed IP %s not valid"
msgstr "Fixed IP %s は無効です"

#, python-format
msgid ""
"Fixed IP address %(address)s is already in use on instance %(instance_uuid)s."
msgstr ""
"Fixed IP アドレス %(address)s はインスタンス %(instance_uuid)s で既に使用され"
"ています。"

#, python-format
msgid "Fixed IP address %(address)s is invalid."
msgstr "Fixed IP アドレス %(address)s は無効です。"

#, python-format
msgid ""
"Fixed IP address (%(address)s) does not exist in network (%(network_uuid)s)."
msgstr ""
"Fixed IP アドレス (%(address)s) はネットワーク (%(network_uuid)s) 内に存在し"
"ません。"

#, python-format
msgid "Fixed IP associate failed for network: %(net)s."
msgstr "ネットワーク %(net)s に対する Fixed IP の割り当てが失敗しました。"

#, python-format
msgid "Fixed IP not found for address %(address)s."
msgstr " アドレス %(address)s に対応する Fixed IP が見つかりません。"

#, python-format
msgid "Flavor %(flavor_id)s could not be found."
msgstr "フレーバー %(flavor_id)s が見つかりませんでした。"

#, python-format
msgid "Flavor %(flavor_id)s has no extra specs with key %(extra_specs_key)s."
msgstr ""
"フレーバー %(flavor_id)s にはキー %(extra_specs_key)s を持つ追加スペックはあ"
"りません。"

#, python-format
msgid "Flavor %(flavor_id)s has no extra specs with key %(key)s."
msgstr ""
"フレーバー %(flavor_id)s にはキー %(key)s を持つ追加スペックはありません。"

#, python-format
msgid ""
"Flavor %(id)s extra spec cannot be updated or created after %(retries)d "
"retries."
msgstr ""
"%(retries)d 回の再試行の後では、フレーバー %(id)s の追加仕様の更新と作成を行"
"うことはできません。"

#, python-format
msgid ""
"Flavor access already exists for flavor %(flavor_id)s and project "
"%(project_id)s combination."
msgstr ""
"フレーバー %(flavor_id)s とプロジェクト %(project_id)s の組み合わせに対応する"
"フレーバーアクセスは既に存在します。"

#, python-format
msgid "Flavor access not found for %(flavor_id)s / %(project_id)s combination."
msgstr ""
"%(flavor_id)s / %(project_id)s の組み合わせに対応するフレーバーアクセスが見つ"
"かりません。"

msgid ""
"Flavor id can only contain letters from A-Z (both cases), periods, dashes, "
"underscores and spaces."
msgstr ""
"フレーバー ID に使用できるのは、A-Z の英字 (大文字および小文字)、ピリオド、"
"ダッシュ、アンダースコアー、および空白のみです。"

msgid ""
"Flavor names can only contain printable characters and horizontal spaces."
msgstr "フレーバー名には表示可能文字と空白文字のみを使用できます。"

msgid "Flavor used by the instance could not be found."
msgstr "インスタンスで使用されたフレーバーが見つかりませんでした"

#, python-format
msgid "Flavor with ID %(flavor_id)s already exists."
msgstr "ID %(flavor_id)s を持つフレーバーは既に存在します。"

#, python-format
msgid "Flavor with name %(flavor_name)s could not be found."
msgstr "名前が %(flavor_name)s のフレーバーが見つかりませんでした。"

#, python-format
msgid "Flavor with name %(name)s already exists."
msgstr "名前が %(name)s のフレーバーは既に存在します。"

#, python-format
msgid ""
"Flavor's disk is smaller than the minimum size specified in image metadata. "
"Flavor disk is %(flavor_size)i bytes, minimum size is %(image_min_disk)i "
"bytes."
msgstr ""
"フレーバーのディスクサイズがイメージのメタデータで指定された最小サイズよりも"
"小さくなっています。フレーバーディスクは %(flavor_size)i バイト、最小サイズ"
"は %(image_min_disk)i バイトです。"

#, python-format
msgid ""
"Flavor's disk is too small for requested image. Flavor disk is "
"%(flavor_size)i bytes, image is %(image_size)i bytes."
msgstr ""
"フレーバーのディスクサイズがリクエストされたイメージに対し小さすぎます。フ"
"レーバーディスクは %(flavor_size)i バイト、イメージは %(image_size)i バイトで"
"す。"

msgid "Flavor's memory is too small for requested image."
msgstr "フレーバーのメモリーは要求されたイメージに対して小さすぎます。"

#, python-format
msgid "Floating IP %(address)s already exists."
msgstr "Floating IP %(address)s は既に存在しています。"

#, python-format
msgid "Floating IP %(address)s association has failed."
msgstr "Floating IP %(address)s の割り当てに失敗しました。"

#, python-format
msgid "Floating IP %(address)s is associated."
msgstr "Floating IP %(address)s が割り当てられています。"

#, python-format
msgid "Floating IP %(address)s is not associated with instance %(id)s."
msgstr ""
"Floating IP %(address)s はインスタンス %(id)s に割り当てられていません。"

#, python-format
msgid "Floating IP %(address)s is not associated."
msgstr "Floating IP %(address)s は割り当てられていません。"

msgid "Floating IP allocate failed."
msgstr "Floating IP の確保に失敗しました。"

msgid "Floating IP is not associated"
msgstr "Floating IP が割り当てられていません"

#, python-format
msgid "Floating IP not found for ID %(id)s."
msgstr "ID %(id)s の Floating IP が見つかりません。"

#, python-format
msgid "Floating IP not found for ID %s"
msgstr "ID %s の Floating IP が見つかりません"

#, python-format
msgid "Floating IP not found for address %(address)s."
msgstr "アドレス %(address)s に対応する Floating IP が見つかりません。"

#, python-format
msgid "Floating IP not found for host %(host)s."
msgstr "ホスト %(host)s の Floating IP が見つかりません。"

msgid "Floating IP pool not found."
msgstr "Floating IP プールが見つかりません。"

msgid ""
"Forbidden to exceed flavor value of number of serial ports passed in image "
"meta."
msgstr ""
"イメージメタデータで渡されるシリアルポート数のフレーバー値を超えないようにし"
"てください。"

#, python-format
msgid "Found no PIF for device %s"
msgstr "デバイス %s に対応する PIF が見つかりませんでした"

msgid "Found no disk to snapshot."
msgstr "スナップショットの作成対象のディスクが見つかりません"

#, python-format
msgid "Found no network for bridge %s"
msgstr "ブリッジ %s に対するネットワークが存在しません。"

#, python-format
msgid "Found non-unique network for bridge %s"
msgstr "ブリッジ %s について一意でないネットワークが見つかりました"

#, python-format
msgid "Found non-unique network for name_label %s"
msgstr "name_label %s について一意でないネットワークが見つかりました"

#, python-format
msgid "Free %(type)s %(free).02f %(unit)s < requested %(requested)d %(unit)s"
msgstr ""
"空き %(type)s %(free).02f %(unit)s が要求された %(requested)d %(unit)s より少"
"ないです"

#, python-format
msgid "Glance image %(image_id)s is in unknown state - %(state)s"
msgstr "Glance イメージ %(image_id)s は不明な状態 %(state)s です。"

#, fuzzy, python-format
msgid "Glance image %s is in killed state"
msgstr "Glance イメージ %s は強制終了状態です"

#, python-format
msgid "Group not valid. Reason: %(reason)s"
msgstr "グループが無効です。理由: %(reason)s"

msgid "Guest does not have a console available."
msgstr "ゲストはコンソールを使用することはできません。"

#, python-format
msgid "Host %(host)s could not be found."
msgstr "ホスト %(host)s が見つかりませんでした。"

#, python-format
msgid "Host %(host)s is already mapped to cell %(uuid)s"
msgstr "ホスト %(host)s が既にセル %(uuid)s にマッピングされています"

#, python-format
msgid "Host '%(name)s' is not mapped to any cell"
msgstr "ホスト '%(name)s' がどのセルにもマッピングされません"

msgid "Host PowerOn is not supported by the Hyper-V driver"
msgstr "ホスト電源オンは Hyper-V ドライバーではサポートされていません"

msgid "Host aggregate is not empty"
msgstr "ホストアグリゲートが空ではありません"

msgid "Host does not support guests with NUMA topology set"
msgstr "ホストが NUMA トポロジーが設定されたゲストをサポートしていません"

msgid "Host does not support guests with custom memory page sizes"
msgstr ""
"ホストがカスタムのメモリーページサイズが指定されたゲストをサポートしていませ"
"ん"

msgid "Host startup on XenServer is not supported."
msgstr "XenServer 上でのホストの起動はサポートされていません。"

msgid "Hypervisor driver does not support post_live_migration_at_source method"
msgstr ""
"ハイパーバイザードライバーが post_live_migration_at_source メソッドをサポート"
"していません"

#, python-format
msgid "Hypervisor virt type '%s' is not valid"
msgstr "ハイバーバイザーの仮想化タイプ '%s' が有効ではありません"

#, python-format
msgid "Hypervisor virtualization type '%(hv_type)s' is not recognised"
msgstr "ハイパーバイザー仮想化タイプ '%(hv_type)s' は認識されていません"

#, python-format
msgid "Hypervisor with ID '%s' could not be found."
msgstr "ID '%s' のハイパーバイザーが見つかりませんでした。"

#, python-format
msgid "Hypervisor: %s"
msgstr "ハイパーバイザー: %s"

msgid "IP address"
msgstr "IP アドレス"

#, python-format
msgid "IP allocation over quota in pool %s."
msgstr "IP の割り当て量がプール %s 内のクォータを超えています。"

msgid "IP allocation over quota."
msgstr "IP の割り当て量がクォータを超えています。"

msgid "IPv4"
msgstr "IPv4"

msgid "IPv6"
msgstr "IPv6"

#, python-format
msgid "IPv6 netmask \"%s\" must be a netmask or integral prefix"
msgstr ""
"IPv6 ネットマスク「%s」はネットマスクまたは整数のプレフィックスでなければなり"
"ません"

#, python-format
msgid "Image %(image_id)s could not be found."
msgstr "イメージ %(image_id)s が見つかりませんでした。"

#, python-format
msgid "Image %(image_id)s is not active."
msgstr "イメージ %(image_id)s はアクティブではありません。"

#, python-format
msgid "Image %(image_id)s is unacceptable: %(reason)s"
msgstr "イメージ %(image_id)s は受け付けられません: %(reason)s"

msgid "Image disk size greater than requested disk size"
msgstr "イメージディスクが、要求されたディスクサイズよりも大きなサイズです"

msgid "Image is not raw format"
msgstr "イメージは raw 形式ではありません"

msgid "Image metadata key cannot be blank"
msgstr "イメージメタデータキーを空にすることはできません"

msgid "Image metadata key too long"
msgstr "イメージメタデータキーが長すぎます"

msgid "Image metadata limit exceeded"
msgstr "イメージメタデータ数の上限を超えました"

#, python-format
msgid "Image model '%(image)s' is not supported"
msgstr "イメージモデル '%(image)s' はサポートされません"

msgid "Image not found."
msgstr "イメージが見つかりません。"

#, python-format
msgid ""
"Image property '%(name)s' is not permitted to override NUMA configuration "
"set against the flavor"
msgstr ""
"イメージプロパティー '%(name)s' で、フレーバーに対して設定された NUMA 構成を"
"オーバーライドすることは許可されません"

msgid ""
"Image property 'hw_cpu_policy' is not permitted to override CPU pinning "
"policy set against the flavor"
msgstr ""
"イメージプロパティー 'hw_cpu_policy' はこのフレーバーでは設定されたCPU コア固"
"定ポリシーのオーバーライドを許可されていません"

msgid ""
"Image property 'hw_cpu_thread_policy' is not permitted to override CPU "
"thread pinning policy set against the flavor"
msgstr ""
"イメージプロパティー 'hw_cpu_thread_policy' は、フレーバーに設定された CPU ス"
"レッドの固定ポリシーを上書きすることはできません。"

msgid "Image that the instance was started with could not be found."
msgstr "インスタンスの起動時に使用されたイメージが見つかりませんでした。"

#, python-format
msgid ""
"Image vCPU limits %(sockets)d:%(cores)d:%(threads)d exceeds permitted "
"%(maxsockets)d:%(maxcores)d:%(maxthreads)d"
msgstr ""
"イメージの vCPU 上限 %(sockets)d:%(cores)d:%(threads)d が、許可されている "
"%(maxsockets)d:%(maxcores)d:%(maxthreads)d を超えています"

#, python-format
msgid ""
"Image vCPU topology %(sockets)d:%(cores)d:%(threads)d exceeds permitted "
"%(maxsockets)d:%(maxcores)d:%(maxthreads)d"
msgstr ""
"イメージの vCPU トポロジー %(sockets)d:%(cores)d:%(threads)d が、許可されてい"
"る %(maxsockets)d:%(maxcores)d:%(maxthreads)d を超えています"

#, python-format
msgid "Image's config drive option '%(config_drive)s' is invalid"
msgstr "イメージのコンフィグドライブのオプション '%(config_drive)s' は無効です"

msgid ""
"Images with destination_type 'volume' need to have a non-zero size specified"
msgstr ""
"destination_type 'volume' を含むイメージには、ゼロ以外のサイズが指定されてい"
"る必要があります"

msgid "In ERROR state"
msgstr "エラー状態です"

msgid "In Use"
msgstr "使用中"

#, python-format
msgid "In states %(vm_state)s/%(task_state)s, not RESIZED/None"
msgstr "状態は %(vm_state)s/%(task_state)s です。RESIZED/None ではありません"

#, python-format
msgid "In-progress live migration %(id)s is not found for server %(uuid)s."
msgstr ""
"サーバー %(uuid)s で進行中のライブマイグレーション %(id)s が見つかりません。"

msgid ""
"Incompatible settings: ephemeral storage encryption is supported only for "
"LVM images."
msgstr ""
"設定に互換性がありません:  一時ストレージ暗号化は LVM イメージでのみサポート"
"されています。"

#, python-format
msgid "Inconsistency in cell routing: %(reason)s"
msgstr "セルルーティングの不整合: %(reason)s"

#, python-format
msgid "Info cache for instance %(instance_uuid)s could not be found."
msgstr ""
"インスタンス %(instance_uuid)s 用の情報キャッシュが見つかりませんでした。"

#, python-format
msgid ""
"Instance %(instance)s and volume %(vol)s are not in the same "
"availability_zone. Instance is in %(ins_zone)s. Volume is in %(vol_zone)s"
msgstr ""
"インスタンス %(instance)s とボリューム %(vol)s は同じアベイラビリティーゾーン"
"にありません。インスタンスは %(ins_zone)s に、ボリュームは %(vol_zone)s にあ"
"ります"

#, python-format
msgid "Instance %(instance)s does not have a port with id %(port)s"
msgstr "インスタンス %(instance)s に ID %(port)s のポートがありません"

#, python-format
msgid "Instance %(instance_id)s cannot be rescued: %(reason)s"
msgstr "インスタンス %(instance_id)s をレスキューできません: %(reason)s"

#, python-format
msgid "Instance %(instance_id)s could not be found."
msgstr "インスタンス %(instance_id)s が見つかりませんでした。"

#, python-format
msgid "Instance %(instance_id)s has no tag '%(tag)s'"
msgstr "インスタンス %(instance_id)s にタグ \"%(tag)s\" がありません"

#, python-format
msgid "Instance %(instance_id)s is not in rescue mode"
msgstr "インスタンス %(instance_id)s はレスキューモードではありません。"

#, python-format
msgid "Instance %(instance_id)s is not ready"
msgstr "インスタンス %(instance_id)s の準備ができていません"

#, python-format
msgid "Instance %(instance_id)s is not running."
msgstr "インスタンス %(instance_id)s は実行されていません。"

#, python-format
msgid "Instance %(instance_id)s is unacceptable: %(reason)s"
msgstr "インスタンス %(instance_id)s は受け付けられません: %(reason)s"

#, python-format
msgid "Instance %(instance_uuid)s does not specify a NUMA topology"
msgstr "インスタンス %(instance_uuid)s で NUMA トポロジーが指定されていません"

#, python-format
msgid "Instance %(instance_uuid)s does not specify a migration context."
msgstr ""
"インスタンス %(instance_uuid)s がマイグレーションのコンテキストを設定していま"
"せん。"

#, python-format
msgid "Instance %(instance_uuid)s doesn't have fixed IP '%(ip)s'."
msgstr "インスタンス %(instance_uuid)s に Fixed IP '%(ip)s' がありません。"

#, python-format
msgid "Instance %(instance_uuid)s has zero fixed IPs."
msgstr "インスタンス %(instance_uuid)s に Fixed IP がありません。"

#, python-format
msgid ""
"Instance %(instance_uuid)s in %(attr)s %(state)s. Cannot %(method)s while "
"the instance is in this state."
msgstr ""
"インスタンス %(instance_uuid)s は %(attr)s %(state)s 状態です。インスタンスが"
"この状態にある間は %(method)s を行えません。"

#, python-format
msgid "Instance %(instance_uuid)s is locked"
msgstr "インスタンス %(instance_uuid)s はロックされています"

#, python-format
msgid ""
"Instance %(instance_uuid)s requires config drive, but it does not exist."
msgstr ""
"インスタンス %(instance_uuid)s にはコンフィグドライブが必要ですが、存在しませ"
"ん。"

#, python-format
msgid "Instance %(name)s already exists."
msgstr "インスタンス %(name)s は既に存在します。"

#, python-format
msgid "Instance %(server_id)s is in an invalid state for '%(action)s'"
msgstr ""
"インスタンス %(server_id)s は '%(action)s' が実行できない状態にあります"

#, python-format
msgid "Instance %(uuid)s has no mapping to a cell."
msgstr "インスタンス %(uuid)s にはセルに対するマッピングがありません。"

#, python-format
msgid "Instance %s is not attached."
msgstr "インスタンス %s が接続されていません。"

#, python-format
msgid "Instance %s not found"
msgstr "インスタンス %s が見つかりません"

#, python-format
msgid "Instance %s provisioning was aborted"
msgstr "インスタンス %s のプロビジョニングが中止しました。"

msgid "Instance could not be found"
msgstr "インスタンスが見つかりませんでした"

msgid "Instance disk to be encrypted but no context provided"
msgstr ""
"インスタンスディスクの暗号化が必要ですが、コンテキストが指定されていません。"

msgid "Instance event failed"
msgstr "インスタンスイベントが失敗しました"

#, python-format
msgid "Instance group %(group_uuid)s already exists."
msgstr "インスタンスグループ %(group_uuid)s は既に存在します。"

#, python-format
msgid "Instance group %(group_uuid)s could not be found."
msgstr "インスタンスグループ %(group_uuid)s が見つかりませんでした。"

#, python-format
msgid "Instance group %(group_uuid)s has no member with id %(instance_id)s."
msgstr ""
"インスタンスグループ %(group_uuid)s には、ID %(instance_id)s を持つメンバーは"
"存在しません。"

#, python-format
msgid "Instance group %(group_uuid)s has no policy %(policy)s."
msgstr ""
"インスタンスグループ %(group_uuid)s にはポリシー %(policy)s はありません。"

#, fuzzy
msgid "Instance has no source host"
msgstr "インスタンスにソースホストがありません"

msgid "Instance has not been resized."
msgstr "インスタンスのサイズ変更が行われていません"

#, python-format
msgid "Instance hostname %(hostname)s is not a valid DNS name"
msgstr "インスタンスのホスト名 %(hostname)s は有効な DNS 名ではありません。"

#, python-format
msgid "Instance is already in Rescue Mode: %s"
msgstr "インスタンスは既にレスキューモードです: %s"

msgid "Instance is not a member of specified network"
msgstr "インスタンスは指定されたネットワークのメンバーではありません"

msgid "Instance recreate is not supported."
msgstr "インスタンスの再作成はサポートされていません。"

#, python-format
msgid "Instance rollback performed due to: %s"
msgstr "インスタンスのロールバックが実行されました。原因: %s"

msgid "Instance snapshots are not permitted at this time."
msgstr "現在、インスタンスのスナップショット作成は許可されていません。"

#, python-format
msgid ""
"Insufficient Space on Volume Group %(vg)s. Only %(free_space)db available, "
"but %(size)d bytes required by volume %(lv)s."
msgstr ""
"ボリュームグループ %(vg)s に十分なスペースがありません。使用可能なのは "
"%(free_space)db のみですが、ボリューム %(lv)s には %(size)d バイト必要です。"

#, python-format
msgid "Insufficient compute resources: %(reason)s."
msgstr "コンピュートリソースが不十分です: %(reason)s。"

#, python-format
msgid "Insufficient free memory on compute node to start %(uuid)s."
msgstr ""
"コンピュートノードには %(uuid)s を開始するための十分な空きメモリーがありませ"
"ん。"

#, python-format
msgid "Interface %(interface)s not found."
msgstr "インターフェース %(interface)s が見つかりません。"

#, python-format
msgid "Invalid Base 64 data for file %(path)s"
msgstr "ファイル %(path)s の Base64 データが無効です"

msgid "Invalid Connection Info"
msgstr "無効な接続情報"

#, python-format
msgid "Invalid ID received %(id)s."
msgstr "無効な ID %(id)s を受信しました。"

#, python-format
msgid "Invalid IP format %s"
msgstr "%s は無効な IP 形式です"

#, python-format
msgid "Invalid IP protocol %(protocol)s."
msgstr "無効な IP プロトコル %(protocol)s。"

#, python-format
msgid ""
"Invalid PCI Whitelist: The PCI address %(address)s has an invalid %(field)s."
msgstr ""
"無効な PCI ホワイトリスト: PCI アドレス %(address)s に無効な %(field)s が含ま"
"れています。"

msgid ""
"Invalid PCI Whitelist: The PCI whitelist can specify devname or address, but "
"not both"
msgstr ""
"無効な PCI ホワイトリスト: PCI ホワイトリストでは devname またはアドレスを指"
"定できますが、両方を指定することはできません"

#, python-format
msgid "Invalid PCI alias definition: %(reason)s"
msgstr "PCI エイリアス定義が無効です: %(reason)s"

#, python-format
msgid "Invalid PCI devices Whitelist config %(reason)s"
msgstr "PCI デバイスのホワイトリスト設定が無効です: %(reason)s"

#, python-format
msgid "Invalid Regular Expression %s"
msgstr "正規表現 %s は無効です"

msgid "Invalid association."
msgstr "無効な関連付けです。"

#, python-format
msgid "Invalid broker_hosts value: %s. It should be in hostname:port format"
msgstr ""
"broker_hosts 値 %s が無効です。hostname:port の形式でなければなりません"

#, python-format
msgid "Invalid certificate format: %s"
msgstr "無効な証明書の形式: %s"

msgid "Invalid changes-since value"
msgstr "changes-since の値が無効です"

#, python-format
msgid "Invalid characters in hostname '%(hostname)s'"
msgstr "ホスト名 '%(hostname)s' に無効な文字があります"

msgid "Invalid config_drive provided."
msgstr "無効な config_drive が指定されました。"

#, python-format
msgid "Invalid config_drive_format \"%s\""
msgstr "無効な config_drive_format \"%s\""

#, python-format
msgid "Invalid console type %(console_type)s"
msgstr "無効なコンソールタイプ %(console_type)s"

#, python-format
msgid "Invalid content type %(content_type)s."
msgstr "無効なコンテンツ形式 %(content_type)s。"

#, python-format
msgid "Invalid datetime string: %(reason)s"
msgstr "日時の文字列が無効です: %(reason)s"

msgid "Invalid device UUID."
msgstr "デバイス UUID が無効です。"

#, python-format
msgid "Invalid entry: '%s'"
msgstr "項目 '%s' は無効です"

#, python-format
msgid "Invalid entry: '%s'; Expecting dict"
msgstr "項目 '%s' は無効です。辞書型が期待されています"

#, python-format
msgid "Invalid entry: '%s'; Expecting list or dict"
msgstr "項目 '%s' は無効です。リストまたは辞書型が期待されています"

#, python-format
msgid "Invalid exclusion expression %r"
msgstr "排他式 %r は無効です"

#, python-format
msgid "Invalid field name: %s"
msgstr "フィールド名が無効です: %s"

#, python-format
msgid "Invalid fixed IP Address %s in request"
msgstr "リクエストに無効な Fixed IP アドレス %s が含まれています"

#, python-format
msgid "Invalid floating IP %s in request"
msgstr "リクエストに無効な Floating IP %s が含まれています"

#, python-format
msgid "Invalid id: %(instance_id)s (expecting \"i-...\")"
msgstr "無効な ID: %(instance_id)s (\"i-...\" が期待されています)"

#, python-format
msgid "Invalid id: %(volume_id)s (expecting \"i-...\")"
msgstr "無効な ID: %(volume_id)s (\"i-...\" が期待されています)"

#, python-format
msgid "Invalid image format '%(format)s'"
msgstr "イメージ形式 '%(format)s' は無効です"

#, python-format
msgid "Invalid image href %(image_href)s."
msgstr "無効なイメージ href %(image_href)s。"

msgid "Invalid image metadata"
msgstr "イメージメタデータが無効です"

#, python-format
msgid "Invalid inclusion expression %r"
msgstr "包含式 %r は無効です"

#, python-format
msgid ""
"Invalid input for field/attribute %(path)s. Value: %(value)s. %(message)s"
msgstr "フィールド/属性 %(path)s の入力が無効です。値: %(value)s。%(message)s"

#, python-format
msgid "Invalid input received: %(reason)s"
msgstr "無効な入力を受信しました: %(reason)s"

msgid "Invalid instance image."
msgstr "インスタンスイメージが無効です。"

#, python-format
msgid "Invalid is_public filter [%s]"
msgstr "無効な is_public フィルター [%s]"

msgid "Invalid key_name provided."
msgstr "無効な key_name が指定されました。"

#, python-format
msgid "Invalid libvirt version %(version)s"
msgstr "libvirt のバージョン %(version)s が無効です"

#, python-format
msgid "Invalid memory page size '%(pagesize)s'"
msgstr "メモリーページサイズ \"%(pagesize)s\" が無効です"

msgid "Invalid metadata key"
msgstr "無効なメタデータキーです"

#, python-format
msgid "Invalid metadata size: %(reason)s"
msgstr "無効なメタデータサイズ: %(reason)s"

#, python-format
msgid "Invalid metadata: %(reason)s"
msgstr "メタデータが無効です: %(reason)s"

#, python-format
msgid "Invalid minDisk filter [%s]"
msgstr "無効な minDisk フィルター [%s]"

#, python-format
msgid "Invalid min_ram filter [%s]"
msgstr "無効な min_ram フィルター [%s]"

msgid "Invalid name"
msgstr "無効な名前"

#, python-format
msgid "Invalid port range %(from_port)s:%(to_port)s. %(msg)s"
msgstr "無効なポート範囲 %(from_port)s:%(to_port)s。 %(msg)s"

#, python-format
msgid "Invalid port value: %s. It should be an integer"
msgstr "ポート値 %s が無効です。整数でなければなりません"

#, python-format
msgid "Invalid port value: %s. Should be an integer"
msgstr "ポート値 %s が無効です。整数でなければなりません"

msgid "Invalid proxy request signature."
msgstr "無効なプロキシー要求シグニチャー"

#, python-format
msgid "Invalid public key type for signature key type: %s"
msgstr "シグニチャーの鍵タイプの無効な公開鍵: %s"

#, python-format
msgid "Invalid range expression %r"
msgstr "範囲式 %r は無効です"

#, python-format
msgid "Invalid reservation expiration %(expire)s."
msgstr "予約の有効期限 %(expire)s が無効です。"

#, python-format
msgid "Invalid security group name: %(name)s."
msgstr "セキュリティーグループ名が無効です: %(name)s。"

msgid "Invalid service catalog json."
msgstr "無効なサービスカタログ JSON。"

#, python-format
msgid "Invalid signature hash method: %s"
msgstr "無効なシグニチャーハッシュメソッド: %s"

#, python-format
msgid "Invalid signature key type: %s"
msgstr "無効なシグニチャーの鍵タイプ: %s"

msgid "Invalid source_type field."
msgstr "無効な source_type フィールドです。"

msgid "Invalid start time. The start time cannot occur after the end time."
msgstr "無効な開始時刻。開始時刻を終了時刻より後にすることはできません。"

msgid "Invalid state of instance files on shared storage"
msgstr "共有ストレージ上のインスタンスファイルの無効な状態"

msgid "Invalid target_lun"
msgstr "無効な target_lun"

#, python-format
msgid "Invalid timestamp for date %s"
msgstr "日付 %s のタイムスタンプが無効です"

#, python-format
msgid "Invalid type for %s"
msgstr "%s のタイプが無効です"

#, python-format
msgid "Invalid type for %s entry"
msgstr "%s 項目のタイプが無効です"

#, python-format
msgid "Invalid usage_type: %s"
msgstr "usage_type %s は無効です"

#, python-format
msgid "Invalid value for Config Drive option: %(option)s"
msgstr "コンフィグドライブのオプション %(option)s の値が無効です"

#, python-format
msgid ""
"Invalid vcpu_pin_set config, one or more of the specified cpuset is not "
"online. Online cpuset(s): %(online)s, requested cpuset(s): %(req)s"
msgstr ""
"vcpu_pin_set の設定が無効です。指定された CPU セットのうち 1 つ以上がオンライ"
"ン状態にありません。オンラインの CPU セット: %(online)s、リクエストされた "
"CPU セット: %(req)s"

msgid "Invalid vcpu_pin_set config, out of hypervisor cpu range."
msgstr "vcpu_pin_set 設定が無効です。ハイパーバイザーの CPU の範囲外です。"

#, python-format
msgid "Invalid virtual interface address %s in request"
msgstr "リクエストに無効な仮想インターフェースアドレス %s があります"

#, python-format
msgid "Invalid volume access mode: %(access_mode)s"
msgstr "ボリュームアクセスモードが無効です: %(access_mode)s"

msgid "Invalid volume source data"
msgstr "無効なボリュームソースデータ"

#, python-format
msgid "Invalid volume: %(reason)s"
msgstr "無効なボリューム: %(reason)s"

msgid "Invalid volume_size."
msgstr "volume_size が無効です。"

#, python-format
msgid "Ironic node uuid not supplied to driver for instance %s."
msgstr ""
"Ironic ノード uuid が、インスタンス %s のドライバーに提供されていません。"

#, python-format
msgid ""
"Ironic node: %(id)s failed to validate. (deploy: %(deploy)s, power: "
"%(power)s)"
msgstr ""
"Ironic ノード %(id)s を検証できませんでした。(デプロイ: %(deploy)s、電源: "
"%(power)s)"

msgid "Is the appropriate service running?"
msgstr "適切なサービスが実行されていますか?"

#, python-format
msgid ""
"It is not allowed to create an interface on external network %(network_uuid)s"
msgstr ""
"外部ネットワーク %(network_uuid)s でインターフェースを作成することは許可され"
"ていません"

#, python-format
msgid ""
"Kernel/Ramdisk image is too large: %(vdi_size)d bytes, max %(max_size)d bytes"
msgstr ""
"カーネルイメージ/RAM ディスクイメージが大きすぎます: %(vdi_size)d バイト、最"
"大値は %(max_size)d バイト"

msgid ""
"Key Names can only contain alphanumeric characters, periods, dashes, "
"underscores, colons and spaces."
msgstr ""
"キー名に使用できるのは、英数字、ピリオド、ダッシュ、アンダースコアー、コロ"
"ン、および空白のみです。"

#, python-format
msgid "Key manager error: %(reason)s"
msgstr "鍵マネージャーエラー: %(reason)s"

#, python-format
msgid "Key pair '%(key_name)s' already exists."
msgstr "キーペア '%(key_name)s' は既に存在します。"

#, python-format
msgid "Keypair %(name)s not found for user %(user_id)s"
msgstr "ユーザー %(user_id)s のキーペア %(name)s が見つかりません"

#, python-format
msgid "Keypair data is invalid: %(reason)s"
msgstr "キーペアデータが無効です: %(reason)s"

msgid "Keypair name contains unsafe characters"
msgstr "キーペア名に安全ではない文字が含まれています"

msgid "Keypair name must be string and between 1 and 255 characters long"
msgstr "キーペア名は 1 から 255 文字の長さの文字列でなければなりません"

#, python-format
msgid "Last %s nova syslog entries:-"
msgstr "最後の %s nova syslog 項目:-"

msgid "Limit"
msgstr "上限値"

msgid "Limits only supported from vCenter 6.0 and above"
msgstr "上限が適用されるのは、vCenter 6.0 以降の場合のみです。"

#, python-format
msgid "Line %(linenum)d : %(line)s"
msgstr "行 %(linenum)d : %(line)s"

#, python-format
msgid "Link Local address is not found.:%s"
msgstr "リンクローカルアドレスが見つかりません: %s"

msgid "Listing virtual interfaces is not supported by this cloud."
msgstr "このクラウドでは仮想インターフェースの一覧表示を行うことができません。"

#, python-format
msgid "Live migration %(id)s for server %(uuid)s is not in progress."
msgstr "サーバー %(uuid)s のマイグレーション %(id)s は進行中ではありません。"

msgid ""
"Live migration can not be used without shared storage except a booted from "
"volume VM which does not have a local disk."
msgstr ""
"ローカルディスクを持たないボリューム VM から起動する場合を除いて、共有スト"
"レージなしにはライブマイグレーションを行うことはできません。"

msgid ""
"Live migration of instances with config drives is not supported in libvirt "
"unless libvirt instance path and drive data is shared across compute nodes."
msgstr ""
"コンフィグドライブを使用したインスタンスのライブマイグレーションは、 libvirt "
"のインスタンスパスとドライブデータがコンピュートノード間で共有されていない限"
"り、libvirt ではサポートされません。"

msgid ""
"Live migration with API v2.25 requires all the Mitaka upgrade to be complete "
"before it is available."
msgstr ""
"API v2.25 でライブマイグレーションを行うには、実行前にすべての Mitaka を更新"
"する必要があります。"

#, python-format
msgid "Malformed message body: %(reason)s"
msgstr "メッセージ本文の形式に誤りがあります: %(reason)s"

#, python-format
msgid ""
"Malformed request URL: URL's project_id '%(project_id)s' doesn't match "
"Context's project_id '%(context_project_id)s'"
msgstr ""
"誤った形式のリクエスト URL です。URL の project_id '%(project_id)s' がコンテ"
"キストの project_id '%(context_project_id)s' と一致しません"

msgid "Malformed request body"
msgstr "誤った形式のリクエスト本文"

msgid "Mapping image to local is not supported."
msgstr "ローカルへのイメージマッピングはサポートしていません。"

#, python-format
msgid "Marker %(marker)s could not be found."
msgstr "マーカー %(marker)s が見つかりませんでした。"

msgid "Maximum allowed length for 'label' is 255."
msgstr "'label' の許容最大長は 255 です。"

msgid "Maximum number of fixed IPs exceeded"
msgstr "Fixed IP の最大数を超えました"

msgid "Maximum number of floating IPs exceeded"
msgstr "Floating IP の最大数を超えました"

msgid "Maximum number of key pairs exceeded"
msgstr "キーペアの最大数を超えました"

#, python-format
msgid "Maximum number of metadata items exceeds %(allowed)d"
msgstr "メタデータ項目の最大数が %(allowed)d を超えています"

msgid "Maximum number of ports exceeded"
msgstr "最大ポート数を超えました"

msgid "Maximum number of security groups or rules exceeded"
msgstr "セキュリティーグループまたはルールの最大数を超えました"

msgid "Metadata item was not found"
msgstr "メタデータ項目が見つかりませんでした"

msgid "Metadata property key greater than 255 characters"
msgstr "メタデータプロパティーのキーが 255 文字を超えています"

msgid "Metadata property value greater than 255 characters"
msgstr "メタデータプロパティーの値が 255 文字を超えています"

msgid "Metadata type should be dict."
msgstr "メタデータタイプは dict でなければなりません。"

#, python-format
msgid ""
"Metric %(name)s could not be found on the compute host node %(host)s."
"%(node)s."
msgstr ""
"コンピュートホストノード %(host)s.%(node)s では、メトリック %(name)s は見つか"
"りませんでした。"

msgid "Migrate Receive failed"
msgstr "マイグレーションの受け取りが失敗しました"

msgid "Migrate Send failed"
msgstr "マイグレーションの送信が失敗しました"

#, python-format
msgid "Migration %(id)s for server %(uuid)s is not live-migration."
msgstr ""
"サーバー %(uuid)s のマイグレーション %(id)s はライブマイグレーションではあり"
"ません。"

#, python-format
msgid "Migration %(migration_id)s could not be found."
msgstr "マイグレーション %(migration_id)s が見つかりませんでした。"

#, python-format
msgid "Migration %(migration_id)s not found for instance %(instance_id)s"
msgstr ""
"インスタンス %(instance_id)s でマイグレーション %(migration_id)s が見つかりま"
"せん"

#, python-format
msgid ""
"Migration %(migration_id)s state of instance %(instance_uuid)s is %(state)s. "
"Cannot %(method)s while the migration is in this state."
msgstr ""
"インスタンス %(instance_uuid)s のマイグレーション %(migration_id)s の状態が "
"%(state)s です。マイグレーションがこの状態にある場合、%(method)s を実行できま"
"せん。"

#, python-format
msgid "Migration error: %(reason)s"
msgstr "マイグレーションエラー: %(reason)s"

msgid "Migration is not supported for LVM backed instances"
msgstr ""
"マイグレーションは LVM 形式のイメージを使用するインスタンスではサポートされて"
"いません"

#, python-format
msgid ""
"Migration not found for instance %(instance_id)s with status %(status)s."
msgstr ""
"状態が %(status)s のインスタンス %(instance_id)s のマイグレーションが見つかり"
"ません。"

#, python-format
msgid "Migration pre-check error: %(reason)s"
msgstr "マイグレーション事前検査エラー: %(reason)s"

#, python-format
msgid "Migration select destinations error: %(reason)s"
msgstr "マイグレーション先の選択エラー: %(reason)s"

#, python-format
msgid "Missing arguments: %s"
msgstr "引数 %s がありません"

#, python-format
msgid "Missing column %(table)s.%(column)s in shadow table"
msgstr "シャドーテーブルにカラム %(table)s.%(column)s がありません"

msgid "Missing device UUID."
msgstr "デバイス UUID がありません。"

msgid "Missing disabled reason field"
msgstr "「無効化の理由」フィールドがありません"

msgid "Missing forced_down field"
msgstr "forced_down フィールドがありません"

msgid "Missing imageRef attribute"
msgstr "imageRef 属性が指定されていません"

#, python-format
msgid "Missing keys: %s"
msgstr "キーがありません: %s"

#, python-format
msgid "Missing parameter %s"
msgstr "パラメーター %s が欠落しています"

msgid "Missing parameter dict"
msgstr "パラメーター dict が指定されていません"

#, python-format
msgid ""
"More than one instance is associated with fixed IP address '%(address)s'."
msgstr ""
"複数のインスタンスが Fixed IP アドレス '%(address)s' に割り当てられています。"

msgid ""
"More than one possible network found. Specify network ID(s) to select which "
"one(s) to connect to."
msgstr ""
"複数の使用可能なネットワークが見つかりました。接続先のネットワークを選択する"
"には、ネットワーク ID を指定してください。"

msgid "More than one swap drive requested."
msgstr "複数のスワップドライブが要求されました。"

#, python-format
msgid "Multi-boot operating system found in %s"
msgstr "%s 内にブート可能なオペレーティングシステムが複数見つかりました"

msgid "Multiple X-Instance-ID headers found within request."
msgstr "リクエストに複数の X-Instance-ID ヘッダーが検出されました。"

msgid "Multiple X-Tenant-ID headers found within request."
msgstr "リクエストに複数の X-Tenant-ID ヘッダーが検出されました。"

#, python-format
msgid "Multiple floating IP pools matches found for name '%s'"
msgstr "名前が '%s' の Floating IP プールが複数見つかりました"

#, python-format
msgid "Multiple floating IPs are found for address %(address)s."
msgstr "アドレス %(address)s に対して複数の Floating IP が見つかりました。"

msgid ""
"Multiple hosts may be managed by the VMWare vCenter driver; therefore we do "
"not return uptime for just one host."
msgstr ""
"複数のホストが VMWare vCenter ドライバーによって管理されている可能性がありま"
"す。このため ホスト単位の稼働時間は返しません。"

msgid "Multiple possible networks found, use a Network ID to be more specific."
msgstr ""
"使用可能なネットワークが複数見つかりました。ネットワーク ID を具体的に指定し"
"てください。"

#, python-format
msgid ""
"Multiple security groups found matching '%s'. Use an ID to be more specific."
msgstr ""
"'%s' に一致するセキュリティーグループが複数見つかりました。より具体的な ID を"
"使用してください。"

msgid "Must input network_id when request IP address"
msgstr "IP アドレスを要求するときは、network_id を入力する必要があります"

msgid "Must not input both network_id and port_id"
msgstr "network_id と port_id の両方を入力しないでください"

msgid ""
"Must specify connection_url, connection_username (optionally), and "
"connection_password to use compute_driver=xenapi.XenAPIDriver"
msgstr ""
"compute_driver=xenapi.XenAPIDriver を使用するには、connection_url、"
"connection_username (オプション)、および connection_password を指定する必要が"
"あります"

msgid ""
"Must specify host_ip, host_username and host_password to use vmwareapi."
"VMwareVCDriver"
msgstr ""
"vmwareapi.VMwareVCDriver を使用するためのホスト IP、ユーザー名、ホストパス"
"ワードを指定する必要があります"

msgid "Must supply a positive value for max_number"
msgstr "max_number には正の値を指定する必要があります"

msgid "Must supply a positive value for max_rows"
msgstr "max_rows には正の値を指定する必要があります"

#, python-format
msgid "Network \"%(val)s\" is not valid in field %(attr)s"
msgstr "ネットワーク \"%(val)s\" のフィールド %(attr)s が有効ではありません"

#, python-format
msgid "Network %(network_id)s could not be found."
msgstr "ネットワーク %(network_id)s が見つかりませんでした。"

#, python-format
msgid "Network %(network_id)s is duplicated."
msgstr "ネットワーク %(network_id)s が重複しています。"

#, python-format
msgid "Network %(network_id)s is still in use."
msgstr "ネットワーク %(network_id)s はまだ使用中です。"

#, python-format
msgid ""
"Network %(network_uuid)s requires a subnet in order to boot instances on."
msgstr ""
"ネットワーク %(network_uuid)s でインスタンスをブートするには、サブネットが必"
"要です。"

#, python-format
msgid "Network adapter %(adapter)s could not be found."
msgstr "ネットワークアダプター %(adapter)s が見つかりませんでした。"

#, python-format
msgid "Network could not be found for bridge %(bridge)s"
msgstr "ブリッジ %(bridge)s のネットワークが見つかりませんでした"

#, python-format
msgid "Network could not be found for instance %(instance_id)s."
msgstr "インスタンス %(instance_id)s のネットワークが見つかりませんでした。"

#, python-format
msgid "Network could not be found for uuid %(uuid)s"
msgstr "UUID %(uuid)s のネットワークが見つかりませんでした"

#, python-format
msgid "Network could not be found with cidr %(cidr)s."
msgstr "CIDR が %(cidr)s のネットワークが見つかりませんでした。"

msgid "Network driver does not support this function."
msgstr "ネットワークドライバーではこの関数はサポートされません。"

#, python-format
msgid "Network host %(host)s has zero fixed IPs in network %(network_id)s."
msgstr ""
"ネットワーク %(network_id)s 上で、ネットワークホスト %(host)s に Fixed IP が"
"ありません。"

#, python-format
msgid ""
"Network must be disassociated from project %(project_id)s before it can be "
"deleted."
msgstr ""
"このネットワークを削除するには、プロジェクト %(project_id)s との関連付けを解"
"除する必要があります。"

msgid "Network not found"
msgstr "ネットワークが見つかりません"

msgid ""
"Network requires port_security_enabled and subnet associated in order to "
"apply security groups."
msgstr ""
"セキュリティーグループを適用するには、ネットワークが port_security_enabled に"
"なっていて、サブネットが関連付けられている必要があります。"

#, python-format
msgid "Network set host failed for network %(network_id)s."
msgstr ""
"ネットワーク %(network_id)s においてネットワークが設定したホストで障害が発生"
"しました。"

msgid "New volume must be detached in order to swap."
msgstr "スワップを行うには、新規ボリュームを切断する必要があります。"

msgid "New volume must be the same size or larger."
msgstr "新規ボリュームは同じサイズか、それ以上でなければなりません。"

#, python-format
msgid "No Block Device Mapping with id %(id)s."
msgstr "ID %(id)s を持つブロックデバイスマッピングがありません。"

#, python-format
msgid "No CPUs available after parsing %r"
msgstr "%r の解釈を行ったところ、使用可能な CPU はありません"

msgid "No Unique Match Found."
msgstr "1 つだけ一致するデータが見つかりません。"

msgid "No access_url in connection_info. Cannot validate protocol"
msgstr ""
"connection_info に access_url がありません。プロトコルを検証できません。"

#, python-format
msgid "No agent-build associated with id %(id)s."
msgstr "ID %(id)s に関連付けられたエージェントビルドはありません。"

msgid "No cell given in routing path."
msgstr "ルーティングパスにセルが指定されていません。"

msgid "No cells available matching scheduling criteria."
msgstr "スケジューリング基準を満たす利用可能なセルがありません"

msgid "No compute host specified"
msgstr "コンピュートホストが指定されていません"

#, python-format
msgid "No configuration information found for operating system %(os_name)s"
msgstr "オペレーティングシステム %(os_name)s に関する設定情報が見つかりません"

#, python-format
msgid "No device with MAC address %s exists on the VM"
msgstr "MAC アドレス %s を持つデバイスが VM にありません"

#, python-format
msgid "No device with interface-id %s exists on VM"
msgstr "interface-id %s を持つデバイスが VM にありません"

#, python-format
msgid "No disk at %(location)s"
msgstr "%(location)s にディスクがありません"

msgid "No errors in logfiles!"
msgstr "ログファイル内にエラーはありません。"

#, python-format
msgid "No fixed IP addresses available for network: %(net)s"
msgstr "ネットワーク %(net)s で使用可能な Fixed IP アドレスがありません。"

#, python-format
msgid "No fixed IP associated with id %(id)s."
msgstr "ID %(id)s に関連付けられた Fixed IP がありません。"

msgid "No fixed IP found."
msgstr "Fixed IP が見つかりません。"

msgid "No fixed IPs associated to instance"
msgstr "Fixed IP がインスタンスに割り当てられていません"

msgid "No floating IP addresses have been defined."
msgstr "Floating IP アドレスが定義されていません。"

#, python-format
msgid "No free disk device names for prefix '%s'"
msgstr "プレフィックス '%s' に合致する名前の空きディスクデバイスがありません"

msgid "No free nbd devices"
msgstr "空きの nbd デバイスがありません"

#, python-format
msgid "No free port available for instance %(instance)s."
msgstr "インスタンス %(instance)s が使用できる空きポートがありません。"

msgid "No host available on cluster"
msgstr "クラスター上に使用可能なホストがありません"

msgid "No hosts found to map to cell, exiting."
msgstr "セルにマッピングするホストが見つかりません。処理を終了します。"

#, python-format
msgid "No hypervisor matching '%s' could be found."
msgstr "'%s' と合致するハイパーバイザーが見つかりませんでした。"

msgid "No image locations are accessible"
msgstr "イメージの場所にアクセスできません"

msgid "No instances found for any event"
msgstr "どのインスタンスに対するイベントもありません"

#, python-format
msgid ""
"No live migration URI configured and no default available for \"%(virt_type)s"
"\" hypervisor virtualization type."
msgstr ""
"ライブマイグレーションの URI が設定されておらず、ハイパーバイザーの仮想化タイ"
"プの \"%(virt_type)s\" で使用可能なデフォルトが存在しません。"

#, python-format
msgid "No matching ID for the URL %s was found."
msgstr "URL %s に一致する ID が見つかりませんでした。"

msgid "No more available networks."
msgstr "使用可能なネットワークはこれ以上ありません。"

msgid "No more floating IPs available."
msgstr "使用可能な Floating IP はこれ以上ありません。"

#, python-format
msgid "No more floating IPs in pool %s."
msgstr "プール %s 内に Floating IP はこれ以上ありません。"

#, python-format
msgid "No mount points found in %(root)s of %(image)s"
msgstr "%(image)s の %(root)s にマウントポイントが見つかりません"

msgid "No networks defined."
msgstr "ネットワークが定義されていません。"

msgid "No networks found"
msgstr "ネットワークが見つかりません"

msgid "No nova entries in syslog!"
msgstr "syslog 内に nova 項目がありません。"

#, python-format
msgid "No operating system found in %s"
msgstr "%s 内にオペレーティングシステムが見つかりません"

#, python-format
msgid "No primary VDI found for %s"
msgstr "%s のプライマリー VDI が見つかりません"

msgid "No root disk defined."
msgstr "ルートディスクが定義されていません。"

#, python-format
msgid ""
"No specific network was requested and none are available for project "
"'%(project_id)s'."
msgstr ""
"特定のネットワークが要求されず、プロジェクト '%(project_id)s' で利用可能な"
"ネットワークがありません。"

msgid "No suitable network for migrate"
msgstr "マイグレーションに適切なネットワークがありません"

msgid "No valid host found for cold migrate"
msgstr "コールドマイグレーションに有効なホストが見つかりません"

msgid "No valid host found for resize"
msgstr "サイズ変更の対象として有効なホストが見つかりません"

#, python-format
msgid "No valid host was found. %(reason)s"
msgstr "有効なホストが見つかりませんでした。%(reason)s"

#, python-format
msgid "No volume Block Device Mapping at path: %(path)s"
msgstr "ボリュームのブロックデバイスマッピングがパス %(path)s にありません"

#, python-format
msgid "No volume Block Device Mapping with id %(volume_id)s."
msgstr ""
"ID %(volume_id)s を持つボリュームのブロックデバイスマッピングがありません。"

#, python-format
msgid "Node %s could not be found."
msgstr "ノード %s が見つかりませんでした。"

#, python-format
msgid "Not able to acquire a free port for %(host)s"
msgstr "%(host)s 用の未使用ポートを取得できません"

#, python-format
msgid "Not able to bind %(host)s:%(port)d, %(error)s"
msgstr "%(host)s:%(port)d をバインドできません。%(error)s"

#, python-format
msgid ""
"Not all Virtual Functions of PF %(compute_node_id)s:%(address)s are free."
msgstr ""
"PF %(compute_node_id)s の %(address)s のすべての Virtual Function に空きがあ"
"るとは限りません。"

msgid "Not an rbd snapshot"
msgstr "rbd スナップショットではありません"

#, python-format
msgid "Not authorized for image %(image_id)s."
msgstr "イメージ %(image_id)s への権限がありません。"

msgid "Not authorized."
msgstr "権限がありません。"

msgid "Not enough parameters to build a valid rule."
msgstr "有効なルールを作成するだけの十分なパラメータがありません"

#, python-format
msgid "Not enough parameters: %(reason)s"
msgstr "パラメーターが不十分です: %(reason)s"

msgid "Not implemented on Windows"
msgstr "Windows では実装されていません"

msgid "Not stored in rbd"
msgstr "rbd 内に保管されていません"

msgid "Nothing was archived."
msgstr "アーカイブは行われませんでした"

#, python-format
msgid "Nova requires libvirt version %s or greater."
msgstr "Nova には libvirt バージョン %s 以降が必要です。"

msgid "Number of Rows Archived"
msgstr "アーカイブ済みの行数"

#, python-format
msgid "Number of retries to plugin (%(num_retries)d) exceeded."
msgstr "プラグインに対する再試行の回数 (%(num_retries)d) を超えました。"

#, python-format
msgid ""
"Number of serial ports '%(num_ports)s' specified in '%(property)s' isn't "
"valid."
msgstr ""
"'%(property)s' に指定されているシリアルポート数 '%(num_ports)s' は無効です。"

#, python-format
msgid "OVS configuration failed with: %(inner_exception)s."
msgstr "以下の理由のため OVS の設定が失敗しました: %(inner_exception)s。"

#, python-format
msgid "Object action %(action)s failed because: %(reason)s"
msgstr "オブジェクトのアクション %(action)s が失敗しました。原因: %(reason)s"

msgid "Old volume is attached to a different instance."
msgstr "旧ボリュームは別のインスタンスに接続されています。"

#, python-format
msgid "One or more hosts already in availability zone(s) %s"
msgstr "アベイラビリティーゾーン %s に 1 つ以上のホストが既にあります"

msgid "Only administrators may list deleted instances"
msgstr "削除済みインスタンスの一覧を取得できるのは管理者のみです。"

#, python-format
msgid ""
"Only file-based SRs (ext/NFS) are supported by this feature.  SR %(uuid)s is "
"of type %(type)s"
msgstr ""
"この機能でサポートされるのは、ファイルベースの SR (ext/NFS) のみです。SR "
"%(uuid)s のタイプは %(type)s です。"

msgid "Only root certificate can be retrieved."
msgstr "ルート証明書のみが取得可能です。"

#, python-format
msgid "OpenSSL error: %s"
msgstr "OpenSSL エラー: %s"

msgid "Origin header does not match this host."
msgstr "オリジンヘッダーがこのホストに一致しません。"

msgid "Origin header not valid."
msgstr "オリジンヘッダーが無効です。"

msgid "Origin header protocol does not match this host."
msgstr "オリジンヘッダープロトコルがこのホストに一致しません。"

#, python-format
msgid "PCI Device %(node_id)s:%(address)s not found."
msgstr "PCI デバイス %(node_id)s:%(address)s が見つかりません。"

#, python-format
msgid "PCI alias %(alias)s is not defined"
msgstr "PCI エイリアス %(alias)s が定義されていません"

#, python-format
msgid ""
"PCI device %(compute_node_id)s:%(address)s is %(status)s instead of "
"%(hopestatus)s"
msgstr ""
"PCI デバイス %(compute_node_id)s:%(address)s は %(hopestatus)s ではなく "
"%(status)s です"

#, python-format
msgid ""
"PCI device %(compute_node_id)s:%(address)s is owned by %(owner)s instead of "
"%(hopeowner)s"
msgstr ""
"PCI デバイス %(compute_node_id)s:%(address)s の所有者は、%(hopeowner)s ではな"
"く %(owner)s です"

#, python-format
msgid "PCI device %(id)s not found"
msgstr "PCI デバイス %(id)s が見つかりません"

#, python-format
msgid "PCI device request %(requests)s failed"
msgstr "PCI デバイス要求 %(requests)s が失敗しました"

#, python-format
msgid ""
"PCS doesn't support images in %s format. You should either set "
"force_raw_images=True in config or upload an image in ploop or raw format."
msgstr ""
"PCS では %s 形式のイメージはサポートされません。設定で force_raw_images=True "
"を設定するか、ploop 形式か raw の形式でイメージをアップロードする必要がありま"
"す。"

#, python-format
msgid ""
"PIF %(pif_uuid)s for network %(bridge)s has VLAN id %(pif_vlan)d. Expected "
"%(vlan_num)d"
msgstr ""
"ネットワーク %(bridge)s の PIF %(pif_uuid)s の VLAN ID は %(pif_vlan)d で"
"す。%(vlan_num)d が期待されていました"

#, python-format
msgid "PIF %s does not contain IP address"
msgstr "PIF %s に IP アドレスが含まれていません"

#, python-format
msgid "Page size %(pagesize)s forbidden against '%(against)s'"
msgstr "ページサイズ %(pagesize)s は \"%(against)s\" に対して禁止されています"

#, python-format
msgid "Page size %(pagesize)s is not supported by the host."
msgstr "ページサイズ %(pagesize)s はこのホストではサポートされていません。"

#, python-format
msgid ""
"Parameters %(missing_params)s not present in vif_details for vif %(vif_id)s. "
"Check your Neutron configuration to validate that the macvtap parameters are "
"correct."
msgstr ""
"vif %(vif_id)s について、パラメーター %(missing_params)s が vif_details 内に"
"存在しません。macvtapパラーメーターが正確に設定されているか Neutron の設定を"
"確認してください。"

#, python-format
msgid "Path %s must be LVM logical volume"
msgstr "パス %s は LVM 論理ボリュームでなければなりません"

msgid "Paused"
msgstr "一時停止済み"

msgid "Personality file content too long"
msgstr "パーソナリティーファイルの内容が長すぎます"

msgid "Personality file limit exceeded"
msgstr "パーソナリティーファイル数の上限を超えました"

msgid "Personality file path too long"
msgstr "パーソナリティーファイルのパスが長すぎます"

#, python-format
msgid ""
"Physical Function %(compute_node_id)s:%(address)s, related to VF "
"%(compute_node_id)s:%(vf_address)s is %(status)s instead of %(hopestatus)s"
msgstr ""
"VF %(compute_node_id)s に関連する %(address)s のPhysical Function "
"%(compute_node_id)s。%(vf_address)s は %(status)s ではなく %(hopestatus)sです"

#, python-format
msgid "Physical network is missing for network %(network_uuid)s"
msgstr "ネットワーク %(network_uuid)s に対応する物理ネットワークがありません"

msgid "Please re-run nova-manage as root."
msgstr "nova-manage を root で再実行してください。"

msgid "Please specify either fixed_range or uuid"
msgstr "fixed_range または UUID のいずれかを指定してください"

#, python-format
msgid "Plug vif failed because of unexpected vif_type=%s"
msgstr "想定しない vif_type=%s が原因で vif の接続に失敗しました"

#, python-format
msgid "Plugin version mismatch (Expected %(exp)s, got %(got)s)"
msgstr ""
"プラグインのバージョンが一致しません (%(exp)s が期待値でしたが、%(got)s が取"
"得されました)"

#, python-format
msgid "Policy doesn't allow %(action)s to be performed."
msgstr "ポリシーにより %(action)s の実行が許可されていません"

#, python-format
msgid "Port %(port_id)s is still in use."
msgstr "ポート %(port_id)s はまだ使用中です。"

#, python-format
msgid "Port %(port_id)s not usable for instance %(instance)s."
msgstr "ポート %(port_id)s はインスタンス %(instance)s では使用できません。"

#, python-format
msgid ""
"Port %(port_id)s not usable for instance %(instance)s. Value %(value)s "
"assigned to dns_name attribute does not match instance's hostname "
"%(hostname)s"
msgstr ""
"ポート %(port_id)s はインスタンス %(instance)s では使用できません。dns_name "
"属性に割り当てられた値 %(value)s がインスタンスのホスト名 %(hostname)s と合致"
"しません"

#, python-format
msgid "Port %(port_id)s requires a FixedIP in order to be used."
msgstr "ポート %(port_id)s を使用するには、Fixed IP が必要です。"

#, python-format
msgid "Port %s is not attached"
msgstr "ポート %s は接続されていません"

#, python-format
msgid "Port id %(port_id)s could not be found."
msgstr "ポート ID %(port_id)s が見つかりませんでした。"

#, python-format
msgid "Project %(project_id)s could not be found."
msgstr "プロジェクト %(project_id)s が見つかりませんでした。"

#, python-format
msgid "Provided video model (%(model)s) is not supported."
msgstr "指定されたビデオモデル (%(model)s) はサポートされていません。"

#, python-format
msgid "Provided watchdog action (%(action)s) is not supported."
msgstr ""
"指定されたウォッチドッグアクション (%(action)s) はサポートされていません。"

msgid "QEMU guest agent is not enabled"
msgstr "QEMU ゲストエージェントが有効になっていません"

#, python-format
msgid "Quiescing is not supported in instance %(instance_id)s"
msgstr "インスタンス %(instance_id)s を正常に終了することができません。"

msgid "Quota"
msgstr "クォータ"

#, python-format
msgid "Quota class %(class_name)s could not be found."
msgstr "クォータクラス %(class_name)s が見つかりませんでした。"

msgid "Quota could not be found"
msgstr "クォータが見つかりませんでした"

#, python-format
msgid ""
"Quota exceeded for %(overs)s: Requested %(req)s, but already used %(used)s "
"of %(allowed)s %(overs)s"
msgstr ""
"%(overs)s のクオータを超えました: %(req)s がリクエストされましたが、既に "
"%(allowed)s のうち %(used)s を使用しています (%(overs)s)"

#, python-format
msgid "Quota exceeded for resources: %(overs)s"
msgstr "リソース %(overs)s がクォータを超過しました"

msgid "Quota exceeded, too many key pairs."
msgstr "クォータを超過しました。キーペアが多すぎます。"

msgid "Quota exceeded, too many networks."
msgstr "クォータを超過しました。ネットワークが多すぎます。"

msgid "Quota exceeded, too many security group rules."
msgstr "クォータを超過しました。セキュリティーグループルールが多すぎます。"

msgid "Quota exceeded, too many security groups."
msgstr "クォータを超過しました。セキュリティーグループが多すぎます。"

msgid "Quota exceeded, too many server groups."
msgstr "クォータを超過しました。サーバーグループが多すぎます。"

msgid "Quota exceeded, too many servers in group"
msgstr "クォータを超過しました。グループ内のサーバーが多すぎます"

#, python-format
msgid "Quota exceeded: code=%(code)s"
msgstr "クォータを超過しました: code=%(code)s"

#, python-format
msgid "Quota exists for project %(project_id)s, resource %(resource)s"
msgstr ""
"プロジェクト %(project_id)s、リソース %(resource)s のクォータが存在します"

#, python-format
msgid "Quota for project %(project_id)s could not be found."
msgstr "プロジェクト %(project_id)s のクォータが見つかりませんでした。"

#, python-format
msgid ""
"Quota for user %(user_id)s in project %(project_id)s could not be found."
msgstr ""
"プロジェクト %(project_id)s のユーザー %(user_id)s のクォータが見つかりません"
"でした。"

#, python-format
msgid ""
"Quota limit %(limit)s for %(resource)s must be greater than or equal to "
"already used and reserved %(minimum)s."
msgstr ""
"%(resource)s のクォータ上限 %(limit)s は、既に使用もしくは予約されている数で"
"ある %(minimum)s 以上でなければなりません。"

#, python-format
msgid ""
"Quota limit %(limit)s for %(resource)s must be less than or equal to "
"%(maximum)s."
msgstr ""
"%(resource)s のクォータ上限 %(limit)s は、%(maximum)s 以下でなければなりませ"
"ん。"

msgid "Quota limit must be -1 or greater."
msgstr "クォータ上限は -1 以上の値でなければなりません。"

#, python-format
msgid "Quota limit must be greater than %s."
msgstr "クォータ上限は %s より大きい値でなければなりません。"

#, python-format
msgid "Quota limit must be less than %s."
msgstr "クォータ上限は %s より小さい値でなければなりません。"

#, python-format
msgid "Quota reservation %(uuid)s could not be found."
msgstr "クォータ予約 %(uuid)s が見つかりませんでした。"

#, python-format
msgid "Quota usage for project %(project_id)s could not be found."
msgstr "プロジェクト %(project_id)s のクォータ使用量が見つかりませんでした。"

#, python-format
msgid "Reached maximum number of retries trying to unplug VBD %s"
msgstr "VBD %s の取り外しの最大試行回数に達しました"

msgid ""
"Realtime policy needs vCPU(s) mask configured with at least 1 RT vCPU and 1 "
"ordinary vCPU. See hw:cpu_realtime_mask or hw_cpu_realtime_mask"
msgstr ""
"リアルタイムポリシーでは、1 つ以上の RT vCPU と 1 つの通常の vCPU を使用して "
"vCPU のマスクを設定する必要があります。hw:cpu_realtime_mask または "
"hw_cpu_realtime_mask を参照してください"

msgid "Realtime policy not supported by hypervisor"
msgstr "ハイパーバイザーはリアルタイムポリシーをサポートしません"

#, python-format
msgid ""
"Relative blockcommit support was not detected. Libvirt '%s' or later is "
"required for online deletion of file/network storage-backed volume snapshots."
msgstr ""
"相対ブロックコミットのサポートが検出されませんでした。ファイルまたはネット"
"ワークストレージによるボリュームのスナップショットをオンラインで削除するには "
"Libvirt '%s' 以降が必要です。"

msgid "Request body and URI mismatch"
msgstr "リクエスト本文と URI の不一致"

msgid "Request is too large."
msgstr "リクエストが大きすぎます。"

msgid ""
"Request must include either Timestamp or Expires, but cannot contain both"
msgstr ""
"リクエストにはタイムスタンプまたは有効期限のいずれかを含める必要があります"
"が、両方を含めることはできません"

#, python-format
msgid "Request of image %(image_id)s got BadRequest response: %(response)s"
msgstr ""
"イメージ %(image_id)s のリクエストに対して BadRequest のレスポンスが返されま"
"した: %(response)s"

#, python-format
msgid "RequestSpec not found for instance %(instance_uuid)s"
msgstr "インスタンス %(instance_uuid)s に対する RequestSpec が見つかりません"

msgid "Requested CPU control policy not supported by host"
msgstr "ホストは要求された CPU の制御ポリシーをサポートしません"

#, python-format
msgid "Requested cidr (%(cidr)s) conflicts with existing cidr (%(other)s)"
msgstr ""
"要求された CIDR (%(cidr)s) は、既存の CIDR (%(other)s) と競合しています"

#, python-format
msgid ""
"Requested hardware '%(model)s' is not supported by the '%(virt)s' virt driver"
msgstr ""
"要求されたハードウェア '%(model)s' は '%(virt)s' virt ドライバーではサポート"
"されません"

#, python-format
msgid "Requested image %(image)s has automatic disk resize disabled."
msgstr ""
"要求されたイメージ %(image)s ではディスクサイズの自動変更が無効になっていま"
"す。"

msgid ""
"Requested instance NUMA topology cannot fit the given host NUMA topology"
msgstr ""
"要求されたインスタンス NUMA トポロジーは、指定されたホスト NUMA トポロジーに"
"適合しません"

msgid ""
"Requested instance NUMA topology together with requested PCI devices cannot "
"fit the given host NUMA topology"
msgstr ""
"PCI デバイスとともに要求されたインスタンスの NUMA トポロジーは、指定されたホ"
"ストの NUMA トポロジーに適合できません"

msgid "Requested network does not contain enough (2+) usable hosts"
msgstr "要求されたネットワークには十分な (2 以上) 使用可能なホストがありません"

#, python-format
msgid ""
"Requested vCPU limits %(sockets)d:%(cores)d:%(threads)d are impossible to "
"satisfy for vcpus count %(vcpus)d"
msgstr ""
"要求された vCPU 制限 %(sockets)d:%(cores)d:%(threads)d は、vCPU カウント "
"%(vcpus)d を満たすことができません"

#, python-format
msgid ""
"Required image properties for signature verification do not exist. Cannot "
"verify signature. Missing property: %s"
msgstr ""
"シグニチャーの検証に必要なイメージプロパティーが存在しません。シグニチャーを"
"検証できません。プロパティーが存在しません: %s"

#, python-format
msgid "Rescue device does not exist for instance %s"
msgstr "インスタンス %s 用のレスキューデバイスが存在しません"

msgid "Reserved"
msgstr "予約済み"

#, python-format
msgid "Resize error: %(reason)s"
msgstr "サイズ変更エラー: %(reason)s"

msgid "Resize to zero disk flavor is not allowed."
msgstr "ディスクが 0 のフレーバーにサイズ変更することはできません。"

msgid "Resource could not be found."
msgstr "リソースを見つけられませんでした。"

msgid "Resumed"
msgstr "再開済み"

#, python-format
msgid "Root element name should be '%(name)s' not '%(tag)s'"
msgstr ""
"ルートエレメント名は '%(tag)s' ではなく '%(name)s' でなければなりません"

msgid "Rotation param is required for backup image_type"
msgstr "バックアップの image_type には Rotation パラメーターが必要です"

#, python-format
msgid "Rule (%s) not found"
msgstr "ルール (%s) が見つかりません"

#, python-format
msgid "Rule already exists in group: %(rule)s"
msgstr "ルールがグループにはすでに存在します: %(rule)s"

#, python-format
msgid "Running Nova with parallels virt_type requires libvirt version %s"
msgstr ""
"parallels virt_type で Nova を実行するには libvirt バージョン %s が必要です。"

#, python-format
msgid ""
"Running Nova with qemu/kvm virt_type on %(arch)s requires libvirt version "
"%(libvirt_ver)s and qemu version %(qemu_ver)s, or greater"
msgstr ""
"%(arch)s 上で qemu/kvm virt_type を使用して Nova を稼働させるには、libvirt の"
"バージョン %(libvirt_ver)s および qemu のバージョン %(qemu_ver)s (またはそれ"
"以降のバージョン) が必要です。"

#, python-format
msgid "Running batches of %i until complete"
msgstr "完了するまで %i のバッチを実行します"

#, python-format
msgid "Running cmd (subprocess): %s"
msgstr "コマンド (subprocess) 実行: %s"

#, python-format
msgid "Scheduler Host Filter %(filter_name)s could not be found."
msgstr ""
"スケジューラーホストフィルター %(filter_name)s が見つかりませんでした。"

#, python-format
msgid "Security group %(name)s is not found for project %(project)s"
msgstr ""
"プロジェクト %(project)s のセキュリティーグループ %(name)s が見つかりません"

#, python-format
msgid ""
"Security group %(security_group_id)s is already associated with the instance "
"%(instance_id)s"
msgstr ""
"セキュリティーグループ %(security_group_id)s は既にインスタンス "
"%(instance_id)s に関連付けられています"

#, python-format
msgid ""
"Security group %(security_group_id)s is not associated with the instance "
"%(instance_id)s"
msgstr ""
"セキュリティーグループ %(security_group_id)s はインスタンス %(instance_id)s "
"に関連付けられていません"

#, python-format
msgid ""
"Security group %(security_group_id)s not found for project %(project_id)s."
msgstr ""
"プロジェクト %(project_id)s のセキュリティーグループ %(security_group_id)s が"
"見つかりません。"

#, python-format
msgid "Security group %(security_group_id)s not found."
msgstr "セキュリティーグループ %(security_group_id)s が見つかりません。"

#, python-format
msgid ""
"Security group %(security_group_name)s already exists for project "
"%(project_id)s."
msgstr ""
"プロジェクト %(project_id)s にはセキュリティーグループ "
"%(security_group_name)s がすでに存在します。"

#, python-format
msgid ""
"Security group %(security_group_name)s not associated with the instance "
"%(instance)s"
msgstr ""
"セキュリティーグループ %(security_group_name)s がインスタンス %(instance)s に"
"関連付けられていません"

#, python-format
msgid "Security group %s already exists"
msgstr "セキュリティーグループ %s は既に存在します"

#, python-format
msgid "Security group %s is not a string or unicode"
msgstr "セキュリティーグループ %s が文字列でも Unicode でもありません"

#, python-format
msgid "Security group default rule (%rule_id)s not found."
msgstr "セキュリティーグループのデフォルトルール (%rule_id) が見つかりません。"

msgid "Security group id should be integer"
msgstr "セキュリティーグループ ID は整数でなければなりません"

msgid "Security group id should be uuid"
msgstr "セキュリティーグループ ID は UUID でなければなりません"

msgid "Security group is still in use"
msgstr "セキュリティーグループはまだ使用中です"

msgid "Security group name cannot be empty"
msgstr "セキュリティーグループ名を空にすることはできません"

msgid "Security group not specified"
msgstr "セキュリティーグループが指定されていません"

#, python-format
msgid "Security group with rule %(rule_id)s not found."
msgstr "ルール %(rule_id)s を持つセキュリティーグループが見つかりません。"

#, python-format
msgid "Server disk was unable to be resized because: %(reason)s"
msgstr "サーバーディスクのサイズを変更できませんでした。理由: %(reason)s"

msgid "Server does not exist"
msgstr "サーバーが存在しません。"

#, python-format
msgid "ServerGroup policy is not supported: %(reason)s"
msgstr "サーバーグループポリシーはサポートされていません: %(reason)s"

msgid "ServerGroupAffinityFilter not configured"
msgstr "ServerGroupAffinityFilter が設定されていません"

msgid "ServerGroupAntiAffinityFilter not configured"
msgstr "ServerGroupAntiAffinityFilter が設定されていません"

msgid "ServerGroupSoftAffinityWeigher not configured"
msgstr "ServerGroupSoftAffinityWeigher が設定されていません"

msgid "ServerGroupSoftAntiAffinityWeigher not configured"
msgstr "ServerGroupSoftAntiAffinityWeigher が設定されていません"

#, python-format
msgid "Service %(service_id)s could not be found."
msgstr "サービス %(service_id)s が見つかりませんでした。"

#, python-format
msgid "Service %s not found."
msgstr "サービス %s が見つかりません。"

#, python-format
msgid "Service API method not found: %(detail)s"
msgstr "サービス API メソッドが見つかりません: %(detail)s"

msgid "Service is unavailable at this time."
msgstr "サービスが現在利用できません。"

#, python-format
msgid "Service with host %(host)s binary %(binary)s exists."
msgstr ""
"ホスト %(host)s のバイナリー %(binary)s を使用するサービスが存在します。"

#, python-format
msgid "Service with host %(host)s topic %(topic)s exists."
msgstr "ホスト %(host)s のトピック %(topic)s を使用するサービスが存在します。"

msgid "Set admin password is not supported"
msgstr "設定された管理者パスワードがサポートされません"

#, python-format
msgid "Shadow table with name %(name)s already exists."
msgstr "名前が %(name)s のシャドーテーブルは既に存在します。"

#, python-format
msgid "Share '%s' is not supported"
msgstr "シェア '%s' はサポートされません"

#, python-format
msgid "Share level '%s' cannot have share configured"
msgstr "シェアレベル '%s' に設定されたシェアがありません"

msgid ""
"Shrinking the filesystem down with resize2fs has failed, please check if you "
"have enough free space on your disk."
msgstr ""
"resize2fs でファイルシステムのサイズを縮小できませんでした。ディスク上に十分"
"な空き容量があるかどうかを確認してください。"

#, python-format
msgid "Signature verification for the image failed: %(reason)s."
msgstr "イメージのシグニチャーの検証が失敗しました: %(reason)s。"

#, python-format
msgid "Snapshot %(snapshot_id)s could not be found."
msgstr "スナップショット %(snapshot_id)s が見つかりませんでした。"

msgid "Some fields are invalid."
msgstr "いくつかのフィールドが無効です。"

msgid "Some required fields are missing"
msgstr "いくつかの必須フィールドがありません。"

#, python-format
msgid ""
"Something went wrong when deleting a volume snapshot: rebasing a "
"%(protocol)s network disk using qemu-img has not been fully tested"
msgstr ""
"ボリュームのスナップショットの削除中に問題が発生しました: qemu-img を使用し"
"て %(protocol)s のネットワークディスクを再設定することは十分に検証されていま"
"せん。"

msgid "Sort direction size exceeds sort key size"
msgstr "ソート方向の数がソートキーの数より多いです"

msgid "Sort key supplied was not valid."
msgstr "指定されたソートキーが無効でした。"

msgid "Specified fixed address not assigned to instance"
msgstr "指定された固定アドレスはインスタンスに割り当てられていません"

msgid "Specify `table_name` or `table` param"
msgstr "'table_name' または 'table' のパラメーターを指定してください"

msgid "Specify only one param `table_name` `table`"
msgstr ""
"'table_name' または 'table' のパラメーターのいずれか 1 つのみを指定してくださ"
"い"

msgid "Started"
msgstr "開始済み"

msgid "Stopped"
msgstr "停止済み"

#, python-format
msgid "Storage error: %(reason)s"
msgstr "ストレージエラー: %(reason)s"

#, python-format
msgid "Storage policy %s did not match any datastores"
msgstr "ストレージポリシー %s がどのデータストアにも一致しませんでした"

msgid "Success"
msgstr "成功"

msgid "Suspended"
msgstr "休止済み"

msgid "Swap drive requested is larger than instance type allows."
msgstr ""
"要求されたスワップドライブのサイズが、インスタンスタイプで許可されているサイ"
"ズを超えています。"

msgid "Swap only supports host devices"
msgstr "スワップでサポートされるのはホストデバイスのみです"

msgid "Table"
msgstr "テーブル"

#, python-format
msgid "Task %(task_name)s is already running on host %(host)s"
msgstr "タスク %(task_name)s はホスト %(host)s 上で既に実行中です"

#, python-format
msgid "Task %(task_name)s is not running on host %(host)s"
msgstr "タスク %(task_name)s はホスト %(host)s 上で実行されていません"

#, python-format
msgid "The CA file for %(project)s could not be found"
msgstr "%(project)s 用の CA ファイルが見つかりませんでした"

#, python-format
msgid "The CRL file for %(project)s could not be found"
msgstr "%(project)s 用の CRL ファイルが見つかりませんでした"

#, python-format
msgid "The DNS entry %(name)s already exists in domain %(domain)s."
msgstr "DNS エントリー %(name)s はドメイン %(domain)s 内に既に存在します。"

#, python-format
msgid "The PCI address %(address)s has an incorrect format."
msgstr "PCI アドレス %(address)s の形式が正しくありません。"

msgid ""
"The above error may show that the database has not been created.\n"
"Please create a database using 'nova-manage db sync' before running this "
"command."
msgstr ""
"上のエラーは、データベースが作成されなかったことを示している可能性がありま"
"す。\n"
"このコマンドを実行する前に、'nova-manage db sync' を使用してデータベースを作"
"成してください。"

msgid "The backlog must be more than 0"
msgstr "バックログは 0 より大きい値である必要があります"

#, python-format
msgid "The console port range %(min_port)d-%(max_port)d is exhausted."
msgstr ""
"コンソール用のポート範囲 %(min_port)d-%(max_port)d を使い切られています。"

msgid "The created instance's disk would be too small."
msgstr "作成されたインスタンスのディスクが小さすぎます。"

msgid "The current driver does not support preserving ephemeral partitions."
msgstr "現行ドライバーは、一時パーティションの保持をサポートしていません。"

msgid "The default PBM policy doesn't exist on the backend."
msgstr "デフォルト PBM ポリシーがバックエンドに存在しません。"

#, python-format
msgid "The firewall filter for %s does not exist"
msgstr "%s のファイアウォールフィルターが存在しません"

msgid "The floating IP request failed with a BadRequest"
msgstr "Floating IP のリクエストが BadRequest により失敗しました。"

#, python-format
msgid "The group %(group_name)s must be configured with an id."
msgstr "グループ %(group_name)s に ID を設定する必要があります。"

msgid "The input is not a string or unicode"
msgstr "入力が文字列でも Unicode でもありません"

msgid ""
"The instance requires a newer hypervisor version than has been provided."
msgstr ""
"このインスタンスは使用されているものよりも新しいバージョンのハイパーバイザー"
"を必要とします。"

#, python-format
msgid ""
"The key %(r)s is required in the location metadata to access the url %(url)s."
msgstr ""
"URL %(url)s にアクセスするには、ロケーションメタデータ内にキー %(r)s がなけれ"
"ばなりません。"

#, python-format
msgid "The key %s is required in all file system descriptions."
msgstr "すべてのファイルシステム記述でキー %s が必要です。"

#, python-format
msgid ""
"The metadata for this location will not work with this module %(module)s.  "
"%(reason)s."
msgstr ""
"このロケーションのメタデータは、このモジュール %(module)s では機能しませ"
"ん。%(reason)s。"

#, python-format
msgid "The method %(method_name)s is not implemented."
msgstr "メソッド %(method_name)s は実装されていません。"

#, python-format
msgid "The module %(module)s is misconfigured: %(reason)s."
msgstr "モジュール %(module)s の設定に誤りがあります: %(reason)s。"

#, python-format
msgid "The mount %(mount_path)s is not a valid Quobyte volume. Error: %(exc)s"
msgstr ""
"マウント %(mount_path)s は有効な Quobyte ボリュームではありません。エラー: "
"%(exc)s"

#, python-format
msgid ""
"The mount point advertised by glance: %(glance_mount)s, does not match the "
"URL path: %(path)s"
msgstr ""
"Glance %(glance_mount)s から通知されたマウントポイントが、URL パス %(path)s "
"と一致しません"

#, python-format
msgid ""
"The network range is not big enough to fit %(num_networks)s networks. "
"Network size is %(network_size)s"
msgstr ""
"ネットワーク範囲が %(num_networks)s 個のネットワークを収容できるほど大きくあ"
"りません。ネットワークサイズは %(network_size)s です"

#, python-format
msgid "The number of defined ports: %(ports)d is over the limit: %(quota)d"
msgstr "定義したポート %(ports)d の数が上限 %(quota)d を超えています"

msgid "The only partition should be partition 1."
msgstr "唯一のパーティションはパーティション 1 でなければなりません。"

#, python-format
msgid "The provided RNG device path: (%(path)s) is not present on the host."
msgstr "指定された RNG デバイスパス (%(path)s) がホスト上にありません。"

msgid "The request body can't be empty"
msgstr "リクエスト本文は空にはできません"

msgid "The request is invalid."
msgstr "リクエスト内容が無効です。"

#, python-format
msgid ""
"The requested amount of video memory %(req_vram)d is higher than the maximum "
"allowed by flavor %(max_vram)d."
msgstr ""
"要求されたビデオメモリー容量 %(req_vram)d がフレーバー %(max_vram)d で許可さ"
"れている最大値を上回っています。"

msgid "The requested availability zone is not available"
msgstr "要求されたアベイラビリティーゾーンは使用不可です"

msgid "The requested console type details are not accessible"
msgstr "要求されたコンソールタイプの詳細にはアクセスできません"

msgid "The requested functionality is not supported."
msgstr "要求された機能はサポートされていません。"

msgid "The signature data was not properly encoded using base64"
msgstr ""
"このシグニチャーデータは base64 を使用して適切にエンコードされませんでした"

#, python-format
msgid "The specified cluster '%s' was not found in vCenter"
msgstr "指定されたクラスター '%s' が vCenter で見つかりませんでした"

msgid ""
"The sum between the number of networks and the vlan start cannot be greater "
"than 4094"
msgstr "ネットワーク数と VLAN の開始番号の和は 4094 より大きくできません。"

#, python-format
msgid "The supplied device (%(device)s) is busy."
msgstr "指定されたデバイス (%(device)s) は使用中です。"

#, python-format
msgid "The supplied device path (%(path)s) is in use."
msgstr "指定されたデバイスパス (%(path)s) は使用中です。"

#, python-format
msgid "The supplied device path (%(path)s) is invalid."
msgstr "指定されたデバイスパス (%(path)s) が無効です。"

#, python-format
msgid ""
"The supplied disk path (%(path)s) already exists, it is expected not to "
"exist."
msgstr ""
"指定されたディスクパス (%(path)s) は既にに存在します。これは存在しているべき"
"ではありません。"

msgid "The supplied hypervisor type of is invalid."
msgstr "指定されたハイパーバイザーは無効です。"

msgid "The target host can't be the same one."
msgstr "宛先ホストを同じホストにすることはできません。"

#, python-format
msgid "The token '%(token)s' is invalid or has expired"
msgstr "トークン \"%(token)s\" が無効か、有効期限切れです"

msgid "The vlan number cannot be greater than 4094"
msgstr "VLAN 番号を 4094 より大きくすることはできません"

msgid "The vlan number cannot be less than 1"
msgstr "VLAN 番号は 1 以上でなければなりません"

#, python-format
msgid ""
"The volume cannot be assigned the same device name as the root device %s"
msgstr ""
"ボリュームにルートデバイス %s と同じデバイス名を割り当てることはできません"

msgid "The volume was either invalid or not attached to the instance."
msgstr "ボリュームが無効か、インスタンスに接続されていません。"

#, python-format
msgid ""
"There are %(records)d records in the '%(table_name)s' table where the uuid "
"or instance_uuid column is NULL. Run this command again with the --delete "
"option after you have backed up any necessary data."
msgstr ""
"uuid 列または instance_uuid 列がヌルのレコード %(records)d がテーブル "
"'%(table_name)s' にあります。必要なデータをバックアップした後で、--delete オ"
"プションを指定してこのコマンドを再度実行してください。"

#, python-format
msgid ""
"There are %(records)d records in the '%(table_name)s' table where the uuid "
"or instance_uuid column is NULL. These must be manually cleaned up before "
"the migration will pass. Consider running the 'nova-manage db "
"null_instance_uuid_scan' command."
msgstr ""
"uuid 列または instance_uuid 列がヌルのレコード %(records)d がテーブル "
"'%(table_name)s' にあります。マイグレーションを行う前に、これらを手動でクリー"
"ンアップする必要があります。 'nova-manage db null_instance_uuid_scan' コマン"
"ドの実行を検討してください。"

msgid "There are not enough hosts available."
msgstr "使用可能なホストが不足しています。"

#, python-format
msgid ""
"There are still %(count)i unmigrated flavor records. Migration cannot "
"continue until all instance flavor records have been migrated to the new "
"format. Please run `nova-manage db migrate_flavor_data' first."
msgstr ""
"まだマイグレーションが行われていないフレーバーレコードの件数が %(count)i あり"
"ます。すべてのインスタンスのフレーバーレコードが新形式に移行するまで、マイグ"
"レーションを継続することはできません。最初に 'nova-manage db "
"migrate_flavor_data' を実行してください。"

#, python-format
msgid "There is no such action: %s"
msgstr "このようなアクションはありません: %s"

#, python-format
msgid "There was an error with the download module %(module)s. %(reason)s"
msgstr "ダウンロードモジュール %(module)s でエラーが発生しました。%(reason)s"

msgid "There were no records found where instance_uuid was NULL."
msgstr "instance_uuid がヌルのレコードはありませんでした。"

#, python-format
msgid ""
"This compute node's hypervisor is older than the minimum supported version: "
"%(version)s."
msgstr ""
"このコンピュートノードのハイパーバイザーがサポートされる最小バージョンよりも"
"古くなっています: %(version)s。"

msgid "This default rule already exists."
msgstr "このデフォルトルールは既に存在します。"

msgid "This domU must be running on the host specified by connection_url"
msgstr ""
"この domU は、connection_url で指定されたホスト上で実行されている必要がありま"
"す"

msgid "This driver only supports type 'a'"
msgstr "このドライバーはタイプ 'a' のみをサポートします"

msgid "This driver only supports type 'a' entries."
msgstr "このドライバーはタイプ 'a' の項目のみをサポートします。"

msgid ""
"This method needs to be called with either networks=None and port_ids=None "
"or port_ids and networks as not none."
msgstr ""
"このメソッドを呼び出すには、networks と port_ids に None を設定するか、 "
"port_ids と networks に None 以外の値を設定する必要があります。"

#, python-format
msgid "This rule already exists in group %s"
msgstr "指定されたルールは既にグループ %s に存在しています。"

#, python-format
msgid ""
"This service is older (v%(thisver)i) than the minimum (v%(minver)i) version "
"of the rest of the deployment. Unable to continue."
msgstr ""
"このサービスが実装環境の残りの部分の最小 (v%(minver)i) バージョンよりも古く "
"(v%(thisver)i) なっています。処理を継続できません。"

#, python-format
msgid "Timeout waiting for device %s to be created"
msgstr "デバイス %s が作成されるのを待っている際にタイムアウトになりました"

msgid "Timeout waiting for response from cell"
msgstr "セルからの応答を待機中にタイムアウトになりました"

#, python-format
msgid "Timeout while checking if we can live migrate to host: %s"
msgstr ""
"ホスト %s にライブマイグレーションできるか確認中にタイムアウトが発生しました"

msgid "To and From ports must be integers"
msgstr "開始ポートと終了ポートは整数でなければなりません"

msgid "Token not found"
msgstr "トークンが見つかりません"

#, python-format
msgid ""
"Too many IP addresses will be generated.  Please increase /%s to reduce the "
"number generated."
msgstr ""
"生成される IP アドレスが多すぎます。/%s の値を増やして、生成される数を減らし"
"てください。"

msgid "Triggering crash dump is not supported"
msgstr "クラッシュダンプのトリガーはサポートされません"

msgid "Type and Code must be integers for ICMP protocol type"
msgstr "ICMP プロトコルのタイプおよびコードは整数でなければなりません"

msgid "UEFI is not supported"
msgstr "UEFI はサポートされません"

msgid "UUID is required to delete Neutron Networks"
msgstr "Neutron ネットワークを削除するには、UUID が必要です"

#, python-format
msgid ""
"Unable to associate floating IP %(address)s to any fixed IPs for instance "
"%(id)s. Instance has no fixed IPv4 addresses to associate."
msgstr ""
"インスタンス %(id)s において Floating IP %(address)s を Fixed IP に割り当てる"
"ことができません。インスタンスに割り当てを行うべき Fixed IPv4 がありません。"

#, python-format
msgid ""
"Unable to associate floating IP %(address)s to fixed IP %(fixed_address)s "
"for instance %(id)s. Error: %(error)s"
msgstr ""
"インスタンス %(id)s において Floating IP %(address)s を Fixed IP "
"%(fixed_address)s に割り当てることができません。エラー: %(error)s"

msgid "Unable to authenticate Ironic client."
msgstr "Ironic クライアントを認証できません。"

msgid ""
"Unable to claim IP for VPN instances, ensure it isn't running, and try again "
"in a few minutes"
msgstr ""
"VPN インスタンスの IP を要求できません。実行中でないことを確認し、数分後に再"
"試行してください"

#, python-format
msgid "Unable to contact guest agent. The following call timed out: %(method)s"
msgstr ""
"ゲストエージェントに接続できません。次の呼び出しがタイムアウトになりました: "
"%(method)s"

#, python-format
msgid "Unable to convert image to %(format)s: %(exp)s"
msgstr "イメージを %(format)s に変換できません: %(exp)s"

#, python-format
msgid "Unable to convert image to raw: %(exp)s"
msgstr "イメージを raw 形式に変換できません: %(exp)s"

#, python-format
msgid "Unable to delete system group '%s'"
msgstr "システムグループ  '%s' を削除できません"

#, python-format
msgid "Unable to destroy VBD %s"
msgstr "VBD %s を削除できません"

#, python-format
msgid "Unable to destroy VDI %s"
msgstr "VDI %s を破棄できません"

msgid "Unable to detach from guest transient domain."
msgstr "ゲストの一時ドメインから切り離すことができません。"

#, python-format
msgid "Unable to determine disk bus for '%s'"
msgstr "ディスク '%s' のバスを判別できません"

#, python-format
msgid "Unable to determine disk prefix for %s"
msgstr "%s のディスクプレフィックスを判別できません"

#, python-format
msgid "Unable to eject %s from the pool; No master found"
msgstr "プールから %s を削除できません。マスターが見つかりません"

#, python-format
msgid "Unable to eject %s from the pool; pool not empty"
msgstr "プールから %s を削除できません。プールは空ではありません"

#, python-format
msgid "Unable to find SR from VBD %s"
msgstr "VBD %s から SR を取得できません。"

#, python-format
msgid "Unable to find SR from VDI %s"
msgstr "VDI %s から SR を取得できません"

#, python-format
msgid "Unable to find a mounted disk for target_iqn: %s"
msgstr "target_iqn %s のマウント済みディスクが見つかりません"

#, python-format
msgid ""
"Unable to find a mounted disk for target_iqn: %s. Please ensure that the "
"host's SAN policy is set to \"OfflineAll\" or \"OfflineShared\""
msgstr ""
"target_iqn %s のマウントされたディスクが見つかりません。ホストのSAN ポリシー"
"が \"OfflineAll\" または \"OfflineShared\" に設定されていることを確認してくだ"
"さい。"

#, python-format
msgid "Unable to find ca_file : %s"
msgstr "ca_file が見つかりません: %s"

#, python-format
msgid "Unable to find cert_file : %s"
msgstr "cert_file が見つかりません: %s"

#, python-format
msgid "Unable to find host for Instance %s"
msgstr "インスタンス %s のホストが見つかりません"

msgid "Unable to find iSCSI Target"
msgstr "iSCSI ターゲットが見つかりません"

#, python-format
msgid "Unable to find key_file : %s"
msgstr "key_file %s が見つかりません"

msgid "Unable to find root VBD/VDI for VM"
msgstr "VM のルート VBD/VDI が見つかりません"

msgid "Unable to find system log file!"
msgstr "システムログファイルが見つかりません。"

msgid "Unable to find volume"
msgstr "ボリュームが見つかりません"

msgid "Unable to get host UUID: /etc/machine-id does not exist"
msgstr " ホストの UUID を取得できません: /etc/machine-id が存在しません"

msgid "Unable to get host UUID: /etc/machine-id is empty"
msgstr "ホストの UUID が取得できません: /etc/machine-id が空です"

#, python-format
msgid "Unable to get record of VDI %s on"
msgstr "VDI %s のレコードを取得できません。"

#, python-format
msgid "Unable to introduce VDI for SR %s"
msgstr "SR %s で VDI を実装できません。"

#, python-format
msgid "Unable to introduce VDI on SR %s"
msgstr "SR %s で VDI を実装できません。"

#, python-format
msgid "Unable to join %s in the pool"
msgstr "プール内の %s を追加できません"

msgid ""
"Unable to launch multiple instances with a single configured port ID. Please "
"launch your instance one by one with different ports."
msgstr ""
"1個の作成済みのポート ID で複数のインスタンスの起動はできません。1 つ 1 つの"
"インスタンスを別々のポートで起動してください。"

msgid "Unable to log in to XenAPI (is the Dom0 disk full?)"
msgstr "XenAPI にログインできません (Dom0 ディスクフル?)"

#, python-format
msgid ""
"Unable to migrate %(instance_uuid)s to %(dest)s: Lack of memory(host:"
"%(avail)s <= instance:%(mem_inst)s)"
msgstr ""
"%(instance_uuid)s を %(dest)s にマイグレーションできません: メモリー不足です "
"(host:%(avail)s <= instance:%(mem_inst)s)"

#, python-format
msgid ""
"Unable to migrate %(instance_uuid)s: Disk of instance is too large(available "
"on destination host:%(available)s < need:%(necessary)s)"
msgstr ""
"%(instance_uuid)s をマイグレーションできません: インスタンスのディスクが大き"
"すぎます (宛先ホスト上の使用可能量: %(available)s < 必要量: %(necessary)s)"

#, python-format
msgid ""
"Unable to migrate instance (%(instance_id)s) to current host (%(host)s)."
msgstr ""
"インスタンス (%(instance_id)s) を現在と同じホスト (%(host)s) にマイグレーショ"
"ンすることはできません。"

#, python-format
msgid "Unable to obtain target information %s"
msgstr "ターゲットの情報 %s を取得できません"

msgid "Unable to resize disk down."
msgstr "ディスクのサイズを縮小することができません。"

#, python-format
msgid "Unable to retrieve certificate with ID: %s"
msgstr "以下の ID の証明書を取得できません: %s"

msgid "Unable to set password on instance"
msgstr "インスタンスにパスワードを設定できません"

msgid "Unable to shrink disk."
msgstr "ディスクを縮小できません。"

#, fuzzy
msgid "Unable to terminate instance."
msgstr "インスタンスを強制終了できません。"

#, python-format
msgid "Unable to unplug VBD %s"
msgstr "VBD %s の取り外しに失敗しました。"

#, python-format
msgid "Unable to update system group '%s'"
msgstr "システムグループ '%s' を更新できません"

#, python-format
msgid "Unacceptable CPU info: %(reason)s"
msgstr "指定できない CPU 情報: %(reason)s"

#, python-format
msgid "Unacceptable attach status:%s for ec2 API."
msgstr "ec2 API では指定できない接続ステータス: %s。"

msgid "Unacceptable parameters."
msgstr "指定できないパラメーターです。"

#, python-format
msgid "Unavailable console type %(console_type)s."
msgstr "コンソールタイプ %(console_type)s は使用できません。"

msgid ""
"Undefined Block Device Mapping root: BlockDeviceMappingList contains Block "
"Device Mappings from multiple instances."
msgstr ""
"ブロックデバイスマッピングのルートが定義されていません: "
"BlockDeviceMappingList に複数のインスタンスのブロックデバイスのマッピングが含"
"まれています。"

#, python-format
msgid ""
"Unexpected API Error. Please report this at http://bugs.launchpad.net/nova/ "
"and attach the Nova API log if possible.\n"
"%s"
msgstr ""
"想定しない API エラーが発生しました。http://bugs.launchpad.net/nova/ でこれを"
"報告して、可能な場合は Nova API ログを添付してください。\n"
"%s"

#, python-format
msgid "Unexpected aggregate action %s"
msgstr "想定しないアグリゲートのアクション %s"

msgid "Unexpected type adding stats"
msgstr "統計の追加中に想定しないタイプが見つかりました"

#, python-format
msgid "Unexpected vif_type=%s"
msgstr "想定しない vif_type=%s"

msgid "Unknown"
msgstr "不明"

#, python-format
msgid "Unknown %(cell_type)s when routing to %(target_cell)s"
msgstr "%(target_cell)s へのルーティングにおける不明な %(cell_type)s"

msgid "Unknown action"
msgstr "不明なアクション"

#, python-format
msgid "Unknown action %s"
msgstr "不明なアクション %s"

msgid "Unknown argument: port"
msgstr "不明な引数: port"

#, python-format
msgid "Unknown chain: %r"
msgstr "不明なチェーン: %r"

#, python-format
msgid "Unknown config drive format %(format)s. Select one of iso9660 or vfat."
msgstr ""
"不明なコンフィグドライブ形式 %(format)s です。「iso9660」または「vfat」のいず"
"れかを選択してください。"

#, python-format
msgid "Unknown delete_info type %s"
msgstr "不明な delete_info タイプ %s"

#, python-format
msgid "Unknown image_type=%s"
msgstr "不明な image_type=%s"

#, python-format
msgid "Unknown method '%(method)s' in compute API"
msgstr "コンピュート API 内の不明なメソッド '%(method)s'"

#, python-format
msgid "Unknown quota resources %(unknown)s."
msgstr "不明なクォータリソース %(unknown)s。"

msgid "Unknown sort direction, must be 'desc' or 'asc'"
msgstr "ソート方向が不明です。'desc' または 'asc' でなければなりません"

#, python-format
msgid "Unknown type: %s"
msgstr "不明なタイプ: %s"

msgid "Unrecognized legacy format."
msgstr "認識できない以前のフォーマットです。"

#, python-format
msgid "Unrecognized read_deleted value '%s'"
msgstr "認識されない read_deleted 値 '%s'"

#, python-format
msgid "Unrecognized value '%s' for CONF.running_deleted_instance_action"
msgstr "CONF.running_deleted_instance_action で認識されない値 '%s'"

msgid "Unsafe filenames in image"
msgstr "安全ではないファイル名がイメージ内にあります"

#, python-format
msgid "Unshelve attempted but the image %s cannot be found."
msgstr "復元が試行されましたが、イメージ %s が見つかりません。"

msgid "Unsupported Content-Type"
msgstr "サポートされない Content-Type"

msgid "Upgrade DB using Essex release first."
msgstr "最初に Essex リリースを使用して DB をアップグレードします。"

#, python-format
msgid "User %(username)s not found in password file."
msgstr "パスワードファイルにユーザー %(username)s が見つかりません。"

#, python-format
msgid "User %(username)s not found in shadow file."
msgstr "shadow ファイルにユーザー %(username)s が見つかりません。"

msgid "User data needs to be valid base 64."
msgstr "ユーザーデータは有効な Base64 でなければなりません。"

#, python-format
msgid ""
"User data too large. User data must be no larger than %(maxsize)s bytes once "
"base64 encoded. Your data is %(length)d bytes"
msgstr ""
"ユーザーデータが長すぎます。Base64 エンコードの場合、ユーザーデータが "
"%(maxsize)s バイトを超えることはできません。指定されたデータは %(length)d バ"
"イトです。"

msgid "User does not have admin privileges"
msgstr "ユーザーに管理者権限がありません"

msgid ""
"Using different block_device_mapping syntaxes is not allowed in the same "
"request."
msgstr "同じリクエスト内で異なる block_device_mapping 指定は使用できません。"

#, python-format
msgid ""
"VDI %(vdi_ref)s is %(virtual_size)d bytes which is larger than flavor size "
"of %(new_disk_size)d bytes."
msgstr ""
"VDI %(vdi_ref)s は %(virtual_size)d バイトです。これは、フレーバーのサイズで"
"ある %(new_disk_size)d バイトを超えています。"

#, python-format
msgid ""
"VDI not found on SR %(sr)s (vdi_uuid %(vdi_uuid)s, target_lun %(target_lun)s)"
msgstr ""
"SR %(sr)s で VDI が見つかりません (vdi_uuid %(vdi_uuid)s、target_lun "
"%(target_lun)s)"

#, fuzzy, python-format
msgid "VHD coalesce attempts exceeded (%d), giving up..."
msgstr "VHD 統合の試行時に (%d) を超過したため、中止します..."

msgid "VIF plugging is not supported by the Hyper-V driver."
msgstr "VIF 接続は Hyper-V ドライバーではサポートされていません。"

msgid "VIF unplugging is not supported by the Hyper-V driver."
msgstr "VIF 切断は Hyper-V ドライバーではサポートされていません。"

#, python-format
msgid ""
"VLAN tag is not appropriate for the port group %(bridge)s. Expected VLAN tag "
"is %(tag)s, but the one associated with the port group is %(pgroup)s."
msgstr ""
"ポートグループ %(bridge)s の VLAN タグが適切ではありません。必要な VLAN タグ"
"は %(tag)s ですが、ポートグループに関連付けられているのは %(pgroup)s です。"

#, python-format
msgid ""
"Value (%(value)s) for parameter Group%(property)s is invalid. Content "
"limited to '%(allowed)s'."
msgstr ""
"パラメーターグループ %(property)s の値 (%(value)s) が無効です。指定できる内容"
"は '%(allowed)s' だけです。"

#, python-format
msgid "Value must be >= 0 for field %s"
msgstr "フィールド %s の値は 0 以上である必要があります"

msgid "Value required for 'scality_sofs_config'"
msgstr "'scality_sofs_config' の値が必要です"

#, python-format
msgid ""
"Version %(req_ver)s is not supported by the API. Minimum is %(min_ver)s and "
"maximum is %(max_ver)s."
msgstr ""
"バージョン %(req_ver)s はこの API ではサポートされていません。最小"
"は%(min_ver)s、最大は %(max_ver)s です。"

msgid "Virtual Interface creation failed"
msgstr "仮想インターフェースの作成に失敗しました"

msgid "Virtual interface plugin failed"
msgstr "仮想インターフェースの接続に失敗しました"

#, python-format
msgid "Virtual machine mode '%(vmmode)s' is not recognised"
msgstr "仮想マシンモード '%(vmmode)s' は認識できません"

#, python-format
msgid "Virtual machine mode '%s' is not valid"
msgstr "仮想マシンモード '%s' が有効ではありません"

#, python-format
msgid ""
"Virtual switch associated with the network adapter %(adapter)s not found."
msgstr ""
"ネットワークアダプター %(adapter)s に関連付けられた仮想スイッチが見つかりませ"
"ん。"

#, python-format
msgid "Virtualization type '%(virt)s' is not supported by this compute driver"
msgstr ""
"このコンピュートドライバーでは仮想化タイプ '%(virt)s' はサポートされません"

msgid "VlanID"
msgstr "VLAN ID"

#, python-format
msgid "Volume %(volume_id)s could not be attached. Reason: %(reason)s"
msgstr "ボリューム %(volume_id)s を接続できません。理由: %(reason)s"

#, python-format
msgid "Volume %(volume_id)s could not be found."
msgstr "ボリューム %(volume_id)s が見つかりませんでした。"

#, python-format
msgid ""
"Volume %(volume_id)s did not finish being created even after we waited "
"%(seconds)s seconds or %(attempts)s attempts. And its status is "
"%(volume_status)s."
msgstr ""
"%(seconds)s 秒待機し、%(attempts)s 回試行したものの、ボリューム "
"%(volume_id)s を作成することができませんでした。状況は %(volume_status)s で"
"す。"

#, python-format
msgid "Volume %(volume_id)s is not attached to anything"
msgstr "ボリューム %(volume_id)s はどこにも接続されていません"

msgid "Volume does not belong to the requested instance."
msgstr "ボリュームが要求されたインスタンスに属していません。"

#, python-format
msgid ""
"Volume encryption is not supported for %(volume_type)s volume %(volume_id)s"
msgstr ""
"%(volume_type)s のボリューム %(volume_id)s に関してボリュームの暗号化はサポー"
"トされません。"

#, python-format
msgid ""
"Volume is smaller than the minimum size specified in image metadata. Volume "
"size is %(volume_size)i bytes, minimum size is %(image_min_disk)i bytes."
msgstr ""
"ボリュームがイメージのメタデータで指定された最小サイズよりも小さくなっていま"
"す。ボリュームサイズは %(volume_size)i バイト、最小サイズは "
"%(image_min_disk)i バイトです。"

msgid "Volume must be attached in order to detach."
msgstr "ボリュームを切り離すにはボリュームが接続されていなければいけません。"

msgid "Volume resource quota exceeded"
msgstr "ボリュームのリソースクォータを超過しました"

#, python-format
msgid ""
"Volume sets block size, but the current libvirt hypervisor '%s' does not "
"support custom block size"
msgstr ""
"ボリュームによってブロックサイズが設定されますが、現在の libvirt ハイパーバイ"
"ザー '%s' はカスタムブロックサイズをサポートしていません"

#, python-format
msgid "WARNING: fixed IP %s allocated to missing instance"
msgstr "警告: Fixed IP %s が存在しないインスタンスに割り当てられています"

#, python-format
msgid ""
"We do not support scheme '%s' under Python < 2.7.4, please use http or https"
msgstr ""
"Python < 2.7.4 ではスキーム '%s' はサポートされません。http またはhttps を使"
"用してください"

msgid "When resizing, instances must change flavor!"
msgstr "サイズ変更の際は、インスタンスのフレーバーを変更する必要があります。"

msgid ""
"When running server in SSL mode, you must specify both a cert_file and "
"key_file option value in your configuration file"
msgstr ""
"サーバーを SSL モードで実行する場合は、設定ファイルで cert_file と key_file "
"の両方のオプションに値を指定する必要があります"

#, python-format
msgid "Wrong quota method %(method)s used on resource %(res)s"
msgstr ""
"リソース %(res)s で使用されるクォータメソッド %(method)s が正しくありません"

msgid "Wrong type of hook method. Only 'pre' and 'post' type allowed"
msgstr ""
"フックメソッドのタイプが正しくありません。タイプ「pre」および「post」のみが許"
"可されています"

msgid "X-Forwarded-For is missing from request."
msgstr "リクエストに X-Forwarded-For がありません。"

msgid "X-Instance-ID header is missing from request."
msgstr "リクエストに X-Instance-ID ヘッダーがありません。"

msgid "X-Instance-ID-Signature header is missing from request."
msgstr "X-Instance-ID-Signature ヘッダーがリクエストにありません。"

msgid "X-Metadata-Provider is missing from request."
msgstr "リクエストに X-Metadata-Provider がありません。"

msgid "X-Tenant-ID header is missing from request."
msgstr "リクエストに X-Tenant-ID ヘッダーがありません。"

msgid "XAPI supporting relax-xsm-sr-check=true required"
msgstr "relax-xsm-sr-check=true をサポートする XAPI が必要です"

msgid "You are not allowed to delete the image."
msgstr "このイメージの削除は許可されていません。"

msgid ""
"You are not authorized to access the image the instance was started with."
msgstr ""
"インスタンスの起動時に使用されたイメージへのアクセスが許可されていません。"

msgid "You must implement __call__"
msgstr "__call__ を実装しなければなりません"

msgid "You should specify images_rbd_pool flag to use rbd images."
msgstr ""
"rbd イメージを使用するには images_rbd_pool フラグを指定する必要があります。"

msgid "You should specify images_volume_group flag to use LVM images."
msgstr ""
"LVM イメージを使用するには images_volume_group フラグを指定する必要がありま"
"す。"

msgid ""
"Your libvirt version does not support the VIR_DOMAIN_XML_MIGRATABLE flag or "
"your destination node does not support retrieving listen addresses.  In "
"order for live migration to work properly you must either disable serial "
"console or upgrade your libvirt version."
msgstr ""
"libvirt のバージョンが VIR_DOMAIN_XML_MIGRATABLE フラグをサポートしないか、宛"
"先ノードが リッスンアドレスの取得をサポートしません。ライブマイグレーションが"
"適切に機能するには、シリアルコンソールを無効化するか、libvirt のバージョンを"
"アップグレードする必要があります。"

msgid ""
"Your libvirt version does not support the VIR_DOMAIN_XML_MIGRATABLE flag or "
"your destination node does not support retrieving listen addresses.  In "
"order for live migration to work properly, you must configure the graphics "
"(VNC and/or SPICE) listen addresses to be either the catch-all address "
"(0.0.0.0 or ::) or the local address (127.0.0.1 or ::1)."
msgstr ""
"使用している libvirt バージョンが VIR_DOMAIN_XML_MIGRATABLE フラグをサポート"
"していないか、または宛先ノードがリッスンアドレスの取得をサポートしていませ"
"ん。ライブマイグレーションが正しく機能するには、グラフィックス (VNC および "
"SPICE またはそのいずれか) listen アドレスを、 catch-all アドレス (0.0.0.0 ま"
"たは ::) またはローカルアドレス (127.0.0.1 または ::1) のいずれかに設定する必"
"要があります。"

msgid "Zero fixed IPs could be found."
msgstr "Fixed IP が見つかりません。"

msgid "Zero floating IPs available."
msgstr "使用可能な Floating IP はありません。"

msgid "Zero floating IPs exist."
msgstr "Floating IP が存在しません。"

msgid "admin password can't be changed on existing disk"
msgstr "既存のディスク上で管理者パスワードを変更することはできません"

msgid "aggregate deleted"
msgstr "アグリゲートが削除されました"

msgid "aggregate in error"
msgstr "アグリゲートでエラーが発生しました"

#, python-format
msgid "assert_can_migrate failed because: %s"
msgstr "assert_can_migrate が失敗しました: 理由 %s"

msgid "cannot understand JSON"
msgstr "JSON を解釈できません"

msgid "clone() is not implemented"
msgstr "clone() は実装されていません"

#, python-format
msgid "connect info: %s"
msgstr "接続情報: %s"

#, python-format
msgid "connecting to: %(host)s:%(port)s"
msgstr "%(host)s:%(port)s に接続中です"

#, python-format
msgid "destination is %(target_cell)s but routing_path is %(routing_path)s"
msgstr "宛先は %(target_cell)s ですが、routing_path は %(routing_path)s です"

msgid "direct_snapshot() is not implemented"
msgstr "direct_snapshot() が実装されていません"

msgid "disk"
msgstr "ディスク"

#, python-format
msgid "disk type '%s' not supported"
msgstr "ディスクタイプ '%s' はサポートされていません"

#, python-format
msgid "empty project id for instance %s"
msgstr "インスタンス %s のプロジェクト ID が空です"

msgid "error setting admin password"
msgstr "管理者パスワードの設定中にエラーが発生しました"

#, python-format
msgid "error: %s"
msgstr "エラー: %s"

#, python-format
msgid "failed to generate X509 fingerprint. Error message: %s"
msgstr "X.509 フィンガープリントの生成に失敗しました。エラーメッセージ: %s"

msgid "failed to generate fingerprint"
msgstr "フィンガープリントの生成に失敗しました"

msgid "filename cannot be None"
msgstr "ファイル名を None にすることはできません"

msgid "floating IP is already associated"
msgstr "Floating IP は既に割り当てられています"

msgid "floating IP not found"
msgstr "Floating IP が見つかりません"

#, python-format
msgid "fmt=%(fmt)s backed by: %(backing_file)s"
msgstr "fmt=%(fmt)s は %(backing_file)s でサポートされています"

msgid "fping utility is not found."
msgstr "fping ユーティリティーが見つかりません。"

msgid "host"
msgstr "ホスト"

msgid "hostname"
msgstr "ホスト名"

#, python-format
msgid "href %s does not contain version"
msgstr "href %s にバージョンが含まれていません"

msgid "id"
msgstr "ID"

msgid "id cannot contain leading and/or trailing whitespace(s)"
msgstr "ID の先頭や末尾に空白文字は使用できません"

msgid "image"
msgstr "イメージ"

msgid "image already mounted"
msgstr "イメージは既にマウントされています"

msgid "index"
msgstr "インデックス"

msgid "instance"
msgstr "インスタンス"

#, python-format
msgid "instance %s is not running"
msgstr "インスタンス %s は実行されていません"

msgid "instance has a kernel or ramdisk but not both"
msgstr ""
"インスタンスにはカーネルディスクと RAM ディスクの一方はありますが、両方はあり"
"ません"

msgid "instance is a required argument to use @refresh_cache"
msgstr "@refresh_cache を使用する場合、インスタンスは必須の引数です"

msgid "instance is not in a suspended state"
msgstr "インスタンスは休止状態ではありません"

msgid "instance is not powered on"
msgstr "インスタンスの電源がオンになっていません"

msgid "instance is powered off and cannot be suspended."
msgstr "インスタンスは電源オフになっています。休止できません。"

#, python-format
msgid "instance_id %s could not be found as device id on any ports"
msgstr "instance_id %s がデバイス ID に設定されたポートが見つかりませんでした"

#, python-format
msgid "invalid %(property)s %(attr)s"
msgstr "%(property)s の %(attr)s が無効です"

msgid "is_public must be a boolean"
msgstr "is_public はブール値でなければなりません"

msgid "kernel"
msgstr "カーネル"

msgid "keymgr.fixed_key not defined"
msgstr "keymgr.fixed_key が定義されていません"

msgid "l3driver call to add floating IP failed"
msgstr "Floating IP を追加するための l3driver の呼び出しが失敗しました"

msgid "launched"
msgstr "起動場所"

msgid "ldap not installed"
msgstr "ldap がインストールされていません"

#, python-format
msgid "libguestfs installed but not usable (%s)"
msgstr "libguestfs はインストールされていますが、使用できません (%s)"

#, python-format
msgid "libguestfs is not installed (%s)"
msgstr "libguestfs がインストールされていません (%s)"

msgid "libvirt error while requesting blockjob info."
msgstr "blockjob 情報を要求しているときに libvirt エラーが発生しました。"

#, python-format
msgid "marker [%s] not found"
msgstr "マーカー [%s] が見つかりません"

#, python-format
msgid "max rows must be <= %(max_value)d"
msgstr "最大行数は %(max_value)d 以上である必要があります"

msgid "max_count cannot be greater than 1 if an fixed_ip is specified."
msgstr ""
"fixed_ip が指定されている場合、max_count を 1 より大きくすることはできませ"
"ん。"

msgid "memory"
msgstr "メモリー"

msgid "min_count must be <= max_count"
msgstr "min_count は max_count 以下でなければなりません"

#, python-format
msgid "nbd device %s did not show up"
msgstr "nbd デバイス %s が出現しません"

msgid "nbd unavailable: module not loaded"
msgstr "nbd が使用不可です: モジュールがロードされていません"

msgid "network"
msgstr "ネットワーク"

msgid "no hosts to remove"
msgstr "削除するホストがありません"

#, python-format
msgid "no match found for %s"
msgstr "%s に合致するものが見つかりません"

#, python-format
msgid "no usable parent snapshot for volume %s"
msgstr "ボリューム %s に関して使用可能な親スナップショットがありません"

#, python-format
msgid "no write permission on storage pool %s"
msgstr "ストレージプール %s に書き込み権限がありません"

msgid "node"
msgstr "ノード"

#, python-format
msgid "not able to execute ssh command: %s"
msgstr "ssh コマンドを実行できません: %s"

msgid ""
"nova-idmapshift is a tool that properly sets the ownership of a filesystem "
"for use with linux user namespaces.  This tool can only be used with linux "
"lxc containers.  See the man page for details."
msgstr ""
"nova-idmapshift は、Linux ユーザーの名前空間で使用可能なファイルシステムの所"
"有者を適切に設定するツールです。このツールは Linux lxc コンテナーでしか使用で"
"きません。詳細についてはメインページを参照してください。"

msgid "old style configuration can use only dictionary or memcached backends"
msgstr ""
"古い形式の設定では、ディクショナリーと memcached のバックエンドのみを使用でき"
"ます"

msgid "operation time out"
msgstr "操作がタイムアウトしました"

#, python-format
msgid "partition %s not found"
msgstr "パーティション %s が見つかりません"

#, python-format
msgid "partition search unsupported with %s"
msgstr "パーティションの検索は %s ではサポートされていません"

msgid "pause not supported for vmwareapi"
msgstr "vmwareapi では一時停止はサポートされていません"

msgid ""
"printable characters except !, ., @, with at least one non space character"
msgstr ""
"!、.、@ 以外の印刷可能な文字。1 つ以上のスペースではない文字が必要です。"

msgid ""
"printable characters except !, ., @. Can not start or end with whitespace."
msgstr ""
"!、.、@ 以外の印刷可能な文字。空白で開始または終了することはできません。"

msgid "printable characters with at least one non space character"
msgstr "1 つ以上のスペースではない文字を含む印刷可能な文字。"

msgid "printable characters. Can not start or end with whitespace."
msgstr "印刷可能な文字。空白で開始または終了することはできません。"

msgid "project"
msgstr "プロジェクト"

#, python-format
msgid "qemu-img failed to execute on %(path)s : %(exp)s"
msgstr "%(path)s で qemu-img を実行できませんでした: %(exp)s"

#, python-format
msgid "qemu-nbd error: %s"
msgstr "qemu-nbd エラー: %s"

msgid "ramdisk"
msgstr "RAM ディスク"

msgid "rbd python libraries not found"
msgstr "rbd python ライブラリーが見つかりません"

#, python-format
msgid "read_deleted can only be one of 'no', 'yes' or 'only', not %r"
msgstr ""
"read_deleted に指定できるのは 'no', 'yes', 'only' のいずれかです。%r は指定で"
"きません。"

msgid "serve() can only be called once"
msgstr "serve() は一度しか呼び出せません"

msgid "service is a mandatory argument for DB based ServiceGroup driver"
msgstr "サービスは DB ベースの ServiceGroup ドライバーの必須の引数です"

msgid "service is a mandatory argument for Memcached based ServiceGroup driver"
msgstr "service は Memcached ベースの ServiceGroup ドライバーの必須の引数です"

msgid "set_admin_password is not implemented by this driver or guest instance."
msgstr ""
"set_admin_password は、このドライバーまたはゲストインスタンスでは実装されてい"
"ません。"

msgid "setup in progress"
msgstr "セットアップが進行中です"

#, python-format
msgid "snapshot for %s"
msgstr "%s のスナップショット"

msgid "snapshot_id required in create_info"
msgstr "create_info には snapshot_id が必要です"

msgid "start address"
msgstr "開始アドレス"

msgid "state"
msgstr "状態"

msgid "sudo failed, continuing as if nothing happened"
msgstr "sudo が失敗しました。何も起こらなかったものとして続行します"

msgid "token not provided"
msgstr "トークンが指定されていません"

msgid "too many body keys"
msgstr "本文にキーが多すぎます"

msgid "type"
msgstr "タイプ"

msgid "unpause not supported for vmwareapi"
msgstr "vmwareapi では一時停止解除はサポートされていません"

msgid "user"
msgstr "ユーザー"

msgid "uuid"
msgstr "UUID"

#, python-format
msgid ""
"vSwitch which contains the port group %(bridge)s is not associated with the "
"desired physical adapter. Expected vSwitch is %(expected)s, but the one "
"associated is %(actual)s."
msgstr ""
"ポートグループ %(bridge)s を含む vSwitch が目的の物理アダプターに関連付けられ"
"ていません。必要な vSwitch は %(expected)s ですが、関連付けられているのは "
"%(actual)s です。"

msgid "vcpu"
msgstr "vCPU"

msgid "version should be an integer"
msgstr "バージョンは整数でなければなりません"

#, python-format
msgid "vg %s must be LVM volume group"
msgstr "vg %s は LVM ボリュームグループでなければなりません"

#, python-format
msgid "vhostuser_sock_path not present in vif_details for vif %(vif_id)s"
msgstr "vhostuser_sock_path が vif %(vif_id)s の vif_details にありません"

#, python-format
msgid "vif type %s not supported"
msgstr "vif タイプ %s はサポートされません"

msgid "vif_type parameter must be present for this vif_driver implementation"
msgstr "この vif_driver の実装では vif_type パラメーターが必要です"

msgid "vlan must be an integer"
msgstr "vlan は整数でなければなりません"

#, python-format
msgid "volume %s already attached"
msgstr "ボリューム %s は既に接続されています"

#, python-format
msgid "volume %s already detached"
msgstr "ボリューム %s は既に切り離されています"

#, python-format
msgid "volume '%(vol)s' status must be 'available'. Currently in '%(status)s'"
msgstr ""
"ボリューム '%(vol)s' の状況は「使用可能」でなければなりませんが、現在は "
"'%(status)s' です"

#, python-format
msgid ""
"volume '%(vol)s' status must be 'in-use'. Currently in '%(status)s' status"
msgstr ""
"ボリューム '%(vol)s' の状況は「使用中」でなければなりませんが、現在の状況は "
"'%(status)s' です"

#, python-format
msgid "volume_id not found: %s"
msgstr "volume_id が見つかりません: %s"

#, python-format
msgid "xenapi.fake does not have an implementation for %s"
msgstr "xenapi.fake には %s が実装されていません。"

#, python-format
msgid ""
"xenapi.fake does not have an implementation for %s or it has been called "
"with the wrong number of arguments"
msgstr "xenapi.fake に %s の実装がないか、引数の数が誤っています。"

msgid "you can not pass av_zone if the scope is public"
msgstr "スコープがパブリックの場合、av_zone を渡すことはできません"

msgid "you can not pass project if the scope is private"
msgstr "スコープがプライベートである場合、プロジェクトを渡すことはできません"

msgid "zone"
msgstr "ゾーン"
